// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApplyRuntimeRequest`, `RevisionDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`

/// Read-only relaunch command the external upgrade runner executes (R4-29).
class AppRestartCommandDto {
  final String program;
  final String workingDir;

  const AppRestartCommandDto({required this.program, required this.workingDir});

  @override
  int get hashCode => program.hashCode ^ workingDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppRestartCommandDto &&
          runtimeType == other.runtimeType &&
          program == other.program &&
          workingDir == other.workingDir;
}

/// Result of rolling back a staged application upgrade (R4-29).
class AppRollbackResultDto {
  final bool ok;
  final String? restored;
  final ErrorDto? error;

  const AppRollbackResultDto({required this.ok, this.restored, this.error});

  @override
  int get hashCode => ok.hashCode ^ restored.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppRollbackResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          restored == other.restored &&
          error == other.error;
}

/// One applied core update.
class AppliedCoreDto {
  final String core;
  final String version;
  final String? installedDir;
  final String? keptPrevious;

  const AppliedCoreDto({
    required this.core,
    required this.version,
    this.installedDir,
    this.keptPrevious,
  });

  @override
  int get hashCode =>
      core.hashCode ^
      version.hashCode ^
      installedDir.hashCode ^
      keptPrevious.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppliedCoreDto &&
          runtimeType == other.runtimeType &&
          core == other.core &&
          version == other.version &&
          installedDir == other.installedDir &&
          keptPrevious == other.keptPrevious;
}

/// Applied inbound proxy protocol + bound port of the running session (R4-24).
/// Carries no authentication/secret fields by construction.
class AppliedInboundDto {
  /// `http` / `socks` / `mixed`, or `None` when nothing is applied.
  final String? protocol;

  /// Actual bound local proxy port, when known.
  final int? port;

  const AppliedInboundDto({this.protocol, this.port});

  @override
  int get hashCode => protocol.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppliedInboundDto &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          port == other.port;
}

/// Result of applying core updates.
class ApplyCoreResultDto {
  final bool ok;
  final List<AppliedCoreDto> applied;
  final List<String> skipped;
  final ErrorDto? error;

  const ApplyCoreResultDto({
    required this.ok,
    required this.applied,
    required this.skipped,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ applied.hashCode ^ skipped.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyCoreResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          applied == other.applied &&
          skipped == other.skipped &&
          error == other.error;
}

/// Result of `apply_runtime`.
class ApplyRuntimeResult {
  final bool ok;
  final String? operationId;
  final ErrorDto? error;

  const ApplyRuntimeResult({required this.ok, this.operationId, this.error});

  @override
  int get hashCode => ok.hashCode ^ operationId.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyRuntimeResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          operationId == other.operationId &&
          error == other.error;
}

/// Bundles discovered under a parent directory.
class BackupListDto {
  final List<BackupManifestDto> items;
  final ErrorDto? error;

  const BackupListDto({required this.items, this.error});

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupListDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}

/// Versioned backup manifest summary.
class BackupManifestDto {
  final int formatVersion;
  final PlatformInt64 createdAt;
  final String appSourceCommit;
  final String dbSha256;
  final String? configSha256;
  final String? root;
  final int resourceCount;
  final List<EntityCountDto> entityCounts;

  const BackupManifestDto({
    required this.formatVersion,
    required this.createdAt,
    required this.appSourceCommit,
    required this.dbSha256,
    this.configSha256,
    this.root,
    required this.resourceCount,
    required this.entityCounts,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^
      createdAt.hashCode ^
      appSourceCommit.hashCode ^
      dbSha256.hashCode ^
      configSha256.hashCode ^
      root.hashCode ^
      resourceCount.hashCode ^
      entityCounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupManifestDto &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          createdAt == other.createdAt &&
          appSourceCommit == other.appSourceCommit &&
          dbSha256 == other.dbSha256 &&
          configSha256 == other.configSha256 &&
          root == other.root &&
          resourceCount == other.resourceCount &&
          entityCounts == other.entityCounts;
}

/// Result of writing a local backup bundle.
class BackupResultDto {
  final bool ok;
  final String? root;
  final BackupManifestDto? manifest;
  final ErrorDto? error;

  const BackupResultDto({
    required this.ok,
    this.root,
    this.manifest,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ root.hashCode ^ manifest.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          root == other.root &&
          manifest == other.manifest &&
          error == other.error;
}

/// Result of `cancel_job`.
class CancelResult {
  final CancelOutcome outcome;
  final ErrorDto? error;

  const CancelResult({required this.outcome, this.error});

  @override
  int get hashCode => outcome.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CancelResult &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          error == other.error;
}

/// Core capability entry.
class CapabilityDto {
  final CoreType core;
  final List<ConfigType> configTypes;
  final bool structuredGeneration;
  final bool updateSupported;

  const CapabilityDto({
    required this.core,
    required this.configTypes,
    required this.structuredGeneration,
    required this.updateSupported,
  });

  @override
  int get hashCode =>
      core.hashCode ^
      configTypes.hashCode ^
      structuredGeneration.hashCode ^
      updateSupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapabilityDto &&
          runtimeType == other.runtimeType &&
          core == other.core &&
          configTypes == other.configTypes &&
          structuredGeneration == other.structuredGeneration &&
          updateSupported == other.updateSupported;
}

/// Log/temporary-file cleanup result.
class CleanupResultDto {
  final bool ok;
  final int deleted;
  final BigInt bytes;
  final int skipped;
  final ErrorDto? error;

  const CleanupResultDto({
    required this.ok,
    required this.deleted,
    required this.bytes,
    required this.skipped,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      deleted.hashCode ^
      bytes.hashCode ^
      skipped.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CleanupResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          deleted == other.deleted &&
          bytes == other.bytes &&
          skipped == other.skipped &&
          error == other.error;
}

/// Result of a batch copy.
class CopyProfilesResult {
  final bool ok;
  final List<ProfileDto> copies;
  final ErrorDto? error;

  const CopyProfilesResult({
    required this.ok,
    required this.copies,
    this.error,
  });

  @override
  int get hashCode => ok.hashCode ^ copies.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyProfilesResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          copies == other.copies &&
          error == other.error;
}

/// One target's check result.
class CoreUpdateDto {
  final String core;
  final bool supported;
  final String? note;
  final String? installedVersion;
  final String? remoteVersion;
  final bool hasUpdate;
  final String? assetName;
  final String? downloadUrl;
  final String? expectedSha256;
  final String? dgstUrl;

  const CoreUpdateDto({
    required this.core,
    required this.supported,
    this.note,
    this.installedVersion,
    this.remoteVersion,
    required this.hasUpdate,
    this.assetName,
    this.downloadUrl,
    this.expectedSha256,
    this.dgstUrl,
  });

  @override
  int get hashCode =>
      core.hashCode ^
      supported.hashCode ^
      note.hashCode ^
      installedVersion.hashCode ^
      remoteVersion.hashCode ^
      hasUpdate.hashCode ^
      assetName.hashCode ^
      downloadUrl.hashCode ^
      expectedSha256.hashCode ^
      dgstUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreUpdateDto &&
          runtimeType == other.runtimeType &&
          core == other.core &&
          supported == other.supported &&
          note == other.note &&
          installedVersion == other.installedVersion &&
          remoteVersion == other.remoteVersion &&
          hasUpdate == other.hasUpdate &&
          assetName == other.assetName &&
          downloadUrl == other.downloadUrl &&
          expectedSha256 == other.expectedSha256 &&
          dgstUrl == other.dgstUrl;
}

/// Installed-core probe result.
class CoreVersionsDto {
  final List<InstalledCoreDto> items;
  final ErrorDto? error;

  const CoreVersionsDto({required this.items, this.error});

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreVersionsDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}

/// Result of `custom_import_file`: the stored config file name on success.
class CustomFileResult {
  final bool ok;
  final String? fileName;
  final ErrorDto? error;

  const CustomFileResult({required this.ok, this.fileName, this.error});

  @override
  int get hashCode => ok.hashCode ^ fileName.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFileResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          fileName == other.fileName &&
          error == other.error;
}

/// Result of a batch delete.
class DeleteProfilesResult {
  final bool ok;
  final BigInt removed;
  final ErrorDto? error;

  const DeleteProfilesResult({
    required this.ok,
    required this.removed,
    this.error,
  });

  @override
  int get hashCode => ok.hashCode ^ removed.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteProfilesResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          removed == other.removed &&
          error == other.error;
}

/// Result of `delete_sub_items`.
class DeleteSubsResult {
  final bool ok;
  final BigInt removed;
  final ErrorDto? error;

  const DeleteSubsResult({required this.ok, required this.removed, this.error});

  @override
  int get hashCode => ok.hashCode ^ removed.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteSubsResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          removed == other.removed &&
          error == other.error;
}

/// One per-table row count inside a backup manifest.
class EntityCountDto {
  final String table;
  final BigInt sourceRows;
  final BigInt importedRows;
  final BigInt migratedRows;
  final BigInt skippedRows;

  const EntityCountDto({
    required this.table,
    required this.sourceRows,
    required this.importedRows,
    required this.migratedRows,
    required this.skippedRows,
  });

  @override
  int get hashCode =>
      table.hashCode ^
      sourceRows.hashCode ^
      importedRows.hashCode ^
      migratedRows.hashCode ^
      skippedRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityCountDto &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          sourceRows == other.sourceRows &&
          importedRows == other.importedRows &&
          migratedRows == other.migratedRows &&
          skippedRows == other.skippedRows;
}

/// Error DTO carrying the stable contract fields.
class ErrorDto {
  final String code;
  final String messageKey;
  final String? fieldPath;
  final bool retryable;
  final String? operationId;
  final String? detail;

  const ErrorDto({
    required this.code,
    required this.messageKey,
    this.fieldPath,
    required this.retryable,
    this.operationId,
    this.detail,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      messageKey.hashCode ^
      fieldPath.hashCode ^
      retryable.hashCode ^
      operationId.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          messageKey == other.messageKey &&
          fieldPath == other.fieldPath &&
          retryable == other.retryable &&
          operationId == other.operationId &&
          detail == other.detail;
}

/// Event envelope delivered on the FRB stream.
class EventEnvelopeDto {
  final BigInt epoch;
  final BigInt seq;
  final String kind;

  /// `true` for control events, `false` for telemetry.
  final bool control;

  /// Raw JSON payload.
  final String payloadJson;

  const EventEnvelopeDto({
    required this.epoch,
    required this.seq,
    required this.kind,
    required this.control,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      epoch.hashCode ^
      seq.hashCode ^
      kind.hashCode ^
      control.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventEnvelopeDto &&
          runtimeType == other.runtimeType &&
          epoch == other.epoch &&
          seq == other.seq &&
          kind == other.kind &&
          control == other.control &&
          payloadJson == other.payloadJson;
}

/// External-upgrade spec for the application itself (never executed here).
class ExternalSpecDto {
  final bool ok;
  final String? helperExe;
  final String? source;
  final String? installRoot;
  final int waitForPid;
  final List<String> args;
  final ErrorDto? error;

  const ExternalSpecDto({
    required this.ok,
    this.helperExe,
    this.source,
    this.installRoot,
    required this.waitForPid,
    required this.args,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      helperExe.hashCode ^
      source.hashCode ^
      installRoot.hashCode ^
      waitForPid.hashCode ^
      args.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalSpecDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          helperExe == other.helperExe &&
          source == other.source &&
          installRoot == other.installRoot &&
          waitForPid == other.waitForPid &&
          args == other.args &&
          error == other.error;
}

/// Result of importing from clipboard text.
class ImportResult {
  final bool ok;
  final int imported;
  final List<ProfileDto> profiles;
  final List<ParseIssueDto> errors;
  final ErrorDto? error;

  const ImportResult({
    required this.ok,
    required this.imported,
    required this.profiles,
    required this.errors,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      imported.hashCode ^
      profiles.hashCode ^
      errors.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          imported == other.imported &&
          profiles == other.profiles &&
          errors == other.errors &&
          error == other.error;
}

/// Condensed import report for the UI.
class ImportSummaryDto {
  final bool ok;
  final String status;
  final int sourceVersion;
  final BigInt importedRows;
  final int warnings;
  final int errors;
  final String message;
  final ErrorDto? error;

  const ImportSummaryDto({
    required this.ok,
    required this.status,
    required this.sourceVersion,
    required this.importedRows,
    required this.warnings,
    required this.errors,
    required this.message,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      status.hashCode ^
      sourceVersion.hashCode ^
      importedRows.hashCode ^
      warnings.hashCode ^
      errors.hashCode ^
      message.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportSummaryDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          status == other.status &&
          sourceVersion == other.sourceVersion &&
          importedRows == other.importedRows &&
          warnings == other.warnings &&
          errors == other.errors &&
          message == other.message &&
          error == other.error;
}

/// One installed core directory.
class InstalledCoreDto {
  final String core;
  final String dir;
  final String version;
  final String? executable;

  const InstalledCoreDto({
    required this.core,
    required this.dir,
    required this.version,
    this.executable,
  });

  @override
  int get hashCode =>
      core.hashCode ^ dir.hashCode ^ version.hashCode ^ executable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstalledCoreDto &&
          runtimeType == other.runtimeType &&
          core == other.core &&
          dir == other.dir &&
          version == other.version &&
          executable == other.executable;
}

/// Active job summary.
class JobDto {
  final String jobId;
  final String kind;
  final JobState state;

  /// `None` when the stage is unknown (never fake a percent).
  final int? percent;
  final String? stageKey;
  final String? errorCode;
  final String? errorMessageKey;

  const JobDto({
    required this.jobId,
    required this.kind,
    required this.state,
    this.percent,
    this.stageKey,
    this.errorCode,
    this.errorMessageKey,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      percent.hashCode ^
      stageKey.hashCode ^
      errorCode.hashCode ^
      errorMessageKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          kind == other.kind &&
          state == other.state &&
          percent == other.percent &&
          stageKey == other.stageKey &&
          errorCode == other.errorCode &&
          errorMessageKey == other.errorMessageKey;
}

/// Read-only status of a prior runtime operation (R4-04 reconcile). `found`
/// distinguishes "no such operation" from a status whose state is not-yet-run.
class OperationStatusDto {
  final bool found;
  final String operationId;
  final String? jobId;
  final JobState state;
  final CancelOutcome? cancel;
  final ErrorDto? error;

  const OperationStatusDto({
    required this.found,
    required this.operationId,
    this.jobId,
    required this.state,
    this.cancel,
    this.error,
  });

  @override
  int get hashCode =>
      found.hashCode ^
      operationId.hashCode ^
      jobId.hashCode ^
      state.hashCode ^
      cancel.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationStatusDto &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          operationId == other.operationId &&
          jobId == other.jobId &&
          state == other.state &&
          cancel == other.cancel &&
          error == other.error;
}

/// A located per-item parse failure.
class ParseIssueDto {
  final String code;
  final String message;
  final int? itemIndex;
  final BigInt? byteOffset;

  const ParseIssueDto({
    required this.code,
    required this.message,
    this.itemIndex,
    this.byteOffset,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      message.hashCode ^
      itemIndex.hashCode ^
      byteOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseIssueDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          itemIndex == other.itemIndex &&
          byteOffset == other.byteOffset;
}

/// A profile row carrying every editable field.
class ProfileDto {
  final String indexId;
  final ConfigType configType;
  final CoreType? coreType;
  final int configVersion;
  final String subid;
  final bool isSub;
  final int? preSocksPort;
  final bool displayLog;
  final String remarks;
  final String address;
  final int port;
  final String password;
  final String username;
  final String network;
  final bool? muxEnabled;
  final String? finalmask;
  final SecurityDto security;
  final ProtocolExtraDto protoExtra;
  final TransportExtraDto transportExtra;

  /// Opaque unknown-extension JSON, preserved for round-trip.
  final String extraJson;

  const ProfileDto({
    required this.indexId,
    required this.configType,
    this.coreType,
    required this.configVersion,
    required this.subid,
    required this.isSub,
    this.preSocksPort,
    required this.displayLog,
    required this.remarks,
    required this.address,
    required this.port,
    required this.password,
    required this.username,
    required this.network,
    this.muxEnabled,
    this.finalmask,
    required this.security,
    required this.protoExtra,
    required this.transportExtra,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      indexId.hashCode ^
      configType.hashCode ^
      coreType.hashCode ^
      configVersion.hashCode ^
      subid.hashCode ^
      isSub.hashCode ^
      preSocksPort.hashCode ^
      displayLog.hashCode ^
      remarks.hashCode ^
      address.hashCode ^
      port.hashCode ^
      password.hashCode ^
      username.hashCode ^
      network.hashCode ^
      muxEnabled.hashCode ^
      finalmask.hashCode ^
      security.hashCode ^
      protoExtra.hashCode ^
      transportExtra.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          indexId == other.indexId &&
          configType == other.configType &&
          coreType == other.coreType &&
          configVersion == other.configVersion &&
          subid == other.subid &&
          isSub == other.isSub &&
          preSocksPort == other.preSocksPort &&
          displayLog == other.displayLog &&
          remarks == other.remarks &&
          address == other.address &&
          port == other.port &&
          password == other.password &&
          username == other.username &&
          network == other.network &&
          muxEnabled == other.muxEnabled &&
          finalmask == other.finalmask &&
          security == other.security &&
          protoExtra == other.protoExtra &&
          transportExtra == other.transportExtra &&
          extraJson == other.extraJson;
}

/// Query filter for `query_profiles`.
class ProfileFilterDto {
  final String? text;
  final List<ConfigType> configTypes;
  final String? subid;

  const ProfileFilterDto({this.text, required this.configTypes, this.subid});

  @override
  int get hashCode => text.hashCode ^ configTypes.hashCode ^ subid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileFilterDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          configTypes == other.configTypes &&
          subid == other.subid;
}

/// One page of profiles with a stable cursor.
class ProfilePageDto {
  final List<ProfileDto> items;
  final BigInt total;
  final BigInt? nextCursor;

  const ProfilePageDto({
    required this.items,
    required this.total,
    this.nextCursor,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode ^ nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfilePageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          nextCursor == other.nextCursor;
}

/// Sort key for `query_profiles`.
enum ProfileSortDto { remarks, address, delay, indexId }

/// `ProtocolExtraItem` (30 properties) exposed to the editor.
class ProtocolExtraDto {
  final bool? uot;
  final String? congestionControl;
  final String? httpHeaders;
  final String? alterId;
  final String? vmessSecurity;
  final String? flow;
  final String? vlessEncryption;
  final String? ssMethod;
  final String? wgPublicKey;
  final String? wgPresharedKey;
  final String? wgInterfaceAddress;
  final String? wgReserved;
  final int? wgMtu;
  final String? wgDns;
  final String? salamanderPass;
  final int? upMbps;
  final int? downMbps;
  final String? ports;
  final String? hopInterval;
  final String? hy2RealmUrl;
  final String? geckoMinPacketSize;
  final String? geckoMaxPacketSize;
  final int? insecureConcurrency;
  final bool? naiveQuic;
  final String? groupType;
  final String? childItems;
  final String? subChildItems;
  final String? filter;

  /// Numeric `EMultipleLoad` value.
  final int? multipleLoad;
  final bool? isSingboxEndpoint;

  /// Opaque unknown-extension JSON, preserved for round-trip.
  final String extraJson;

  const ProtocolExtraDto({
    this.uot,
    this.congestionControl,
    this.httpHeaders,
    this.alterId,
    this.vmessSecurity,
    this.flow,
    this.vlessEncryption,
    this.ssMethod,
    this.wgPublicKey,
    this.wgPresharedKey,
    this.wgInterfaceAddress,
    this.wgReserved,
    this.wgMtu,
    this.wgDns,
    this.salamanderPass,
    this.upMbps,
    this.downMbps,
    this.ports,
    this.hopInterval,
    this.hy2RealmUrl,
    this.geckoMinPacketSize,
    this.geckoMaxPacketSize,
    this.insecureConcurrency,
    this.naiveQuic,
    this.groupType,
    this.childItems,
    this.subChildItems,
    this.filter,
    this.multipleLoad,
    this.isSingboxEndpoint,
    required this.extraJson,
  });

  static Future<ProtocolExtraDto> default_() =>
      RustLib.instance.api.crateApiContractProtocolExtraDtoDefault();

  @override
  int get hashCode =>
      uot.hashCode ^
      congestionControl.hashCode ^
      httpHeaders.hashCode ^
      alterId.hashCode ^
      vmessSecurity.hashCode ^
      flow.hashCode ^
      vlessEncryption.hashCode ^
      ssMethod.hashCode ^
      wgPublicKey.hashCode ^
      wgPresharedKey.hashCode ^
      wgInterfaceAddress.hashCode ^
      wgReserved.hashCode ^
      wgMtu.hashCode ^
      wgDns.hashCode ^
      salamanderPass.hashCode ^
      upMbps.hashCode ^
      downMbps.hashCode ^
      ports.hashCode ^
      hopInterval.hashCode ^
      hy2RealmUrl.hashCode ^
      geckoMinPacketSize.hashCode ^
      geckoMaxPacketSize.hashCode ^
      insecureConcurrency.hashCode ^
      naiveQuic.hashCode ^
      groupType.hashCode ^
      childItems.hashCode ^
      subChildItems.hashCode ^
      filter.hashCode ^
      multipleLoad.hashCode ^
      isSingboxEndpoint.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolExtraDto &&
          runtimeType == other.runtimeType &&
          uot == other.uot &&
          congestionControl == other.congestionControl &&
          httpHeaders == other.httpHeaders &&
          alterId == other.alterId &&
          vmessSecurity == other.vmessSecurity &&
          flow == other.flow &&
          vlessEncryption == other.vlessEncryption &&
          ssMethod == other.ssMethod &&
          wgPublicKey == other.wgPublicKey &&
          wgPresharedKey == other.wgPresharedKey &&
          wgInterfaceAddress == other.wgInterfaceAddress &&
          wgReserved == other.wgReserved &&
          wgMtu == other.wgMtu &&
          wgDns == other.wgDns &&
          salamanderPass == other.salamanderPass &&
          upMbps == other.upMbps &&
          downMbps == other.downMbps &&
          ports == other.ports &&
          hopInterval == other.hopInterval &&
          hy2RealmUrl == other.hy2RealmUrl &&
          geckoMinPacketSize == other.geckoMinPacketSize &&
          geckoMaxPacketSize == other.geckoMaxPacketSize &&
          insecureConcurrency == other.insecureConcurrency &&
          naiveQuic == other.naiveQuic &&
          groupType == other.groupType &&
          childItems == other.childItems &&
          subChildItems == other.subChildItems &&
          filter == other.filter &&
          multipleLoad == other.multipleLoad &&
          isSingboxEndpoint == other.isSingboxEndpoint &&
          extraJson == other.extraJson;
}

/// Recognition result for a possible upstream archive.
class RecognitionDto {
  final bool isUpstream;
  final bool hasConfig;
  final bool hasDb;
  final String layout;
  final List<String> entries;
  final ErrorDto? error;

  const RecognitionDto({
    required this.isUpstream,
    required this.hasConfig,
    required this.hasDb,
    required this.layout,
    required this.entries,
    this.error,
  });

  @override
  int get hashCode =>
      isUpstream.hashCode ^
      hasConfig.hashCode ^
      hasDb.hashCode ^
      layout.hashCode ^
      entries.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecognitionDto &&
          runtimeType == other.runtimeType &&
          isUpstream == other.isUpstream &&
          hasConfig == other.hasConfig &&
          hasDb == other.hasDb &&
          layout == other.layout &&
          entries == other.entries &&
          error == other.error;
}

/// Startup recovery summary.
class RecoveryDto {
  final bool recoveryNeeded;
  final String? stage;
  final int restored;
  final int pending;

  const RecoveryDto({
    required this.recoveryNeeded,
    this.stage,
    required this.restored,
    required this.pending,
  });

  @override
  int get hashCode =>
      recoveryNeeded.hashCode ^
      stage.hashCode ^
      restored.hashCode ^
      pending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryDto &&
          runtimeType == other.runtimeType &&
          recoveryNeeded == other.recoveryNeeded &&
          stage == other.stage &&
          restored == other.restored &&
          pending == other.pending;
}

/// One failed resource download (R4-34).
class ResourceFailureDto {
  final String url;
  final String code;
  final String detail;

  const ResourceFailureDto({
    required this.url,
    required this.code,
    required this.detail,
  });

  @override
  int get hashCode => url.hashCode ^ code.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceFailureDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          code == other.code &&
          detail == other.detail;
}

/// Structured outcome of a Geo/SRS resource pass (R4-34).
class ResourceUpdateReportDto {
  final bool ok;
  final bool due;
  final int attempted;
  final List<String> downloaded;
  final List<ResourceFailureDto> failed;
  final ErrorDto? error;

  const ResourceUpdateReportDto({
    required this.ok,
    required this.due,
    required this.attempted,
    required this.downloaded,
    required this.failed,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      due.hashCode ^
      attempted.hashCode ^
      downloaded.hashCode ^
      failed.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceUpdateReportDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          due == other.due &&
          attempted == other.attempted &&
          downloaded == other.downloaded &&
          failed == other.failed &&
          error == other.error;
}

/// Result of restoring a bundle.
class RestoreResultDto {
  final bool ok;
  final bool restored;
  final String? targetBackup;
  final String message;
  final ErrorDto? error;

  const RestoreResultDto({
    required this.ok,
    required this.restored,
    this.targetBackup,
    required this.message,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      restored.hashCode ^
      targetBackup.hashCode ^
      message.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          restored == other.restored &&
          targetBackup == other.targetBackup &&
          message == other.message &&
          error == other.error;
}

/// Live TUN lease facts (adapter, interface, route count, dry-run flag).
class RuntimeTunDto {
  final String adapterName;
  final int interfaceIndex;
  final int routeCount;
  final bool dryRun;

  const RuntimeTunDto({
    required this.adapterName,
    required this.interfaceIndex,
    required this.routeCount,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      adapterName.hashCode ^
      interfaceIndex.hashCode ^
      routeCount.hashCode ^
      dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeTunDto &&
          runtimeType == other.runtimeType &&
          adapterName == other.adapterName &&
          interfaceIndex == other.interfaceIndex &&
          routeCount == other.routeCount &&
          dryRun == other.dryRun;
}

/// Result of `save_profile`: either the saved profile or a field error.
class SaveProfileResult {
  final bool ok;
  final ProfileDto? profile;
  final BigInt? newRevision;
  final ErrorDto? error;

  const SaveProfileResult({
    required this.ok,
    this.profile,
    this.newRevision,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ profile.hashCode ^ newRevision.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveProfileResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          profile == other.profile &&
          newRevision == other.newRevision &&
          error == other.error;
}

/// TLS/Reality fields carried directly on `ProfileItem`.
class SecurityDto {
  final String? streamSecurity;
  final String? allowInsecure;
  final String? sni;
  final String? alpn;
  final String? fingerprint;
  final String? publicKey;
  final String? shortId;
  final String? spiderX;
  final String? mldsa65Verify;
  final String? cert;
  final String? certSha;
  final String? echConfigList;
  final String? verifyPeerCertByName;

  const SecurityDto({
    this.streamSecurity,
    this.allowInsecure,
    this.sni,
    this.alpn,
    this.fingerprint,
    this.publicKey,
    this.shortId,
    this.spiderX,
    this.mldsa65Verify,
    this.cert,
    this.certSha,
    this.echConfigList,
    this.verifyPeerCertByName,
  });

  static Future<SecurityDto> default_() =>
      RustLib.instance.api.crateApiContractSecurityDtoDefault();

  @override
  int get hashCode =>
      streamSecurity.hashCode ^
      allowInsecure.hashCode ^
      sni.hashCode ^
      alpn.hashCode ^
      fingerprint.hashCode ^
      publicKey.hashCode ^
      shortId.hashCode ^
      spiderX.hashCode ^
      mldsa65Verify.hashCode ^
      cert.hashCode ^
      certSha.hashCode ^
      echConfigList.hashCode ^
      verifyPeerCertByName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityDto &&
          runtimeType == other.runtimeType &&
          streamSecurity == other.streamSecurity &&
          allowInsecure == other.allowInsecure &&
          sni == other.sni &&
          alpn == other.alpn &&
          fingerprint == other.fingerprint &&
          publicKey == other.publicKey &&
          shortId == other.shortId &&
          spiderX == other.spiderX &&
          mldsa65Verify == other.mldsa65Verify &&
          cert == other.cert &&
          certSha == other.certSha &&
          echConfigList == other.echConfigList &&
          verifyPeerCertByName == other.verifyPeerCertByName;
}

/// Result of exporting profiles as share/base64/inner text.
class ShareExportResult {
  final bool ok;
  final String text;
  final int count;
  final ErrorDto? error;

  const ShareExportResult({
    required this.ok,
    required this.text,
    required this.count,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ text.hashCode ^ count.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareExportResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          text == other.text &&
          count == other.count &&
          error == other.error;
}

/// Result of a simple boolean mutation.
class SimpleResult {
  final bool ok;
  final ErrorDto? error;

  const SimpleResult({required this.ok, this.error});

  @override
  int get hashCode => ok.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          error == other.error;
}

/// The `get_snapshot` result.
///
/// Runtime facts (`runtime_pid`, `runtime_ports`, ...) are the live values
/// reported by net-host; they are `None`/empty when the runtime is not running
/// and are never synthesized from UI state.
class SnapshotDto {
  final BigInt desiredRevision;
  final BigInt appliedRevision;
  final RevisionState revisionState;
  final RuntimeState runtimeState;
  final bool hostAlive;
  final int? runtimePid;
  final PlatformInt64? runtimeCreatedAtMs;
  final Uint16List runtimePorts;
  final String? runtimeSessionId;
  final String? runtimeConfigSha256;
  final String? runtimeOperationId;
  final ErrorDto? runtimeError;

  /// Actual TUN lease facts reported by net-host; `None` when the running
  /// plan has no TUN lease (TUN-A03: the UI must read the real state, never
  /// the desired switch).
  final RuntimeTunDto? runtimeTun;
  final List<JobDto> activeJobs;
  final List<CapabilityDto> capabilities;
  final RecoveryDto recovery;
  final BigInt profileCount;

  const SnapshotDto({
    required this.desiredRevision,
    required this.appliedRevision,
    required this.revisionState,
    required this.runtimeState,
    required this.hostAlive,
    this.runtimePid,
    this.runtimeCreatedAtMs,
    required this.runtimePorts,
    this.runtimeSessionId,
    this.runtimeConfigSha256,
    this.runtimeOperationId,
    this.runtimeError,
    this.runtimeTun,
    required this.activeJobs,
    required this.capabilities,
    required this.recovery,
    required this.profileCount,
  });

  @override
  int get hashCode =>
      desiredRevision.hashCode ^
      appliedRevision.hashCode ^
      revisionState.hashCode ^
      runtimeState.hashCode ^
      hostAlive.hashCode ^
      runtimePid.hashCode ^
      runtimeCreatedAtMs.hashCode ^
      runtimePorts.hashCode ^
      runtimeSessionId.hashCode ^
      runtimeConfigSha256.hashCode ^
      runtimeOperationId.hashCode ^
      runtimeError.hashCode ^
      runtimeTun.hashCode ^
      activeJobs.hashCode ^
      capabilities.hashCode ^
      recovery.hashCode ^
      profileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotDto &&
          runtimeType == other.runtimeType &&
          desiredRevision == other.desiredRevision &&
          appliedRevision == other.appliedRevision &&
          revisionState == other.revisionState &&
          runtimeState == other.runtimeState &&
          hostAlive == other.hostAlive &&
          runtimePid == other.runtimePid &&
          runtimeCreatedAtMs == other.runtimeCreatedAtMs &&
          runtimePorts == other.runtimePorts &&
          runtimeSessionId == other.runtimeSessionId &&
          runtimeConfigSha256 == other.runtimeConfigSha256 &&
          runtimeOperationId == other.runtimeOperationId &&
          runtimeError == other.runtimeError &&
          runtimeTun == other.runtimeTun &&
          activeJobs == other.activeJobs &&
          capabilities == other.capabilities &&
          recovery == other.recovery &&
          profileCount == other.profileCount;
}

/// Result of `stop_runtime`.
class StopRuntimeResult {
  final bool ok;
  final ErrorDto? error;

  const StopRuntimeResult({required this.ok, this.error});

  @override
  int get hashCode => ok.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StopRuntimeResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          error == other.error;
}

/// The 17-field subscription model (`SubItem`).
class SubItemDto {
  final String id;
  final String remarks;
  final String url;
  final String moreUrl;
  final bool enabled;
  final String userAgent;
  final String? requestHeaders;
  final int sort;
  final String? filter;
  final int autoUpdateInterval;
  final PlatformInt64 updateTime;
  final String? convertTarget;
  final String? prevProfile;
  final String? nextProfile;
  final int? preSocksPort;
  final String? memo;
  final int? customCoreType;

  const SubItemDto({
    required this.id,
    required this.remarks,
    required this.url,
    required this.moreUrl,
    required this.enabled,
    required this.userAgent,
    this.requestHeaders,
    required this.sort,
    this.filter,
    required this.autoUpdateInterval,
    required this.updateTime,
    this.convertTarget,
    this.prevProfile,
    this.nextProfile,
    this.preSocksPort,
    this.memo,
    this.customCoreType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      remarks.hashCode ^
      url.hashCode ^
      moreUrl.hashCode ^
      enabled.hashCode ^
      userAgent.hashCode ^
      requestHeaders.hashCode ^
      sort.hashCode ^
      filter.hashCode ^
      autoUpdateInterval.hashCode ^
      updateTime.hashCode ^
      convertTarget.hashCode ^
      prevProfile.hashCode ^
      nextProfile.hashCode ^
      preSocksPort.hashCode ^
      memo.hashCode ^
      customCoreType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          remarks == other.remarks &&
          url == other.url &&
          moreUrl == other.moreUrl &&
          enabled == other.enabled &&
          userAgent == other.userAgent &&
          requestHeaders == other.requestHeaders &&
          sort == other.sort &&
          filter == other.filter &&
          autoUpdateInterval == other.autoUpdateInterval &&
          updateTime == other.updateTime &&
          convertTarget == other.convertTarget &&
          prevProfile == other.prevProfile &&
          nextProfile == other.nextProfile &&
          preSocksPort == other.preSocksPort &&
          memo == other.memo &&
          customCoreType == other.customCoreType;
}

/// Result of a subscription mutation.
class SubItemDtoResult {
  final bool ok;
  final SubItemDto? item;
  final ErrorDto? error;

  const SubItemDtoResult({required this.ok, this.item, this.error});

  @override
  int get hashCode => ok.hashCode ^ item.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubItemDtoResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          item == other.item &&
          error == other.error;
}

/// One entry of a subscription update report.
class SubUpdateEntryDto {
  final String subId;
  final String remarks;

  /// `updated` / `preserved_empty` / `preserved_error` / `skipped` /
  /// `cancelled` / `failed`.
  final String status;
  final int? added;
  final int? existing;
  final String? code;
  final String? message;

  const SubUpdateEntryDto({
    required this.subId,
    required this.remarks,
    required this.status,
    this.added,
    this.existing,
    this.code,
    this.message,
  });

  @override
  int get hashCode =>
      subId.hashCode ^
      remarks.hashCode ^
      status.hashCode ^
      added.hashCode ^
      existing.hashCode ^
      code.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubUpdateEntryDto &&
          runtimeType == other.runtimeType &&
          subId == other.subId &&
          remarks == other.remarks &&
          status == other.status &&
          added == other.added &&
          existing == other.existing &&
          code == other.code &&
          message == other.message;
}

/// Result of `update_subscriptions`.
class SubUpdateResult {
  final bool ok;
  final int success;
  final bool cancelled;
  final List<SubUpdateEntryDto> entries;
  final String? jobId;
  final ErrorDto? error;

  const SubUpdateResult({
    required this.ok,
    required this.success,
    required this.cancelled,
    required this.entries,
    this.jobId,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      success.hashCode ^
      cancelled.hashCode ^
      entries.hashCode ^
      jobId.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubUpdateResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          success == other.success &&
          cancelled == other.cancelled &&
          entries == other.entries &&
          jobId == other.jobId &&
          error == other.error;
}

/// Result of `list_sub_items`.
class SubsPageDto {
  final List<SubItemDto> items;
  final ErrorDto? error;

  const SubsPageDto({required this.items, this.error});

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubsPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}

/// `TransportExtraItem` (11 properties) exposed to the editor.
class TransportExtraDto {
  final String? rawHeaderType;
  final String? host;
  final String? path;
  final String? xhttpMode;
  final String? xhttpExtra;
  final String? grpcAuthority;
  final String? grpcServiceName;
  final String? grpcMode;
  final String? kcpHeaderType;
  final String? kcpSeed;
  final int? kcpMtu;

  /// Opaque unknown-extension JSON, preserved for round-trip.
  final String extraJson;

  const TransportExtraDto({
    this.rawHeaderType,
    this.host,
    this.path,
    this.xhttpMode,
    this.xhttpExtra,
    this.grpcAuthority,
    this.grpcServiceName,
    this.grpcMode,
    this.kcpHeaderType,
    this.kcpSeed,
    this.kcpMtu,
    required this.extraJson,
  });

  static Future<TransportExtraDto> default_() =>
      RustLib.instance.api.crateApiContractTransportExtraDtoDefault();

  @override
  int get hashCode =>
      rawHeaderType.hashCode ^
      host.hashCode ^
      path.hashCode ^
      xhttpMode.hashCode ^
      xhttpExtra.hashCode ^
      grpcAuthority.hashCode ^
      grpcServiceName.hashCode ^
      grpcMode.hashCode ^
      kcpHeaderType.hashCode ^
      kcpSeed.hashCode ^
      kcpMtu.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportExtraDto &&
          runtimeType == other.runtimeType &&
          rawHeaderType == other.rawHeaderType &&
          host == other.host &&
          path == other.path &&
          xhttpMode == other.xhttpMode &&
          xhttpExtra == other.xhttpExtra &&
          grpcAuthority == other.grpcAuthority &&
          grpcServiceName == other.grpcServiceName &&
          grpcMode == other.grpcMode &&
          kcpHeaderType == other.kcpHeaderType &&
          kcpSeed == other.kcpSeed &&
          kcpMtu == other.kcpMtu &&
          extraJson == other.extraJson;
}

/// Result of checking every selected target.
class UpdateReportDto {
  final bool ok;
  final List<CoreUpdateDto> checks;
  final ErrorDto? error;

  const UpdateReportDto({required this.ok, required this.checks, this.error});

  @override
  int get hashCode => ok.hashCode ^ checks.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateReportDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          checks == other.checks &&
          error == other.error;
}

/// One update target's static description.
class UpdateTargetDto {
  final String core;
  final String repo;
  final bool supported;
  final bool prereleaseCapable;
  final String? maxVersion;
  final String? note;

  const UpdateTargetDto({
    required this.core,
    required this.repo,
    required this.supported,
    required this.prereleaseCapable,
    this.maxVersion,
    this.note,
  });

  @override
  int get hashCode =>
      core.hashCode ^
      repo.hashCode ^
      supported.hashCode ^
      prereleaseCapable.hashCode ^
      maxVersion.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateTargetDto &&
          runtimeType == other.runtimeType &&
          core == other.core &&
          repo == other.repo &&
          supported == other.supported &&
          prereleaseCapable == other.prereleaseCapable &&
          maxVersion == other.maxVersion &&
          note == other.note;
}

/// Result of parsing a single share URI.
class UriParseResult {
  final bool ok;
  final ProfileDto? profile;
  final ErrorDto? error;

  const UriParseResult({required this.ok, this.profile, this.error});

  @override
  int get hashCode => ok.hashCode ^ profile.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UriParseResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          profile == other.profile &&
          error == other.error;
}

/// Integrity verification result.
class VerificationDto {
  final bool ok;
  final List<String> missing;
  final List<String> mismatched;

  const VerificationDto({
    required this.ok,
    required this.missing,
    required this.mismatched,
  });

  @override
  int get hashCode => ok.hashCode ^ missing.hashCode ^ mismatched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerificationDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          missing == other.missing &&
          mismatched == other.mismatched;
}

/// Connection-check result.
class WebDavCheckDto {
  final bool ok;
  final bool createdDir;
  final int status;
  final String message;
  final ErrorDto? error;

  const WebDavCheckDto({
    required this.ok,
    required this.createdDir,
    required this.status,
    required this.message,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      createdDir.hashCode ^
      status.hashCode ^
      message.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavCheckDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          createdDir == other.createdDir &&
          status == other.status &&
          message == other.message &&
          error == other.error;
}

/// WebDAV endpoint configuration (mirrors `WebDavItem`; password is a secret).
class WebDavConfigDto {
  final String url;
  final String userName;
  final String password;
  final String dirName;

  const WebDavConfigDto({
    required this.url,
    required this.userName,
    required this.password,
    required this.dirName,
  });

  @override
  int get hashCode =>
      url.hashCode ^ userName.hashCode ^ password.hashCode ^ dirName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavConfigDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          userName == other.userName &&
          password == other.password &&
          dirName == other.dirName;
}

/// Result of loading/saving the WebDAV configuration.
class WebDavConfigResultDto {
  final bool ok;
  final WebDavConfigDto? config;
  final BigInt revision;
  final ErrorDto? error;

  const WebDavConfigResultDto({
    required this.ok,
    this.config,
    required this.revision,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ config.hashCode ^ revision.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavConfigResultDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          config == other.config &&
          revision == other.revision &&
          error == other.error;
}

/// One remote WebDAV entry.
class WebDavEntryDto {
  final String href;
  final bool isDir;
  final BigInt size;
  final String modified;

  const WebDavEntryDto({
    required this.href,
    required this.isDir,
    required this.size,
    required this.modified,
  });

  @override
  int get hashCode =>
      href.hashCode ^ isDir.hashCode ^ size.hashCode ^ modified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavEntryDto &&
          runtimeType == other.runtimeType &&
          href == other.href &&
          isDir == other.isDir &&
          size == other.size &&
          modified == other.modified;
}

/// Remote listing result.
class WebDavListDto {
  final bool ok;
  final List<WebDavEntryDto> items;
  final ErrorDto? error;

  const WebDavListDto({required this.ok, required this.items, this.error});

  @override
  int get hashCode => ok.hashCode ^ items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavListDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          items == other.items &&
          error == other.error;
}

/// Result of a remote backup upload / download.
class WebDavOpDto {
  final bool ok;
  final BigInt bytes;
  final String message;
  final ErrorDto? error;

  const WebDavOpDto({
    required this.ok,
    required this.bytes,
    required this.message,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ bytes.hashCode ^ message.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavOpDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          bytes == other.bytes &&
          message == other.message &&
          error == other.error;
}
