// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast`, `dto_to_profile`, `emit_control`, `engine`, `envelope_to_dto`, `epoch_counter`, `error_dto`, `next_event`, `profile_to_dto`, `seq_counter`, `stub_plan`, `subscribers`

/// `get_snapshot` — settings version, runtime snapshot, active jobs,
/// capabilities and startup-recovery status.
SnapshotDto getSnapshot() => RustLib.instance.api.crateApiEngineGetSnapshot();

/// `query_profiles` — filter/sort/cursor/page_size with stable ids.
ProfilePageDto queryProfiles({
  required ProfileFilterDto filter,
  required ProfileSortDto sort,
  required BigInt cursor,
  required int pageSize,
}) => RustLib.instance.api.crateApiEngineQueryProfiles(
  filter: filter,
  sort: sort,
  cursor: cursor,
  pageSize: pageSize,
);

/// `save_profile` — draft + expected revision; returns the saved entity and
/// new revision or a field error.
SaveProfileResult saveProfile({
  required ProfileDto draft,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiEngineSaveProfile(
  draft: draft,
  expectedRevision: expectedRevision,
);

/// `apply_runtime` — target id + expected revision; returns an operation id.
/// The result flows on the event stream.
ApplyRuntimeResult applyRuntime({
  required String targetId,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiEngineApplyRuntime(
  targetId: targetId,
  expectedRevision: expectedRevision,
);

/// `cancel_job` — idempotent cancellation.
CancelResult cancelJob({required String jobId}) =>
    RustLib.instance.api.crateApiEngineCancelJob(jobId: jobId);

/// `subscribe_events` — FRB stream of events. On subscribe the current
/// epoch/seq is sent first so a reconnecting UI can detect gaps.
Stream<EventEnvelopeDto> subscribeEvents() =>
    RustLib.instance.api.crateApiEngineSubscribeEvents();

/// Test helper: emit a synthetic control event to the stream.
void emitTestEvent({required String kind, required String payloadJson}) =>
    RustLib.instance.api.crateApiEngineEmitTestEvent(
      kind: kind,
      payloadJson: payloadJson,
    );

/// Number of active subscribers (diagnostics / tests).
int subscriberCount() => RustLib.instance.api.crateApiEngineSubscriberCount();

/// Mark a job as running its compensating path (test helper for cancel flow).
void markJobPastSafePoint({required String jobId}) =>
    RustLib.instance.api.crateApiEngineMarkJobPastSafePoint(jobId: jobId);

/// Seed the in-memory engine with `count` synthetic profiles (bootstrap +
/// tests). Addresses are RFC5737 / example domains only.
void seedSyntheticProfiles({required int count}) =>
    RustLib.instance.api.crateApiEngineSeedSyntheticProfiles(count: count);

/// Number of profiles currently held by the in-memory engine.
BigInt profileCount() => RustLib.instance.api.crateApiEngineProfileCount();
