// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_template`, `template_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

/// `list_templates` — the stored rows (builtins seeded on first open).
TemplatesPageDto listTemplates() =>
    RustLib.instance.api.crateApiGroupsListTemplates();

/// `get_template` — the row for one core, if any.
FullConfigTemplateDto? getTemplate({required CoreType core}) =>
    RustLib.instance.api.crateApiGroupsGetTemplate(core: core);

/// `save_template` — validate (JSON objects), upsert by core, persist.
TemplateDtoResult saveTemplate({required FullConfigTemplateDto item}) =>
    RustLib.instance.api.crateApiGroupsSaveTemplate(item: item);

/// `delete_template` — remove one row by id.
SimpleResult deleteTemplate({required String id}) =>
    RustLib.instance.api.crateApiGroupsDeleteTemplate(id: id);

/// `group_children` — ordered child profiles of a group/chain node
/// (subscription matches first, then the explicit `ChildItems` order).
ProfilePageDto groupChildren({required String indexId}) =>
    RustLib.instance.api.crateApiGroupsGroupChildren(indexId: indexId);

/// `gen_group_all` — create the "all nodes of this subscription" policy group.
SaveProfileResult genGroupAll({required String subId}) =>
    RustLib.instance.api.crateApiGroupsGenGroupAll(subId: subId);

/// `gen_group_region` — create one policy group per region with matches.
GroupGenResult genGroupRegion({required String subId}) =>
    RustLib.instance.api.crateApiGroupsGenGroupRegion(subId: subId);

/// The 8-field `FullConfigTemplateItem` row.
class FullConfigTemplateDto {
  final String id;
  final String remarks;
  final bool enabled;
  final CoreType coreType;
  final String? config;
  final String? tunConfig;
  final bool? addProxyOnly;
  final String? proxyDetour;

  const FullConfigTemplateDto({
    required this.id,
    required this.remarks,
    required this.enabled,
    required this.coreType,
    this.config,
    this.tunConfig,
    this.addProxyOnly,
    this.proxyDetour,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      remarks.hashCode ^
      enabled.hashCode ^
      coreType.hashCode ^
      config.hashCode ^
      tunConfig.hashCode ^
      addProxyOnly.hashCode ^
      proxyDetour.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FullConfigTemplateDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          remarks == other.remarks &&
          enabled == other.enabled &&
          coreType == other.coreType &&
          config == other.config &&
          tunConfig == other.tunConfig &&
          addProxyOnly == other.addProxyOnly &&
          proxyDetour == other.proxyDetour;
}

/// Result of `gen_group_region`: one saved profile per matching region.
class GroupGenResult {
  final bool ok;
  final List<ProfileDto> profiles;
  final ErrorDto? error;

  const GroupGenResult({required this.ok, required this.profiles, this.error});

  @override
  int get hashCode => ok.hashCode ^ profiles.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupGenResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          profiles == other.profiles &&
          error == other.error;
}

/// Result of `save_template`.
class TemplateDtoResult {
  final bool ok;
  final FullConfigTemplateDto? item;
  final ErrorDto? error;

  const TemplateDtoResult({required this.ok, this.item, this.error});

  @override
  int get hashCode => ok.hashCode ^ item.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplateDtoResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          item == other.item &&
          error == other.error;
}

/// Result of `list_templates`.
class TemplatesPageDto {
  final List<FullConfigTemplateDto> items;
  final ErrorDto? error;

  const TemplatesPageDto({required this.items, this.error});

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplatesPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}
