// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum ConfigType {
  vmess,
  vless,
  trojan,
  shadowsocks,
  socks,
  http,
  hysteria2,
  tuic,
}

enum CoreType { xray, singBox, mihomo, custom }

class ProfileSummary {
  final String id;
  final ConfigType configType;
  final String remarks;
  final String address;
  final int port;
  final String network;
  final String streamSecurity;
  final String subRemarks;
  final int delay;
  final String speed;
  final BigInt todayUp;
  final String ipInfo;
  final BigInt todayDown;
  final BigInt totalUp;
  final BigInt totalDown;
  final CoreType coreType;

  const ProfileSummary({
    required this.id,
    required this.configType,
    required this.remarks,
    required this.address,
    required this.port,
    required this.network,
    required this.streamSecurity,
    required this.subRemarks,
    required this.delay,
    required this.speed,
    required this.todayUp,
    required this.ipInfo,
    required this.todayDown,
    required this.totalUp,
    required this.totalDown,
    required this.coreType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      configType.hashCode ^
      remarks.hashCode ^
      address.hashCode ^
      port.hashCode ^
      network.hashCode ^
      streamSecurity.hashCode ^
      subRemarks.hashCode ^
      delay.hashCode ^
      speed.hashCode ^
      todayUp.hashCode ^
      ipInfo.hashCode ^
      todayDown.hashCode ^
      totalUp.hashCode ^
      totalDown.hashCode ^
      coreType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          configType == other.configType &&
          remarks == other.remarks &&
          address == other.address &&
          port == other.port &&
          network == other.network &&
          streamSecurity == other.streamSecurity &&
          subRemarks == other.subRemarks &&
          delay == other.delay &&
          speed == other.speed &&
          todayUp == other.todayUp &&
          ipInfo == other.ipInfo &&
          todayDown == other.todayDown &&
          totalUp == other.totalUp &&
          totalDown == other.totalDown &&
          coreType == other.coreType;
}
