// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_clash`, `build_source`, `clash_config`, `clash_error`, `domain_error`, `hub`, `ingest_runtime_event`, `join_host_port`, `level_from_value`, `level_value`, `lines_from_envelope`, `new`, `next_seq`, `node_dtos`, `not_supported`, `now_unix`, `poll_loop_async`, `poll_loop`, `rebind_store`, `sync_from_engine_session`, `traffic_dto`, `with_hub`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClashConfig`, `MonitorHub`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `ingest_log_text_for_test`, `ingest_stats_for_test`, `inject_log_batch_for_test`, `log_subscriber_count_for_test`, `reset_monitor_for_test`, `set_clash_base_for_test`, `take_seq`, `traffic_subscriber_count_for_test`

/// Configure the monitor with the running session's facts.
///
/// `core` is the domain `CoreType` numeric value; `state_port` is Xray's
/// `/debug/vars` port and `state_port2` the Clash/`traffic` port. Nothing is
/// contacted here.
SimpleResult monitorConfigure({
  required int core,
  required int statePort,
  required int statePort2,
  String? secret,
  required bool enableStatistics,
  required bool displayRealTimeSpeed,
  required int refreshIntervalMs,
}) => RustLib.instance.api.crateApiMonitorMonitorConfigure(
  core: core,
  statePort: statePort,
  statePort2: statePort2,
  secret: secret,
  enableStatistics: enableStatistics,
  displayRealTimeSpeed: displayRealTimeSpeed,
  refreshIntervalMs: refreshIntervalMs,
);

/// Set the active node id that receives the proxy byte attribution.
SimpleResult monitorSetActiveNode({String? indexId}) =>
    RustLib.instance.api.crateApiMonitorMonitorSetActiveNode(indexId: indexId);

/// Whether statistics collection is active.
bool monitorEnabled() => RustLib.instance.api.crateApiMonitorMonitorEnabled();

/// Current statistics snapshot.
StatsSnapshotDto statsSnapshot() =>
    RustLib.instance.api.crateApiMonitorStatsSnapshot();

/// `ClearAllServerStatistics`: clear memory + persisted rows.
SimpleResult clearStats() => RustLib.instance.api.crateApiMonitorClearStats();

/// Register a traffic stream. Sends the current epoch/seq header first.
Stream<TrafficBatchDto> subscribeTraffic() =>
    RustLib.instance.api.crateApiMonitorSubscribeTraffic();

/// Number of log lines currently buffered.
int logTotal() => RustLib.instance.api.crateApiMonitorLogTotal();

/// Read a page of buffered log lines.
LogPageDto getLogs({required int offset, required int limit}) =>
    RustLib.instance.api.crateApiMonitorGetLogs(offset: offset, limit: limit);

/// Clear the visible logs (control queue is preserved).
SimpleResult clearLogs() => RustLib.instance.api.crateApiMonitorClearLogs();

/// Set the level/keyword filter applied to newly collected lines.
SimpleResult setLogFilter({
  required int minLevel,
  required List<String> include,
  required List<String> exclude,
}) => RustLib.instance.api.crateApiMonitorSetLogFilter(
  minLevel: minLevel,
  include: include,
  exclude: exclude,
);

/// Pause collection and/or scroll independently.
SimpleResult setLogPause({
  required bool collectingPaused,
  required bool scrollPaused,
}) => RustLib.instance.api.crateApiMonitorSetLogPause(
  collectingPaused: collectingPaused,
  scrollPaused: scrollPaused,
);

/// Register a log stream. The current buffer is replayed first.
Stream<LogBatchDto> subscribeLogs() =>
    RustLib.instance.api.crateApiMonitorSubscribeLogs();

/// Toggle a page's visibility. Only visible pages are subscribed (plan §14).
PageVisibilityDto setPageVisible({
  required String page,
  required bool visible,
}) => RustLib.instance.api.crateApiMonitorSetPageVisible(
  page: page,
  visible: visible,
);

/// Set the delay-probe URL from settings (`SpeedPingTestUrl`). Empty clears it
/// back to the upstream default.
SimpleResult monitorSetDelayUrl({String? url}) =>
    RustLib.instance.api.crateApiMonitorMonitorSetDelayUrl(url: url);

/// Whether the configured core exposes the Clash API.
bool clashSupported() => RustLib.instance.api.crateApiMonitorClashSupported();

/// Fetch proxies/groups from the Clash controller.
Future<ClashProxiesDto> clashProxies() =>
    RustLib.instance.api.crateApiMonitorClashProxies();

/// Read the live `/configs` mode and the selectable mode list.
Future<ClashModeDto> clashModeState() =>
    RustLib.instance.api.crateApiMonitorClashModeState();

/// Switch the Clash routing mode (`PATCH /configs`).
Future<MonitorActionResult> updateClashMode({required String mode}) =>
    RustLib.instance.api.crateApiMonitorUpdateClashMode(mode: mode);

/// Select `name` inside proxy group `group`.
Future<MonitorActionResult> selectClashProxy({
  required String group,
  required String name,
}) => RustLib.instance.api.crateApiMonitorSelectClashProxy(
  group: group,
  name: name,
);

/// Single-node delay probe (`-1` means timeout/unreachable).
Future<DelayResultDto> clashProxyDelay({required String name}) =>
    RustLib.instance.api.crateApiMonitorClashProxyDelay(name: name);

/// Probe every child of a proxy group.
Future<GroupDelayDto> clashGroupDelay({required String group}) =>
    RustLib.instance.api.crateApiMonitorClashGroupDelay(group: group);

/// Fetch the active connection table.
Future<ClashConnectionsDto> clashConnections() =>
    RustLib.instance.api.crateApiMonitorClashConnections();

/// Close one connection by id.
Future<MonitorActionResult> closeClashConnection({required String id}) =>
    RustLib.instance.api.crateApiMonitorCloseClashConnection(id: id);

/// Close every connection.
Future<MonitorActionResult> closeAllClashConnections() =>
    RustLib.instance.api.crateApiMonitorCloseAllClashConnections();

/// Start the 1 Hz statistics poller once. No-op for unsupported cores.
///
/// Each call first (re)synchronizes the hub with the applied session so a
/// normal GUI apply enables real collection and a stop/switch clears the old
/// session's ports.
void monitorStartPolling() =>
    RustLib.instance.api.crateApiMonitorMonitorStartPolling();

/// One Clash connection row.
class ClashConnectionDto {
  final String id;
  final String? host;
  final String? network;
  final String? connectionType;
  final List<String> chains;
  final String? rule;
  final String? processPath;
  final String? source;
  final String? destination;
  final BigInt upload;
  final BigInt download;
  final String? start;

  const ClashConnectionDto({
    required this.id,
    this.host,
    this.network,
    this.connectionType,
    required this.chains,
    this.rule,
    this.processPath,
    this.source,
    this.destination,
    required this.upload,
    required this.download,
    this.start,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      host.hashCode ^
      network.hashCode ^
      connectionType.hashCode ^
      chains.hashCode ^
      rule.hashCode ^
      processPath.hashCode ^
      source.hashCode ^
      destination.hashCode ^
      upload.hashCode ^
      download.hashCode ^
      start.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashConnectionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          host == other.host &&
          network == other.network &&
          connectionType == other.connectionType &&
          chains == other.chains &&
          rule == other.rule &&
          processPath == other.processPath &&
          source == other.source &&
          destination == other.destination &&
          upload == other.upload &&
          download == other.download &&
          start == other.start;
}

/// `clash_connections` result.
class ClashConnectionsDto {
  final bool ok;
  final bool supported;
  final String? message;
  final BigInt uploadTotal;
  final BigInt downloadTotal;
  final List<ClashConnectionDto> items;
  final ErrorDto? error;

  const ClashConnectionsDto({
    required this.ok,
    required this.supported,
    this.message,
    required this.uploadTotal,
    required this.downloadTotal,
    required this.items,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      supported.hashCode ^
      message.hashCode ^
      uploadTotal.hashCode ^
      downloadTotal.hashCode ^
      items.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashConnectionsDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          supported == other.supported &&
          message == other.message &&
          uploadTotal == other.uploadTotal &&
          downloadTotal == other.downloadTotal &&
          items == other.items &&
          error == other.error;
}

/// `/configs` mode state: the live mode plus the selectable mode list.
class ClashModeDto {
  final bool ok;
  final bool supported;
  final String? message;

  /// Currently applied mode (`Rule`/`Global`/`Direct`, core-cased).
  final String? mode;

  /// Modes advertised by the core (`mode-list`/`modes`).
  final List<String> modes;
  final ErrorDto? error;

  const ClashModeDto({
    required this.ok,
    required this.supported,
    this.message,
    this.mode,
    required this.modes,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      supported.hashCode ^
      message.hashCode ^
      mode.hashCode ^
      modes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashModeDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          supported == other.supported &&
          message == other.message &&
          mode == other.mode &&
          modes == other.modes &&
          error == other.error;
}

/// `clash_proxies` result.
class ClashProxiesDto {
  final bool ok;
  final bool supported;
  final String? message;
  final BigInt epoch;
  final BigInt seq;
  final List<ClashProxyDto> items;
  final ErrorDto? error;

  const ClashProxiesDto({
    required this.ok,
    required this.supported,
    this.message,
    required this.epoch,
    required this.seq,
    required this.items,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      supported.hashCode ^
      message.hashCode ^
      epoch.hashCode ^
      seq.hashCode ^
      items.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashProxiesDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          supported == other.supported &&
          message == other.message &&
          epoch == other.epoch &&
          seq == other.seq &&
          items == other.items &&
          error == other.error;
}

/// One Clash proxy or group.
class ClashProxyDto {
  final String name;
  final String proxyType;
  final bool isGroup;
  final String? now;
  final List<String> all;
  final int delay;
  final String? provider;

  const ClashProxyDto({
    required this.name,
    required this.proxyType,
    required this.isGroup,
    this.now,
    required this.all,
    required this.delay,
    this.provider,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      proxyType.hashCode ^
      isGroup.hashCode ^
      now.hashCode ^
      all.hashCode ^
      delay.hashCode ^
      provider.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashProxyDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          isGroup == other.isGroup &&
          now == other.now &&
          all == other.all &&
          delay == other.delay &&
          provider == other.provider;
}

/// One delay probe.
class DelayResultDto {
  final String name;
  final int delay;

  const DelayResultDto({required this.name, required this.delay});

  @override
  int get hashCode => name.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DelayResultDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay;
}

/// `clash_group_delay` result.
class GroupDelayDto {
  final bool ok;
  final bool supported;
  final String group;
  final List<DelayResultDto> items;
  final ErrorDto? error;

  const GroupDelayDto({
    required this.ok,
    required this.supported,
    required this.group,
    required this.items,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      supported.hashCode ^
      group.hashCode ^
      items.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDelayDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          supported == other.supported &&
          group == other.group &&
          items == other.items &&
          error == other.error;
}

/// Live log batch with the overflow counters.
class LogBatchDto {
  final BigInt epoch;
  final BigInt seq;
  final List<LogLineDto> lines;
  final BigInt droppedLines;
  final BigInt droppedBytes;
  final BigInt truncatedLines;
  final bool collectingPaused;
  final bool scrollPaused;

  const LogBatchDto({
    required this.epoch,
    required this.seq,
    required this.lines,
    required this.droppedLines,
    required this.droppedBytes,
    required this.truncatedLines,
    required this.collectingPaused,
    required this.scrollPaused,
  });

  @override
  int get hashCode =>
      epoch.hashCode ^
      seq.hashCode ^
      lines.hashCode ^
      droppedLines.hashCode ^
      droppedBytes.hashCode ^
      truncatedLines.hashCode ^
      collectingPaused.hashCode ^
      scrollPaused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogBatchDto &&
          runtimeType == other.runtimeType &&
          epoch == other.epoch &&
          seq == other.seq &&
          lines == other.lines &&
          droppedLines == other.droppedLines &&
          droppedBytes == other.droppedBytes &&
          truncatedLines == other.truncatedLines &&
          collectingPaused == other.collectingPaused &&
          scrollPaused == other.scrollPaused;
}

/// One log line as delivered to the UI.
class LogLineDto {
  final String text;

  /// 0 trace, 1 debug, 2 info, 3 warn, 4 error, 5 fatal, 6 unknown.
  final int level;
  final bool truncated;

  const LogLineDto({
    required this.text,
    required this.level,
    required this.truncated,
  });

  @override
  int get hashCode => text.hashCode ^ level.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogLineDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          level == other.level &&
          truncated == other.truncated;
}

/// Page of historical log lines (`get_logs`).
class LogPageDto {
  final bool ok;
  final List<LogLineDto> lines;
  final int total;
  final BigInt droppedLines;
  final BigInt droppedBytes;
  final BigInt truncatedLines;
  final bool collectingPaused;
  final bool scrollPaused;
  final ErrorDto? error;

  const LogPageDto({
    required this.ok,
    required this.lines,
    required this.total,
    required this.droppedLines,
    required this.droppedBytes,
    required this.truncatedLines,
    required this.collectingPaused,
    required this.scrollPaused,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      lines.hashCode ^
      total.hashCode ^
      droppedLines.hashCode ^
      droppedBytes.hashCode ^
      truncatedLines.hashCode ^
      collectingPaused.hashCode ^
      scrollPaused.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogPageDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          lines == other.lines &&
          total == other.total &&
          droppedLines == other.droppedLines &&
          droppedBytes == other.droppedBytes &&
          truncatedLines == other.truncatedLines &&
          collectingPaused == other.collectingPaused &&
          scrollPaused == other.scrollPaused &&
          error == other.error;
}

/// Generic result for select/close/mode actions.
class MonitorActionResult {
  final bool ok;
  final bool supported;
  final String? message;
  final ErrorDto? error;

  const MonitorActionResult({
    required this.ok,
    required this.supported,
    this.message,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ supported.hashCode ^ message.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorActionResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          supported == other.supported &&
          message == other.message &&
          error == other.error;
}

/// One node's `ServerStatItem` as delivered to the UI.
class NodeTrafficDto {
  final String indexId;
  final PlatformInt64 totalUp;
  final PlatformInt64 totalDown;
  final PlatformInt64 todayUp;
  final PlatformInt64 todayDown;
  final PlatformInt64 dateNow;

  const NodeTrafficDto({
    required this.indexId,
    required this.totalUp,
    required this.totalDown,
    required this.todayUp,
    required this.todayDown,
    required this.dateNow,
  });

  @override
  int get hashCode =>
      indexId.hashCode ^
      totalUp.hashCode ^
      totalDown.hashCode ^
      todayUp.hashCode ^
      todayDown.hashCode ^
      dateNow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeTrafficDto &&
          runtimeType == other.runtimeType &&
          indexId == other.indexId &&
          totalUp == other.totalUp &&
          totalDown == other.totalDown &&
          todayUp == other.todayUp &&
          todayDown == other.todayDown &&
          dateNow == other.dateNow;
}

/// Result of `set_page_visible`.
class PageVisibilityDto {
  final bool visible;
  final bool subscribed;
  final int refreshIntervalMs;

  const PageVisibilityDto({
    required this.visible,
    required this.subscribed,
    required this.refreshIntervalMs,
  });

  @override
  int get hashCode =>
      visible.hashCode ^ subscribed.hashCode ^ refreshIntervalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageVisibilityDto &&
          runtimeType == other.runtimeType &&
          visible == other.visible &&
          subscribed == other.subscribed &&
          refreshIntervalMs == other.refreshIntervalMs;
}

/// Point-in-time statistics snapshot.
class StatsSnapshotDto {
  final bool ok;
  final bool enabled;
  final bool displaySpeed;
  final BigInt generation;
  final BigInt proxyUp;
  final BigInt proxyDown;
  final BigInt directUp;
  final BigInt directDown;
  final List<NodeTrafficDto> nodes;
  final ErrorDto? error;

  const StatsSnapshotDto({
    required this.ok,
    required this.enabled,
    required this.displaySpeed,
    required this.generation,
    required this.proxyUp,
    required this.proxyDown,
    required this.directUp,
    required this.directDown,
    required this.nodes,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      enabled.hashCode ^
      displaySpeed.hashCode ^
      generation.hashCode ^
      proxyUp.hashCode ^
      proxyDown.hashCode ^
      directUp.hashCode ^
      directDown.hashCode ^
      nodes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsSnapshotDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          enabled == other.enabled &&
          displaySpeed == other.displaySpeed &&
          generation == other.generation &&
          proxyUp == other.proxyUp &&
          proxyDown == other.proxyDown &&
          directUp == other.directUp &&
          directDown == other.directDown &&
          nodes == other.nodes &&
          error == other.error;
}

/// Live traffic counters + rates (status bar / node table).
class TrafficBatchDto {
  final BigInt epoch;
  final BigInt seq;
  final BigInt generation;
  final BigInt proxyUp;
  final BigInt proxyDown;
  final BigInt directUp;
  final BigInt directDown;
  final BigInt proxyUpBps;
  final BigInt proxyDownBps;
  final BigInt directUpBps;
  final BigInt directDownBps;
  final List<NodeTrafficDto> nodes;

  const TrafficBatchDto({
    required this.epoch,
    required this.seq,
    required this.generation,
    required this.proxyUp,
    required this.proxyDown,
    required this.directUp,
    required this.directDown,
    required this.proxyUpBps,
    required this.proxyDownBps,
    required this.directUpBps,
    required this.directDownBps,
    required this.nodes,
  });

  @override
  int get hashCode =>
      epoch.hashCode ^
      seq.hashCode ^
      generation.hashCode ^
      proxyUp.hashCode ^
      proxyDown.hashCode ^
      directUp.hashCode ^
      directDown.hashCode ^
      proxyUpBps.hashCode ^
      proxyDownBps.hashCode ^
      directUpBps.hashCode ^
      directDownBps.hashCode ^
      nodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafficBatchDto &&
          runtimeType == other.runtimeType &&
          epoch == other.epoch &&
          seq == other.seq &&
          generation == other.generation &&
          proxyUp == other.proxyUp &&
          proxyDown == other.proxyDown &&
          directUp == other.directUp &&
          directDown == other.directDown &&
          proxyUpBps == other.proxyUpBps &&
          proxyDownBps == other.proxyDownBps &&
          directUpBps == other.directUpBps &&
          directDownBps == other.directDownBps &&
          nodes == other.nodes;
}
