// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `store`

/// Generate and retain `count` synthetic rows, returning all of them.
List<ProfileSummary> generateProfiles({required int count}) =>
    RustLib.instance.api.crateApiProfilesGenerateProfiles(count: count);

/// Fetch one deterministic page without replacing the retained data set.
List<ProfileSummary> fetchProfilesPage({
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiProfilesFetchProfilesPage(
  offset: offset,
  limit: limit,
);

/// Number of rows currently retained on the Rust side, for UI cross-check.
int rustProfileCount() =>
    RustLib.instance.api.crateApiProfilesRustProfileCount();

/// Fetch a retained row by index.
ProfileSummary? profileAt({required int index}) =>
    RustLib.instance.api.crateApiProfilesProfileAt(index: index);

/// Deterministic ping simulation for a retained row id. No network I/O.
int pingProfile({required String id}) =>
    RustLib.instance.api.crateApiProfilesPingProfile(id: id);

/// Stream progress events while "generating" `count` rows in pages. Used by
/// the UI to confirm events flow back from Rust.
Stream<ProgressEvent> progressStream({required int count}) =>
    RustLib.instance.api.crateApiProfilesProgressStream(count: count);

/// Echo a UI event sequence back to Dart, proving a full round-trip.
UiEventAck echoUiEvent({required BigInt seq, required String kind}) =>
    RustLib.instance.api.crateApiProfilesEchoUiEvent(seq: seq, kind: kind);

/// Run a synthetic blocking loop off the UI thread and return elapsed millis.
Future<BigInt> simulateBlocking({required BigInt ms}) =>
    RustLib.instance.api.crateApiProfilesSimulateBlocking(ms: ms);

/// Progress event streamed while generating synthetic rows.
class ProgressEvent {
  final int seq;
  final int done;
  final int total;

  const ProgressEvent({
    required this.seq,
    required this.done,
    required this.total,
  });

  @override
  int get hashCode => seq.hashCode ^ done.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressEvent &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          done == other.done &&
          total == other.total;
}

/// Acknowledgement for a UI event, echoing the sequence number back so the UI
/// can match its own counter with the Rust side.
class UiEventAck {
  final BigInt seq;
  final String kind;
  final int rustProfileCount;

  const UiEventAck({
    required this.seq,
    required this.kind,
    required this.rustProfileCount,
  });

  @override
  int get hashCode => seq.hashCode ^ kind.hashCode ^ rustProfileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEventAck &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          kind == other.kind &&
          rustProfileCount == other.rustProfileCount;
}
