// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_profile`, `dto_to_rule`, `err_dto`, `export_error`, `profile_to_dto`, `rule_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

/// `list_routings` — all routing profiles in `Sort` order.
RoutingsPageDto listRoutings() =>
    RustLib.instance.api.crateApiRoutingListRoutings();

/// `get_routing` — one routing profile by id.
RoutingDtoResult getRouting({required String id}) =>
    RustLib.instance.api.crateApiRoutingGetRouting(id: id);

/// `save_routing` — insert or replace one routing profile.
RoutingDtoResult saveRouting({required RoutingProfileDto draft}) =>
    RustLib.instance.api.crateApiRoutingSaveRouting(draft: draft);

/// `delete_routing` — remove one routing profile.
SimpleResult deleteRouting({required String id}) =>
    RustLib.instance.api.crateApiRoutingDeleteRouting(id: id);

/// `set_default_routing` — mark one routing profile active.
SimpleResult setDefaultRouting({required String id}) =>
    RustLib.instance.api.crateApiRoutingSetDefaultRouting(id: id);

/// `list_routing_rules` — parsed rules of a profile plus warnings.
RoutingRulesPageDto listRoutingRules({required String routingId}) =>
    RustLib.instance.api.crateApiRoutingListRoutingRules(routingId: routingId);

/// `save_routing_rules` — replace a profile's whole rule list.
RoutingDtoResult saveRoutingRules({
  required String routingId,
  required List<RoutingRuleDto> rules,
}) => RustLib.instance.api.crateApiRoutingSaveRoutingRules(
  routingId: routingId,
  rules: rules,
);

/// `move_routing_rule` — Top(0)/Up(1)/Down(2)/Bottom(3) one rule.
RoutingDtoResult moveRoutingRule({
  required String routingId,
  required int index,
  required int direction,
}) => RustLib.instance.api.crateApiRoutingMoveRoutingRule(
  routingId: routingId,
  index: index,
  direction: direction,
);

/// `import_routing_rules` — parse text and append/replace on the profile.
RoutingRulesTextResult importRoutingRules({
  required String routingId,
  required String text,
  required bool replace,
}) => RustLib.instance.api.crateApiRoutingImportRoutingRules(
  routingId: routingId,
  text: text,
  replace: replace,
);

/// `export_routing_rules` — all rules (or the `ids` selection) as JSON.
RoutingRulesTextResult exportRoutingRules({
  required String routingId,
  required List<String> ids,
}) => RustLib.instance.api.crateApiRoutingExportRoutingRules(
  routingId: routingId,
  ids: ids,
);

/// `get_rule_mode` — current `ERuleMode` name.
RuleModeResult getRuleMode() =>
    RustLib.instance.api.crateApiRoutingGetRuleMode();

/// `set_rule_mode` — switch `Rule` / `Global` / `Direct`.
SimpleResult setRuleMode({required String mode}) =>
    RustLib.instance.api.crateApiRoutingSetRuleMode(mode: mode);

/// Result of `save_routing` / `get_routing`.
class RoutingDtoResult {
  final bool ok;
  final RoutingProfileDto? item;
  final ErrorDto? error;

  const RoutingDtoResult({required this.ok, this.item, this.error});

  @override
  int get hashCode => ok.hashCode ^ item.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingDtoResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          item == other.item &&
          error == other.error;
}

/// One routing profile (`RoutingItem`, 13 properties).
class RoutingProfileDto {
  final String id;
  final String remarks;
  final String url;
  final String ruleSet;
  final int ruleNum;
  final bool enabled;
  final bool locked;
  final String customIcon;
  final String customRulesetPath4Singbox;
  final String domainStrategy;
  final String domainStrategy4Singbox;
  final int sort;
  final bool isActive;

  const RoutingProfileDto({
    required this.id,
    required this.remarks,
    required this.url,
    required this.ruleSet,
    required this.ruleNum,
    required this.enabled,
    required this.locked,
    required this.customIcon,
    required this.customRulesetPath4Singbox,
    required this.domainStrategy,
    required this.domainStrategy4Singbox,
    required this.sort,
    required this.isActive,
  });

  static Future<RoutingProfileDto> default_() =>
      RustLib.instance.api.crateApiRoutingRoutingProfileDtoDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      remarks.hashCode ^
      url.hashCode ^
      ruleSet.hashCode ^
      ruleNum.hashCode ^
      enabled.hashCode ^
      locked.hashCode ^
      customIcon.hashCode ^
      customRulesetPath4Singbox.hashCode ^
      domainStrategy.hashCode ^
      domainStrategy4Singbox.hashCode ^
      sort.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          remarks == other.remarks &&
          url == other.url &&
          ruleSet == other.ruleSet &&
          ruleNum == other.ruleNum &&
          enabled == other.enabled &&
          locked == other.locked &&
          customIcon == other.customIcon &&
          customRulesetPath4Singbox == other.customRulesetPath4Singbox &&
          domainStrategy == other.domainStrategy &&
          domainStrategy4Singbox == other.domainStrategy4Singbox &&
          sort == other.sort &&
          isActive == other.isActive;
}

/// One routing rule (`RulesItem`, 13 properties).
class RoutingRuleDto {
  final String id;
  final String? ruleKind;
  final String? port;
  final String? network;
  final List<String> inboundTag;
  final bool hasInboundTag;
  final String? outboundTag;
  final List<String> ip;
  final bool hasIp;
  final List<String> domain;
  final bool hasDomain;
  final List<String> protocol;
  final bool hasProtocol;
  final List<String> process;
  final bool hasProcess;
  final bool enabled;
  final String? remarks;
  final int? ruleType;

  const RoutingRuleDto({
    required this.id,
    this.ruleKind,
    this.port,
    this.network,
    required this.inboundTag,
    required this.hasInboundTag,
    this.outboundTag,
    required this.ip,
    required this.hasIp,
    required this.domain,
    required this.hasDomain,
    required this.protocol,
    required this.hasProtocol,
    required this.process,
    required this.hasProcess,
    required this.enabled,
    this.remarks,
    this.ruleType,
  });

  static Future<RoutingRuleDto> default_() =>
      RustLib.instance.api.crateApiRoutingRoutingRuleDtoDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      ruleKind.hashCode ^
      port.hashCode ^
      network.hashCode ^
      inboundTag.hashCode ^
      hasInboundTag.hashCode ^
      outboundTag.hashCode ^
      ip.hashCode ^
      hasIp.hashCode ^
      domain.hashCode ^
      hasDomain.hashCode ^
      protocol.hashCode ^
      hasProtocol.hashCode ^
      process.hashCode ^
      hasProcess.hashCode ^
      enabled.hashCode ^
      remarks.hashCode ^
      ruleType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingRuleDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          ruleKind == other.ruleKind &&
          port == other.port &&
          network == other.network &&
          inboundTag == other.inboundTag &&
          hasInboundTag == other.hasInboundTag &&
          outboundTag == other.outboundTag &&
          ip == other.ip &&
          hasIp == other.hasIp &&
          domain == other.domain &&
          hasDomain == other.hasDomain &&
          protocol == other.protocol &&
          hasProtocol == other.hasProtocol &&
          process == other.process &&
          hasProcess == other.hasProcess &&
          enabled == other.enabled &&
          remarks == other.remarks &&
          ruleType == other.ruleType;
}

/// Result of a routing-rules query (parsed rule list + warnings).
class RoutingRulesPageDto {
  final bool ok;
  final List<RoutingRuleDto> rules;
  final List<RoutingWarningDto> warnings;
  final ErrorDto? error;

  const RoutingRulesPageDto({
    required this.ok,
    required this.rules,
    required this.warnings,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ rules.hashCode ^ warnings.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingRulesPageDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          rules == other.rules &&
          warnings == other.warnings &&
          error == other.error;
}

/// Result of a rules text operation (import/export/move).
class RoutingRulesTextResult {
  final bool ok;
  final String text;
  final int ruleCount;
  final ErrorDto? error;

  const RoutingRulesTextResult({
    required this.ok,
    required this.text,
    required this.ruleCount,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ text.hashCode ^ ruleCount.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingRulesTextResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          text == other.text &&
          ruleCount == other.ruleCount &&
          error == other.error;
}

/// One structured outbound-tag warning.
class RoutingWarningDto {
  final String code;
  final String message;
  final String? fieldPath;

  const RoutingWarningDto({
    required this.code,
    required this.message,
    this.fieldPath,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ fieldPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingWarningDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          fieldPath == other.fieldPath;
}

/// Result of `list_routings`.
class RoutingsPageDto {
  final List<RoutingProfileDto> items;
  final ErrorDto? error;

  const RoutingsPageDto({required this.items, this.error});

  @override
  int get hashCode => items.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingsPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          error == other.error;
}

/// Current routing mode (`ERuleMode`).
class RuleModeResult {
  final String mode;
  final ErrorDto? error;

  const RuleModeResult({required this.mode, this.error});

  @override
  int get hashCode => mode.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleModeResult &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          error == other.error;
}
