// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `changes_to_dto`, `extra_to_json`, `group_revisions_to_json`, `json_to_extra`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// `get_settings` — the normalised tree plus revision counters.
SettingsLoadDto getSettings() =>
    RustLib.instance.api.crateApiSettingsGetSettings();

/// `save_settings_json` — whole-tree save from the canonical `Config` JSON.
///
/// This is the UI's primary save path: it keeps unknown keys and the
/// null/empty-string distinction intact without round-tripping every DTO.
SaveSettingsResult saveSettingsJson({
  required String settingsJson,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiSettingsSaveSettingsJson(
  settingsJson: settingsJson,
  expectedRevision: expectedRevision,
);

/// `settings_revision` — the current whole-tree revision.
BigInt settingsRevision() =>
    RustLib.instance.api.crateApiSettingsSettingsRevision();

/// `save_settings` — whole-tree optimistic save.
SaveSettingsResult saveSettings({
  required SettingsDto settings,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiSettingsSaveSettings(
  settings: settings,
  expectedRevision: expectedRevision,
);

/// `save_settings_group` — replace one top-level group.
SaveSettingsResult saveSettingsGroup({
  required String group,
  required String patchJson,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiSettingsSaveSettingsGroup(
  group: group,
  patchJson: patchJson,
  expectedRevision: expectedRevision,
);

/// Test/debug helper: validate the current tree without saving it.
bool validateCurrentSettings() =>
    RustLib.instance.api.crateApiSettingsValidateCurrentSettings();

/// `CheckUpdateItem` DTO.
class CheckUpdateItemDto {
  final bool checkPreReleaseUpdate;
  final bool updateViaProxy;
  final List<String>? selectedCoreTypes;
  final String extraJson;

  const CheckUpdateItemDto({
    required this.checkPreReleaseUpdate,
    required this.updateViaProxy,
    this.selectedCoreTypes,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      checkPreReleaseUpdate.hashCode ^
      updateViaProxy.hashCode ^
      selectedCoreTypes.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckUpdateItemDto &&
          runtimeType == other.runtimeType &&
          checkPreReleaseUpdate == other.checkPreReleaseUpdate &&
          updateViaProxy == other.updateViaProxy &&
          selectedCoreTypes == other.selectedCoreTypes &&
          extraJson == other.extraJson;
}

/// `ClashUIItem` DTO.
class ClashUiItemDto {
  final bool enableIpv6;
  final bool enableMixinContent;
  final int proxiesSorting;
  final bool proxiesAutoRefresh;
  final int proxiesRefreshInterval;
  final bool connectionsAutoRefresh;
  final int connectionsRefreshInterval;
  final List<ColumnItemDto> connectionsColumnItem;
  final String extraJson;

  const ClashUiItemDto({
    required this.enableIpv6,
    required this.enableMixinContent,
    required this.proxiesSorting,
    required this.proxiesAutoRefresh,
    required this.proxiesRefreshInterval,
    required this.connectionsAutoRefresh,
    required this.connectionsRefreshInterval,
    required this.connectionsColumnItem,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      enableIpv6.hashCode ^
      enableMixinContent.hashCode ^
      proxiesSorting.hashCode ^
      proxiesAutoRefresh.hashCode ^
      proxiesRefreshInterval.hashCode ^
      connectionsAutoRefresh.hashCode ^
      connectionsRefreshInterval.hashCode ^
      connectionsColumnItem.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashUiItemDto &&
          runtimeType == other.runtimeType &&
          enableIpv6 == other.enableIpv6 &&
          enableMixinContent == other.enableMixinContent &&
          proxiesSorting == other.proxiesSorting &&
          proxiesAutoRefresh == other.proxiesAutoRefresh &&
          proxiesRefreshInterval == other.proxiesRefreshInterval &&
          connectionsAutoRefresh == other.connectionsAutoRefresh &&
          connectionsRefreshInterval == other.connectionsRefreshInterval &&
          connectionsColumnItem == other.connectionsColumnItem &&
          extraJson == other.extraJson;
}

/// A main-table or Clash connection column (`ColumnItem`).
class ColumnItemDto {
  final String name;
  final int width;
  final int index;
  final String extraJson;

  const ColumnItemDto({
    required this.name,
    required this.width,
    required this.index,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^ width.hashCode ^ index.hashCode ^ extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnItemDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          index == other.index &&
          extraJson == other.extraJson;
}

/// `ConstItem` DTO.
class ConstItemDto {
  final String? subConvertUrl;
  final String? geoSourceUrl;
  final String? srsSourceUrl;
  final String? routeRulesTemplateSourceUrl;
  final String extraJson;

  const ConstItemDto({
    this.subConvertUrl,
    this.geoSourceUrl,
    this.srsSourceUrl,
    this.routeRulesTemplateSourceUrl,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      subConvertUrl.hashCode ^
      geoSourceUrl.hashCode ^
      srsSourceUrl.hashCode ^
      routeRulesTemplateSourceUrl.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConstItemDto &&
          runtimeType == other.runtimeType &&
          subConvertUrl == other.subConvertUrl &&
          geoSourceUrl == other.geoSourceUrl &&
          srsSourceUrl == other.srsSourceUrl &&
          routeRulesTemplateSourceUrl == other.routeRulesTemplateSourceUrl &&
          extraJson == other.extraJson;
}

/// `CoreBasicItem` DTO.
class CoreBasicItemDto {
  final bool logEnabled;
  final String? loglevel;
  final String? defFingerprint;
  final String? defUserAgent;
  final String? sendThrough;
  final String? bindInterface;
  final bool enableFragment;
  final bool enableFinalFragment;
  final bool enableCacheFile4Sbox;
  final String extraJson;

  const CoreBasicItemDto({
    required this.logEnabled,
    this.loglevel,
    this.defFingerprint,
    this.defUserAgent,
    this.sendThrough,
    this.bindInterface,
    required this.enableFragment,
    required this.enableFinalFragment,
    required this.enableCacheFile4Sbox,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      logEnabled.hashCode ^
      loglevel.hashCode ^
      defFingerprint.hashCode ^
      defUserAgent.hashCode ^
      sendThrough.hashCode ^
      bindInterface.hashCode ^
      enableFragment.hashCode ^
      enableFinalFragment.hashCode ^
      enableCacheFile4Sbox.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreBasicItemDto &&
          runtimeType == other.runtimeType &&
          logEnabled == other.logEnabled &&
          loglevel == other.loglevel &&
          defFingerprint == other.defFingerprint &&
          defUserAgent == other.defUserAgent &&
          sendThrough == other.sendThrough &&
          bindInterface == other.bindInterface &&
          enableFragment == other.enableFragment &&
          enableFinalFragment == other.enableFinalFragment &&
          enableCacheFile4Sbox == other.enableCacheFile4Sbox &&
          extraJson == other.extraJson;
}

/// `CoreTypeItem` DTO.
class CoreTypeBindingDto {
  final ConfigType configType;
  final CoreType coreType;

  const CoreTypeBindingDto({required this.configType, required this.coreType});

  @override
  int get hashCode => configType.hashCode ^ coreType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreTypeBindingDto &&
          runtimeType == other.runtimeType &&
          configType == other.configType &&
          coreType == other.coreType;
}

/// `Fragment4RayItem` DTO.
class Fragment4RayItemDto {
  final String? packets;
  final List<String>? lengths;
  final List<String>? delays;
  final String? maxSplit;
  final String? length;
  final String? interval;
  final String extraJson;

  const Fragment4RayItemDto({
    this.packets,
    this.lengths,
    this.delays,
    this.maxSplit,
    this.length,
    this.interval,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      packets.hashCode ^
      lengths.hashCode ^
      delays.hashCode ^
      maxSplit.hashCode ^
      length.hashCode ^
      interval.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Fragment4RayItemDto &&
          runtimeType == other.runtimeType &&
          packets == other.packets &&
          lengths == other.lengths &&
          delays == other.delays &&
          maxSplit == other.maxSplit &&
          length == other.length &&
          interval == other.interval &&
          extraJson == other.extraJson;
}

/// `KeyEventItem` DTO.
class GlobalHotkeyDto {
  final int action;
  final bool alt;
  final bool control;
  final bool shift;
  final int? keyCode;
  final String extraJson;

  const GlobalHotkeyDto({
    required this.action,
    required this.alt,
    required this.control,
    required this.shift,
    this.keyCode,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      alt.hashCode ^
      control.hashCode ^
      shift.hashCode ^
      keyCode.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalHotkeyDto &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          alt == other.alt &&
          control == other.control &&
          shift == other.shift &&
          keyCode == other.keyCode &&
          extraJson == other.extraJson;
}

/// `GrpcItem` DTO (no UI control).
class GrpcItemDto {
  final int? idleTimeout;
  final int? healthCheckTimeout;
  final bool? permitWithoutStream;
  final int? initialWindowsSize;
  final String extraJson;

  const GrpcItemDto({
    this.idleTimeout,
    this.healthCheckTimeout,
    this.permitWithoutStream,
    this.initialWindowsSize,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      idleTimeout.hashCode ^
      healthCheckTimeout.hashCode ^
      permitWithoutStream.hashCode ^
      initialWindowsSize.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GrpcItemDto &&
          runtimeType == other.runtimeType &&
          idleTimeout == other.idleTimeout &&
          healthCheckTimeout == other.healthCheckTimeout &&
          permitWithoutStream == other.permitWithoutStream &&
          initialWindowsSize == other.initialWindowsSize &&
          extraJson == other.extraJson;
}

/// `GUIItem` DTO.
class GuiItemDto {
  final bool autoRun;
  final bool enableStatistics;
  final bool displayRealTimeSpeed;
  final bool keepOlderDedupl;
  final int autoUpdateInterval;
  final int trayMenuServersLimit;
  final bool enableHwa;
  final bool enableLog;
  final String? rootCertProvider;
  final String extraJson;

  const GuiItemDto({
    required this.autoRun,
    required this.enableStatistics,
    required this.displayRealTimeSpeed,
    required this.keepOlderDedupl,
    required this.autoUpdateInterval,
    required this.trayMenuServersLimit,
    required this.enableHwa,
    required this.enableLog,
    this.rootCertProvider,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      autoRun.hashCode ^
      enableStatistics.hashCode ^
      displayRealTimeSpeed.hashCode ^
      keepOlderDedupl.hashCode ^
      autoUpdateInterval.hashCode ^
      trayMenuServersLimit.hashCode ^
      enableHwa.hashCode ^
      enableLog.hashCode ^
      rootCertProvider.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiItemDto &&
          runtimeType == other.runtimeType &&
          autoRun == other.autoRun &&
          enableStatistics == other.enableStatistics &&
          displayRealTimeSpeed == other.displayRealTimeSpeed &&
          keepOlderDedupl == other.keepOlderDedupl &&
          autoUpdateInterval == other.autoUpdateInterval &&
          trayMenuServersLimit == other.trayMenuServersLimit &&
          enableHwa == other.enableHwa &&
          enableLog == other.enableLog &&
          rootCertProvider == other.rootCertProvider &&
          extraJson == other.extraJson;
}

/// `HappyEyeballs4RayItem` DTO.
class HappyEyeballs4RayItemDto {
  final int? tryDelayMs;
  final bool? prioritizeIpv6;
  final int? interleave;
  final int? maxConcurrentTry;
  final String extraJson;

  const HappyEyeballs4RayItemDto({
    this.tryDelayMs,
    this.prioritizeIpv6,
    this.interleave,
    this.maxConcurrentTry,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      tryDelayMs.hashCode ^
      prioritizeIpv6.hashCode ^
      interleave.hashCode ^
      maxConcurrentTry.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HappyEyeballs4RayItemDto &&
          runtimeType == other.runtimeType &&
          tryDelayMs == other.tryDelayMs &&
          prioritizeIpv6 == other.prioritizeIpv6 &&
          interleave == other.interleave &&
          maxConcurrentTry == other.maxConcurrentTry &&
          extraJson == other.extraJson;
}

/// `HysteriaItem` DTO.
class HysteriaItemDto {
  final int upMbps;
  final int downMbps;
  final int hopInterval;
  final String extraJson;

  const HysteriaItemDto({
    required this.upMbps,
    required this.downMbps,
    required this.hopInterval,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      upMbps.hashCode ^
      downMbps.hashCode ^
      hopInterval.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HysteriaItemDto &&
          runtimeType == other.runtimeType &&
          upMbps == other.upMbps &&
          downMbps == other.downMbps &&
          hopInterval == other.hopInterval &&
          extraJson == other.extraJson;
}

/// `InItem` DTO.
class InboundListenerDto {
  final int localPort;

  /// `EInboundProtocol` numeric value.
  final int protocol;
  final bool udpEnabled;
  final bool sniffingEnabled;
  final List<String>? destOverride;
  final bool routeOnly;
  final bool allowLanConn;
  final bool newPort4Lan;
  final String user;
  final String pass;
  final bool secondLocalPortEnabled;
  final String extraJson;

  const InboundListenerDto({
    required this.localPort,
    required this.protocol,
    required this.udpEnabled,
    required this.sniffingEnabled,
    this.destOverride,
    required this.routeOnly,
    required this.allowLanConn,
    required this.newPort4Lan,
    required this.user,
    required this.pass,
    required this.secondLocalPortEnabled,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      localPort.hashCode ^
      protocol.hashCode ^
      udpEnabled.hashCode ^
      sniffingEnabled.hashCode ^
      destOverride.hashCode ^
      routeOnly.hashCode ^
      allowLanConn.hashCode ^
      newPort4Lan.hashCode ^
      user.hashCode ^
      pass.hashCode ^
      secondLocalPortEnabled.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboundListenerDto &&
          runtimeType == other.runtimeType &&
          localPort == other.localPort &&
          protocol == other.protocol &&
          udpEnabled == other.udpEnabled &&
          sniffingEnabled == other.sniffingEnabled &&
          destOverride == other.destOverride &&
          routeOnly == other.routeOnly &&
          allowLanConn == other.allowLanConn &&
          newPort4Lan == other.newPort4Lan &&
          user == other.user &&
          pass == other.pass &&
          secondLocalPortEnabled == other.secondLocalPortEnabled &&
          extraJson == other.extraJson;
}

/// `KcpItem` DTO (UI tab commented out upstream).
class KcpItemDto {
  final int mtu;
  final int tti;
  final int uplinkCapacity;
  final int downlinkCapacity;
  final int cwndMultiplier;
  final int maxSendingWindow;
  final String extraJson;

  const KcpItemDto({
    required this.mtu,
    required this.tti,
    required this.uplinkCapacity,
    required this.downlinkCapacity,
    required this.cwndMultiplier,
    required this.maxSendingWindow,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      mtu.hashCode ^
      tti.hashCode ^
      uplinkCapacity.hashCode ^
      downlinkCapacity.hashCode ^
      cwndMultiplier.hashCode ^
      maxSendingWindow.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KcpItemDto &&
          runtimeType == other.runtimeType &&
          mtu == other.mtu &&
          tti == other.tti &&
          uplinkCapacity == other.uplinkCapacity &&
          downlinkCapacity == other.downlinkCapacity &&
          cwndMultiplier == other.cwndMultiplier &&
          maxSendingWindow == other.maxSendingWindow &&
          extraJson == other.extraJson;
}

/// `MsgUIItem` DTO.
class MsgUiItemDto {
  final String? mainMsgFilter;
  final bool? autoRefresh;
  final String extraJson;

  const MsgUiItemDto({
    this.mainMsgFilter,
    this.autoRefresh,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      mainMsgFilter.hashCode ^ autoRefresh.hashCode ^ extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MsgUiItemDto &&
          runtimeType == other.runtimeType &&
          mainMsgFilter == other.mainMsgFilter &&
          autoRefresh == other.autoRefresh &&
          extraJson == other.extraJson;
}

/// `Mux4RayItem` DTO.
class Mux4RayItemDto {
  final int? concurrency;
  final int? xudpConcurrency;
  final String? xudpProxyUdp443;
  final String extraJson;

  const Mux4RayItemDto({
    this.concurrency,
    this.xudpConcurrency,
    this.xudpProxyUdp443,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      concurrency.hashCode ^
      xudpConcurrency.hashCode ^
      xudpProxyUdp443.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mux4RayItemDto &&
          runtimeType == other.runtimeType &&
          concurrency == other.concurrency &&
          xudpConcurrency == other.xudpConcurrency &&
          xudpProxyUdp443 == other.xudpProxyUdp443 &&
          extraJson == other.extraJson;
}

/// `Mux4SboxItem` DTO.
class Mux4SboxItemDto {
  final String? protocol;
  final int maxConnections;
  final bool? padding;
  final String extraJson;

  const Mux4SboxItemDto({
    this.protocol,
    required this.maxConnections,
    this.padding,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      maxConnections.hashCode ^
      padding.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mux4SboxItemDto &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          maxConnections == other.maxConnections &&
          padding == other.padding &&
          extraJson == other.extraJson;
}

/// `RoutingBasicItem` DTO.
class RoutingBasicItemDto {
  final String? domainStrategy;
  final String? domainStrategy4Singbox;
  final String? routingIndexId;
  final String extraJson;

  const RoutingBasicItemDto({
    this.domainStrategy,
    this.domainStrategy4Singbox,
    this.routingIndexId,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      domainStrategy.hashCode ^
      domainStrategy4Singbox.hashCode ^
      routingIndexId.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutingBasicItemDto &&
          runtimeType == other.runtimeType &&
          domainStrategy == other.domainStrategy &&
          domainStrategy4Singbox == other.domainStrategy4Singbox &&
          routingIndexId == other.routingIndexId &&
          extraJson == other.extraJson;
}

/// `save_settings` / `save_settings_group` result.
class SaveSettingsResult {
  final bool ok;
  final BigInt? newRevision;
  final List<SettingsChangeDto> changes;
  final List<String> restartCoreFields;
  final List<String> restartAppFields;
  final List<String> nextLaunchFields;
  final ErrorDto? error;

  const SaveSettingsResult({
    required this.ok,
    this.newRevision,
    required this.changes,
    required this.restartCoreFields,
    required this.restartAppFields,
    required this.nextLaunchFields,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      newRevision.hashCode ^
      changes.hashCode ^
      restartCoreFields.hashCode ^
      restartAppFields.hashCode ^
      nextLaunchFields.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveSettingsResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          newRevision == other.newRevision &&
          changes == other.changes &&
          restartCoreFields == other.restartCoreFields &&
          restartAppFields == other.restartAppFields &&
          nextLaunchFields == other.nextLaunchFields &&
          error == other.error;
}

/// One classified settings change.
class SettingsChangeDto {
  final String group;
  final String field;
  final String path;
  final String timing;

  const SettingsChangeDto({
    required this.group,
    required this.field,
    required this.path,
    required this.timing,
  });

  @override
  int get hashCode =>
      group.hashCode ^ field.hashCode ^ path.hashCode ^ timing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsChangeDto &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          field == other.field &&
          path == other.path &&
          timing == other.timing;
}

/// The full settings tree DTO.
class SettingsDto {
  final String? indexId;
  final String? subIndexId;
  final CoreBasicItemDto coreBasicItem;
  final TunModeItemDto tunModeItem;
  final KcpItemDto kcpItem;
  final GrpcItemDto grpcItem;
  final RoutingBasicItemDto routingBasicItem;
  final GuiItemDto guiItem;
  final MsgUiItemDto msgUiItem;
  final UiItemDto uiItem;
  final ConstItemDto constItem;
  final SpeedTestItemDto speedTestItem;
  final Mux4RayItemDto mux4RayItem;
  final Mux4SboxItemDto mux4SboxItem;
  final HysteriaItemDto hysteriaItem;
  final ClashUiItemDto clashUiItem;
  final SystemProxyItemDto systemProxyItem;
  final WebDavItemDto webDavItem;
  final CheckUpdateItemDto checkUpdateItem;
  final Fragment4RayItemDto? fragment4RayItem;
  final List<InboundListenerDto> inbound;
  final List<GlobalHotkeyDto> globalHotkeys;
  final List<CoreTypeBindingDto>? coreTypeItem;
  final SimpleDnsItemDto simpleDnsItem;
  final HappyEyeballs4RayItemDto happyEyeballs4RayItem;
  final String extraJson;

  const SettingsDto({
    this.indexId,
    this.subIndexId,
    required this.coreBasicItem,
    required this.tunModeItem,
    required this.kcpItem,
    required this.grpcItem,
    required this.routingBasicItem,
    required this.guiItem,
    required this.msgUiItem,
    required this.uiItem,
    required this.constItem,
    required this.speedTestItem,
    required this.mux4RayItem,
    required this.mux4SboxItem,
    required this.hysteriaItem,
    required this.clashUiItem,
    required this.systemProxyItem,
    required this.webDavItem,
    required this.checkUpdateItem,
    this.fragment4RayItem,
    required this.inbound,
    required this.globalHotkeys,
    this.coreTypeItem,
    required this.simpleDnsItem,
    required this.happyEyeballs4RayItem,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      indexId.hashCode ^
      subIndexId.hashCode ^
      coreBasicItem.hashCode ^
      tunModeItem.hashCode ^
      kcpItem.hashCode ^
      grpcItem.hashCode ^
      routingBasicItem.hashCode ^
      guiItem.hashCode ^
      msgUiItem.hashCode ^
      uiItem.hashCode ^
      constItem.hashCode ^
      speedTestItem.hashCode ^
      mux4RayItem.hashCode ^
      mux4SboxItem.hashCode ^
      hysteriaItem.hashCode ^
      clashUiItem.hashCode ^
      systemProxyItem.hashCode ^
      webDavItem.hashCode ^
      checkUpdateItem.hashCode ^
      fragment4RayItem.hashCode ^
      inbound.hashCode ^
      globalHotkeys.hashCode ^
      coreTypeItem.hashCode ^
      simpleDnsItem.hashCode ^
      happyEyeballs4RayItem.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          indexId == other.indexId &&
          subIndexId == other.subIndexId &&
          coreBasicItem == other.coreBasicItem &&
          tunModeItem == other.tunModeItem &&
          kcpItem == other.kcpItem &&
          grpcItem == other.grpcItem &&
          routingBasicItem == other.routingBasicItem &&
          guiItem == other.guiItem &&
          msgUiItem == other.msgUiItem &&
          uiItem == other.uiItem &&
          constItem == other.constItem &&
          speedTestItem == other.speedTestItem &&
          mux4RayItem == other.mux4RayItem &&
          mux4SboxItem == other.mux4SboxItem &&
          hysteriaItem == other.hysteriaItem &&
          clashUiItem == other.clashUiItem &&
          systemProxyItem == other.systemProxyItem &&
          webDavItem == other.webDavItem &&
          checkUpdateItem == other.checkUpdateItem &&
          fragment4RayItem == other.fragment4RayItem &&
          inbound == other.inbound &&
          globalHotkeys == other.globalHotkeys &&
          coreTypeItem == other.coreTypeItem &&
          simpleDnsItem == other.simpleDnsItem &&
          happyEyeballs4RayItem == other.happyEyeballs4RayItem &&
          extraJson == other.extraJson;
}

/// `get_settings` result.
class SettingsLoadDto {
  final bool ok;
  final BigInt revision;
  final String groupRevisionsJson;
  final SettingsDto? settings;

  /// Canonical `guiNConfig.json` `Config` JSON (PascalCase, unknown keys and
  /// null/empty distinctions preserved). The UI edits this directly and saves
  /// it back through [`save_settings_json`].
  final String settingsJson;
  final ErrorDto? error;

  const SettingsLoadDto({
    required this.ok,
    required this.revision,
    required this.groupRevisionsJson,
    this.settings,
    required this.settingsJson,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      revision.hashCode ^
      groupRevisionsJson.hashCode ^
      settings.hashCode ^
      settingsJson.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsLoadDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          revision == other.revision &&
          groupRevisionsJson == other.groupRevisionsJson &&
          settings == other.settings &&
          settingsJson == other.settingsJson &&
          error == other.error;
}

/// `SimpleDNSItem` DTO.
class SimpleDnsItemDto {
  final bool? useSystemHosts;
  final bool? addCommonHosts;
  final bool? fakeIp;
  final bool? globalFakeIp;
  final String? fakeIpRange;
  final bool? blockBindingQuery;
  final bool? blockAaaaQuery;
  final String? directDns;
  final String? remoteDns;
  final String? bootstrapDns;
  final String? strategy4Freedom;
  final String? strategy4Proxy;
  final String? strategy4ProxyDial;
  final bool? serveStale;
  final bool? parallelQuery;
  final String? hosts;
  final String? directExpectedIps;
  final bool? enableHappyEyeballs;
  final String extraJson;

  const SimpleDnsItemDto({
    this.useSystemHosts,
    this.addCommonHosts,
    this.fakeIp,
    this.globalFakeIp,
    this.fakeIpRange,
    this.blockBindingQuery,
    this.blockAaaaQuery,
    this.directDns,
    this.remoteDns,
    this.bootstrapDns,
    this.strategy4Freedom,
    this.strategy4Proxy,
    this.strategy4ProxyDial,
    this.serveStale,
    this.parallelQuery,
    this.hosts,
    this.directExpectedIps,
    this.enableHappyEyeballs,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      useSystemHosts.hashCode ^
      addCommonHosts.hashCode ^
      fakeIp.hashCode ^
      globalFakeIp.hashCode ^
      fakeIpRange.hashCode ^
      blockBindingQuery.hashCode ^
      blockAaaaQuery.hashCode ^
      directDns.hashCode ^
      remoteDns.hashCode ^
      bootstrapDns.hashCode ^
      strategy4Freedom.hashCode ^
      strategy4Proxy.hashCode ^
      strategy4ProxyDial.hashCode ^
      serveStale.hashCode ^
      parallelQuery.hashCode ^
      hosts.hashCode ^
      directExpectedIps.hashCode ^
      enableHappyEyeballs.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleDnsItemDto &&
          runtimeType == other.runtimeType &&
          useSystemHosts == other.useSystemHosts &&
          addCommonHosts == other.addCommonHosts &&
          fakeIp == other.fakeIp &&
          globalFakeIp == other.globalFakeIp &&
          fakeIpRange == other.fakeIpRange &&
          blockBindingQuery == other.blockBindingQuery &&
          blockAaaaQuery == other.blockAaaaQuery &&
          directDns == other.directDns &&
          remoteDns == other.remoteDns &&
          bootstrapDns == other.bootstrapDns &&
          strategy4Freedom == other.strategy4Freedom &&
          strategy4Proxy == other.strategy4Proxy &&
          strategy4ProxyDial == other.strategy4ProxyDial &&
          serveStale == other.serveStale &&
          parallelQuery == other.parallelQuery &&
          hosts == other.hosts &&
          directExpectedIps == other.directExpectedIps &&
          enableHappyEyeballs == other.enableHappyEyeballs &&
          extraJson == other.extraJson;
}

/// `SpeedTestItem` DTO.
class SpeedTestItemDto {
  final int speedTestTimeout;
  final String? speedTestUrl;
  final String? speedPingTestUrl;
  final int mixedConcurrencyCount;
  final String? ipapiUrl;
  final String? udpTestTarget;
  final int? speedTestPageSize;
  final int? speedTestDelayInterval;
  final String extraJson;

  const SpeedTestItemDto({
    required this.speedTestTimeout,
    this.speedTestUrl,
    this.speedPingTestUrl,
    required this.mixedConcurrencyCount,
    this.ipapiUrl,
    this.udpTestTarget,
    this.speedTestPageSize,
    this.speedTestDelayInterval,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      speedTestTimeout.hashCode ^
      speedTestUrl.hashCode ^
      speedPingTestUrl.hashCode ^
      mixedConcurrencyCount.hashCode ^
      ipapiUrl.hashCode ^
      udpTestTarget.hashCode ^
      speedTestPageSize.hashCode ^
      speedTestDelayInterval.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTestItemDto &&
          runtimeType == other.runtimeType &&
          speedTestTimeout == other.speedTestTimeout &&
          speedTestUrl == other.speedTestUrl &&
          speedPingTestUrl == other.speedPingTestUrl &&
          mixedConcurrencyCount == other.mixedConcurrencyCount &&
          ipapiUrl == other.ipapiUrl &&
          udpTestTarget == other.udpTestTarget &&
          speedTestPageSize == other.speedTestPageSize &&
          speedTestDelayInterval == other.speedTestDelayInterval &&
          extraJson == other.extraJson;
}

/// `SystemProxyItem` DTO. Stored only in this task; the real WinINET work is T13.
class SystemProxyItemDto {
  /// `ESysProxyType` numeric value (0..3).
  final int sysProxyType;
  final String? systemProxyExceptions;
  final bool notProxyLocalAddress;
  final String? systemProxyAdvancedProtocol;
  final String? customSystemProxyPacPath;
  final String? customSystemProxyScriptPath;
  final String extraJson;

  const SystemProxyItemDto({
    required this.sysProxyType,
    this.systemProxyExceptions,
    required this.notProxyLocalAddress,
    this.systemProxyAdvancedProtocol,
    this.customSystemProxyPacPath,
    this.customSystemProxyScriptPath,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      sysProxyType.hashCode ^
      systemProxyExceptions.hashCode ^
      notProxyLocalAddress.hashCode ^
      systemProxyAdvancedProtocol.hashCode ^
      customSystemProxyPacPath.hashCode ^
      customSystemProxyScriptPath.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemProxyItemDto &&
          runtimeType == other.runtimeType &&
          sysProxyType == other.sysProxyType &&
          systemProxyExceptions == other.systemProxyExceptions &&
          notProxyLocalAddress == other.notProxyLocalAddress &&
          systemProxyAdvancedProtocol == other.systemProxyAdvancedProtocol &&
          customSystemProxyPacPath == other.customSystemProxyPacPath &&
          customSystemProxyScriptPath == other.customSystemProxyScriptPath &&
          extraJson == other.extraJson;
}

/// `TunModeItem` DTO.
class TunModeItemDto {
  final bool enableTun;
  final bool autoRoute;
  final bool strictRoute;
  final String? stack;
  final int mtu;
  final bool enableIpv6Address;
  final String? icmpRouting;
  final bool enableLegacyProtect;
  final List<String>? routeExcludeAddress;
  final String? ipv4Address;
  final String? ipv6Address;
  final String extraJson;

  const TunModeItemDto({
    required this.enableTun,
    required this.autoRoute,
    required this.strictRoute,
    this.stack,
    required this.mtu,
    required this.enableIpv6Address,
    this.icmpRouting,
    required this.enableLegacyProtect,
    this.routeExcludeAddress,
    this.ipv4Address,
    this.ipv6Address,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      enableTun.hashCode ^
      autoRoute.hashCode ^
      strictRoute.hashCode ^
      stack.hashCode ^
      mtu.hashCode ^
      enableIpv6Address.hashCode ^
      icmpRouting.hashCode ^
      enableLegacyProtect.hashCode ^
      routeExcludeAddress.hashCode ^
      ipv4Address.hashCode ^
      ipv6Address.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunModeItemDto &&
          runtimeType == other.runtimeType &&
          enableTun == other.enableTun &&
          autoRoute == other.autoRoute &&
          strictRoute == other.strictRoute &&
          stack == other.stack &&
          mtu == other.mtu &&
          enableIpv6Address == other.enableIpv6Address &&
          icmpRouting == other.icmpRouting &&
          enableLegacyProtect == other.enableLegacyProtect &&
          routeExcludeAddress == other.routeExcludeAddress &&
          ipv4Address == other.ipv4Address &&
          ipv6Address == other.ipv6Address &&
          extraJson == other.extraJson;
}

/// `UIItem` DTO.
class UiItemDto {
  final bool enableAutoAdjustMainLvColWidth;
  final int mainGirdHeight1;
  final int mainGirdHeight2;

  /// `EGirdOrientation` numeric value (0/1/2).
  final int mainGirdOrientation;
  final String? colorPrimaryName;
  final String? currentTheme;
  final String? currentLanguage;
  final String? currentFontFamily;
  final int currentFontSize;
  final bool enableDragDropSort;
  final bool doubleClick2Activate;
  final bool autoHideStartup;
  final bool hide2TrayWhenClose;
  final bool macosShowInDock;
  final List<ColumnItemDto> mainColumnItem;
  final List<WindowSizeItemDto> windowSizeItem;
  final bool hideColumnIpInfo;
  final String extraJson;

  const UiItemDto({
    required this.enableAutoAdjustMainLvColWidth,
    required this.mainGirdHeight1,
    required this.mainGirdHeight2,
    required this.mainGirdOrientation,
    this.colorPrimaryName,
    this.currentTheme,
    this.currentLanguage,
    this.currentFontFamily,
    required this.currentFontSize,
    required this.enableDragDropSort,
    required this.doubleClick2Activate,
    required this.autoHideStartup,
    required this.hide2TrayWhenClose,
    required this.macosShowInDock,
    required this.mainColumnItem,
    required this.windowSizeItem,
    required this.hideColumnIpInfo,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      enableAutoAdjustMainLvColWidth.hashCode ^
      mainGirdHeight1.hashCode ^
      mainGirdHeight2.hashCode ^
      mainGirdOrientation.hashCode ^
      colorPrimaryName.hashCode ^
      currentTheme.hashCode ^
      currentLanguage.hashCode ^
      currentFontFamily.hashCode ^
      currentFontSize.hashCode ^
      enableDragDropSort.hashCode ^
      doubleClick2Activate.hashCode ^
      autoHideStartup.hashCode ^
      hide2TrayWhenClose.hashCode ^
      macosShowInDock.hashCode ^
      mainColumnItem.hashCode ^
      windowSizeItem.hashCode ^
      hideColumnIpInfo.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiItemDto &&
          runtimeType == other.runtimeType &&
          enableAutoAdjustMainLvColWidth ==
              other.enableAutoAdjustMainLvColWidth &&
          mainGirdHeight1 == other.mainGirdHeight1 &&
          mainGirdHeight2 == other.mainGirdHeight2 &&
          mainGirdOrientation == other.mainGirdOrientation &&
          colorPrimaryName == other.colorPrimaryName &&
          currentTheme == other.currentTheme &&
          currentLanguage == other.currentLanguage &&
          currentFontFamily == other.currentFontFamily &&
          currentFontSize == other.currentFontSize &&
          enableDragDropSort == other.enableDragDropSort &&
          doubleClick2Activate == other.doubleClick2Activate &&
          autoHideStartup == other.autoHideStartup &&
          hide2TrayWhenClose == other.hide2TrayWhenClose &&
          macosShowInDock == other.macosShowInDock &&
          mainColumnItem == other.mainColumnItem &&
          windowSizeItem == other.windowSizeItem &&
          hideColumnIpInfo == other.hideColumnIpInfo &&
          extraJson == other.extraJson;
}

/// `WebDavItem` DTO. Values are secrets; the UI must not log them.
class WebDavItemDto {
  final String? url;
  final String? userName;
  final String? password;
  final String? dirName;
  final String extraJson;

  const WebDavItemDto({
    this.url,
    this.userName,
    this.password,
    this.dirName,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      userName.hashCode ^
      password.hashCode ^
      dirName.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavItemDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          userName == other.userName &&
          password == other.password &&
          dirName == other.dirName &&
          extraJson == other.extraJson;
}

/// A persisted window geometry row (`WindowSizeItem`).
class WindowSizeItemDto {
  final String typeName;
  final int width;
  final int height;
  final int mainGridHeight1;
  final int mainGridHeight2;

  /// `EGirdOrientation` numeric value (0/1/2).
  final int orientation;
  final String extraJson;

  const WindowSizeItemDto({
    required this.typeName,
    required this.width,
    required this.height,
    required this.mainGridHeight1,
    required this.mainGridHeight2,
    required this.orientation,
    required this.extraJson,
  });

  @override
  int get hashCode =>
      typeName.hashCode ^
      width.hashCode ^
      height.hashCode ^
      mainGridHeight1.hashCode ^
      mainGridHeight2.hashCode ^
      orientation.hashCode ^
      extraJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowSizeItemDto &&
          runtimeType == other.runtimeType &&
          typeName == other.typeName &&
          width == other.width &&
          height == other.height &&
          mainGridHeight1 == other.mainGridHeight1 &&
          mainGridHeight2 == other.mainGridHeight2 &&
          orientation == other.orientation &&
          extraJson == other.extraJson;
}
