// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `action_from_value`, `action_value`, `default_core`, `dto`, `from_ex`, `hub`, `new`, `new`, `open_reserved`, `profile_to_node`, `with_hub`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetHostTestSession`, `SpeedTestHub`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `close`, `download`, `open`, `real_ping`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `apply_speedtest_result_for_test`, `reset_speedtest_for_test`

/// Apply the effective `SpeedTestItem` settings.
SimpleResult speedtestConfigure({
  required int pageSize,
  required int mixedConcurrency,
  required int timeoutSecs,
  required String speedTestUrl,
  required String speedPingTestUrl,
  String? ipapiUrl,
  String? udpTestTarget,
  required int delayIntervalSecs,
}) => RustLib.instance.api.crateApiSpeedtestSpeedtestConfigure(
  pageSize: pageSize,
  mixedConcurrency: mixedConcurrency,
  timeoutSecs: timeoutSecs,
  speedTestUrl: speedTestUrl,
  speedPingTestUrl: speedPingTestUrl,
  ipapiUrl: ipapiUrl,
  udpTestTarget: udpTestTarget,
  delayIntervalSecs: delayIntervalSecs,
);

/// What this build can really do (UDP is disabled, never faked).
SpeedTestSupportDto speedtestSupported() =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestSupported();

/// Start a speedtest job over the selected node ids (empty = all stored nodes).
SpeedTestStartDto speedtestStart({
  required int kind,
  required List<String> indexIds,
}) => RustLib.instance.api.crateApiSpeedtestSpeedtestStart(
  kind: kind,
  indexIds: indexIds,
);

/// Idempotent cancel of a running speedtest job.
SimpleResult speedtestCancel({required String jobId}) =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestCancel(jobId: jobId);

/// All `ProfileExItem` result rows (UI overlay).
List<SpeedTestResultDto> speedtestResults() =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestResults();

/// Number of speedtest jobs still running. The UI polls this to end live
/// refresh without depending on the FRB stream lifecycle.
int speedtestActiveJobs() =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestActiveJobs();

/// `RemoveInvalidServerResult`: delete rows whose delay failed (`-1`).
int speedtestRemoveInvalid() =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestRemoveInvalid();

/// Register a batch stream.
Stream<SpeedTestBatchDto> speedtestSubscribe() =>
    RustLib.instance.api.crateApiSpeedtestSpeedtestSubscribe();

/// One 50-100 ms result batch.
class SpeedTestBatchDto {
  final String jobId;
  final int kind;
  final List<SpeedTestResultDto> results;
  final bool done;
  final bool cancelled;

  const SpeedTestBatchDto({
    required this.jobId,
    required this.kind,
    required this.results,
    required this.done,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      kind.hashCode ^
      results.hashCode ^
      done.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTestBatchDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          kind == other.kind &&
          results == other.results &&
          done == other.done &&
          cancelled == other.cancelled;
}

/// Result row delivered to the UI (`ProfileExItem`).
class SpeedTestResultDto {
  final String indexId;
  final int delay;
  final double speed;
  final String message;
  final String ipInfo;

  const SpeedTestResultDto({
    required this.indexId,
    required this.delay,
    required this.speed,
    required this.message,
    required this.ipInfo,
  });

  @override
  int get hashCode =>
      indexId.hashCode ^
      delay.hashCode ^
      speed.hashCode ^
      message.hashCode ^
      ipInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTestResultDto &&
          runtimeType == other.runtimeType &&
          indexId == other.indexId &&
          delay == other.delay &&
          speed == other.speed &&
          message == other.message &&
          ipInfo == other.ipInfo;
}

/// Result of `speedtest_start`.
class SpeedTestStartDto {
  final bool ok;
  final String? jobId;
  final int total;
  final ErrorDto? error;

  const SpeedTestStartDto({
    required this.ok,
    this.jobId,
    required this.total,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ jobId.hashCode ^ total.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTestStartDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          jobId == other.jobId &&
          total == other.total &&
          error == other.error;
}

/// Which test actions the current build can really perform.
class SpeedTestSupportDto {
  final bool tcpPing;
  final bool realPing;
  final bool download;
  final bool mixed;
  final bool fastRealPing;

  /// UDP test is not implemented in the restricted scope; the UI disables it.
  final bool udp;

  const SpeedTestSupportDto({
    required this.tcpPing,
    required this.realPing,
    required this.download,
    required this.mixed,
    required this.fastRealPing,
    required this.udp,
  });

  @override
  int get hashCode =>
      tcpPing.hashCode ^
      realPing.hashCode ^
      download.hashCode ^
      mixed.hashCode ^
      fastRealPing.hashCode ^
      udp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTestSupportDto &&
          runtimeType == other.runtimeType &&
          tcpPing == other.tcpPing &&
          realPing == other.realPing &&
          download == other.download &&
          mixed == other.mixed &&
          fastRealPing == other.fastRealPing &&
          udp == other.udp;
}
