// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `commit_import_fail_next`, `content_stem`, `dto_to_sub`, `finish_sub_job`, `load_outbound_json`, `materialize_custom_configs`, `parse_error_result`, `parse_import`, `parse_issue_dto`, `register_sub_job`, `remember_sub_report`, `render_export`, `spawn_sub_update`, `sub_jobs`, `sub_reports`, `sub_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ParsedImport`

/// `list_sub_items` — every subscription ordered by `Sort`.
SubsPageDto listSubItems() => RustLib.instance.api.crateApiSubsListSubItems();

/// `get_sub_item` — one subscription by id.
SubItemDto? getSubItem({required String id}) =>
    RustLib.instance.api.crateApiSubsGetSubItem(id: id);

/// `save_sub_item` — validate + persist; assigns id/sort when new.
SubItemDtoResult saveSubItem({required SubItemDto item}) =>
    RustLib.instance.api.crateApiSubsSaveSubItem(item: item);

/// `delete_sub_items` — delete a selection.
DeleteSubsResult deleteSubItems({required List<String> ids}) =>
    RustLib.instance.api.crateApiSubsDeleteSubItems(ids: ids);

/// `set_sub_enabled` — enable/disable one subscription.
SubItemDtoResult setSubEnabled({required String id, required bool enabled}) =>
    RustLib.instance.api.crateApiSubsSetSubEnabled(id: id, enabled: enabled);

/// `reorder_sub_items` — persist a new display order.
SimpleResult reorderSubItems({required List<String> ids}) =>
    RustLib.instance.api.crateApiSubsReorderSubItems(ids: ids);

/// `validate_sub_item` — UI-side pre-check without persisting.
SimpleResult validateSubItem({required SubItemDto item}) =>
    RustLib.instance.api.crateApiSubsValidateSubItem(item: item);

/// `set_local_proxy_port` — record the running session's mixed/socks port.
void setLocalProxyPort({int? port}) =>
    RustLib.instance.api.crateApiSubsSetLocalProxyPort(port: port);

/// `sub_update_report` — the terminal per-group report JSON for `job_id`.
///
/// Returns `None` for an unknown/never-run id. Implemented here but absent
/// from the checked-in `frb_generated` bindings; the bridge currently reaches
/// the report through the job stage key. Regenerating FRB wires this getter
/// directly, replacing the stage-key carrier.
String? subUpdateReport({required String jobId}) =>
    RustLib.instance.api.crateApiSubsSubUpdateReport(jobId: jobId);

/// `update_subscriptions` — the F-SUB-003 pipeline.
///
/// `sub_ids` empty means every subscription; `via_proxy` uses the recorded
/// local session port. When `via_proxy` is requested but no local proxy
/// endpoint is known, a structured `E_PROXY_UNAVAILABLE` error is returned
/// and no direct download is attempted.
///
/// On acceptance the real `job_id` is returned *before* any network work
/// starts (SET-03): the refresh runs on a worker thread, the UI binds its
/// progress (`job_view`) and cancellation (`cancel_job`) to that id, and the
/// final report is pushed as a `subscriptions_updated` control event. A
/// cancellation never replaces the old group, reports a fake success or
/// leaves a half-written candidate set (the pipeline is candidate-first).
Future<SubUpdateResult> updateSubscriptions({
  required List<String> subIds,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiSubsUpdateSubscriptions(
  subIds: subIds,
  viaProxy: viaProxy,
);

/// `update_subscription` — refresh a single subscription.
Future<SubUpdateResult> updateSubscription({
  required String subId,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiSubsUpdateSubscription(
  subId: subId,
  viaProxy: viaProxy,
);

/// `start_sub_scheduler` — start the periodic update loop (idempotent).
SimpleResult startSubScheduler() =>
    RustLib.instance.api.crateApiSubsStartSubScheduler();

/// `stop_sub_scheduler` — graceful stop; never holds up process exit.
SimpleResult stopSubScheduler() =>
    RustLib.instance.api.crateApiSubsStopSubScheduler();

/// `sub_scheduler_running` — diagnostics.
bool subSchedulerRunning() =>
    RustLib.instance.api.crateApiSubsSubSchedulerRunning();

/// `job_view` — current state of any job (including subscription updates).
JobDto? jobView({required String jobId}) =>
    RustLib.instance.api.crateApiSubsJobView(jobId: jobId);

/// `preview_import_text` — parse/preview without persisting (R4-16).
///
/// Decodes and normalises the payload but never touches SQLite and never writes
/// config files; the caller previews the result and then commits through
/// [`import_from_text`] (or a future single-transaction `commit_import_text`).
/// The binding is pending the next FRB regeneration.
ImportResult previewImportText({required String text, String? subid}) => RustLib
    .instance
    .api
    .crateApiSubsPreviewImportText(text: text, subid: subid);

/// `import_from_text` — parse share URIs / base64 / inner URIs, then commit.
///
/// `subid` non-empty attaches the imported nodes to that subscription and
/// inserts them in one `replace_sub_profiles(..., remove_existing: false)`
/// transaction; `deduplicate` applies the upstream `KeepOlderDedupl` collapse.
/// Returns the imported profiles plus located per-line errors
/// (F-IMPORT-001/002/005).
Future<ImportResult> importFromText({
  required String text,
  String? subid,
  required bool deduplicate,
}) => RustLib.instance.api.crateApiSubsImportFromText(
  text: text,
  subid: subid,
  deduplicate: deduplicate,
);

/// `commit_import_text` — single-transaction persistence of an already-parsed
/// import (R4-16, SP-14). The input is the DTO list produced by
/// [`preview_import_text`] plus the target `subid`; every profile is written in
/// one `replace_sub_profiles` transaction (including the no-group case, where
/// `subid` is `None`/empty) so there is no per-line fallback and no second
/// parse. Semantics match `parse_import`: `IsSub = false`, ids assigned, subid
/// stamped; per-line parse issues are reported by the preview, not here.
///
/// SP-14: `Custom`/`Outbound` payloads parked under `extra["RawConfig"]` by the
/// pure preview are staged to content-addressed files *before* the DB
/// transaction; a DB failure deletes files staged by this commit so no orphan
/// survives. `preview_token`/`expected_revision`/`mutation_id` binding lives in
/// the Dart preview/commit seam plus `application::import_batch` until the
/// generated `CommitImportRequest` FRB wiring lands (integrator-owned).
ImportResult commitImportText({
  required List<ProfileDto> profiles,
  String? subid,
}) => RustLib.instance.api.crateApiSubsCommitImportText(
  profiles: profiles,
  subid: subid,
);

/// `parse_share_uri` — resolve a single line without persisting it.
UriParseResult parseShareUri({required String line}) =>
    RustLib.instance.api.crateApiSubsParseShareUri(line: line);

/// Render the selected profiles as share URIs / base64 / inner URIs.
///
/// Returns the text to place on the clipboard or in a file. `kind` is one of
/// `share`, `base64`, `inner`.
Future<ShareExportResult> exportProfiles({
  required List<String> ids,
  required String kind,
}) => RustLib.instance.api.crateApiSubsExportProfiles(ids: ids, kind: kind);

/// `write_export_file` — write export text to a file (URI text only; kernel
/// config export is deferred to T10+).
SimpleResult writeExportFile({required String path, required String text}) =>
    RustLib.instance.api.crateApiSubsWriteExportFile(path: path, text: text);
