// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_sub`, `finish_sub_job`, `load_outbound_json`, `materialize_custom_configs`, `register_sub_job`, `render_export`, `sanitize_index_id`, `spawn_sub_update`, `sub_jobs`, `sub_to_dto`

/// `list_sub_items` — every subscription ordered by `Sort`.
SubsPageDto listSubItems() => RustLib.instance.api.crateApiSubsListSubItems();

/// `get_sub_item` — one subscription by id.
SubItemDto? getSubItem({required String id}) =>
    RustLib.instance.api.crateApiSubsGetSubItem(id: id);

/// `save_sub_item` — validate + persist; assigns id/sort when new.
SubItemDtoResult saveSubItem({required SubItemDto item}) =>
    RustLib.instance.api.crateApiSubsSaveSubItem(item: item);

/// `delete_sub_items` — delete a selection.
DeleteSubsResult deleteSubItems({required List<String> ids}) =>
    RustLib.instance.api.crateApiSubsDeleteSubItems(ids: ids);

/// `set_sub_enabled` — enable/disable one subscription.
SubItemDtoResult setSubEnabled({required String id, required bool enabled}) =>
    RustLib.instance.api.crateApiSubsSetSubEnabled(id: id, enabled: enabled);

/// `reorder_sub_items` — persist a new display order.
SimpleResult reorderSubItems({required List<String> ids}) =>
    RustLib.instance.api.crateApiSubsReorderSubItems(ids: ids);

/// `validate_sub_item` — UI-side pre-check without persisting.
SimpleResult validateSubItem({required SubItemDto item}) =>
    RustLib.instance.api.crateApiSubsValidateSubItem(item: item);

/// `set_local_proxy_port` — record the running session's mixed/socks port.
void setLocalProxyPort({int? port}) =>
    RustLib.instance.api.crateApiSubsSetLocalProxyPort(port: port);

/// `update_subscriptions` — the F-SUB-003 pipeline.
///
/// `sub_ids` empty means every subscription; `via_proxy` uses the recorded
/// local session port. When `via_proxy` is requested but no local proxy
/// endpoint is known, a structured `E_PROXY_UNAVAILABLE` error is returned
/// and no direct download is attempted.
///
/// On acceptance the real `job_id` is returned *before* any network work
/// starts (SET-03): the refresh runs on a worker thread, the UI binds its
/// progress (`job_view`) and cancellation (`cancel_job`) to that id, and the
/// final report is pushed as a `subscriptions_updated` control event. A
/// cancellation never replaces the old group, reports a fake success or
/// leaves a half-written candidate set (the pipeline is candidate-first).
Future<SubUpdateResult> updateSubscriptions({
  required List<String> subIds,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiSubsUpdateSubscriptions(
  subIds: subIds,
  viaProxy: viaProxy,
);

/// `update_subscription` — refresh a single subscription.
Future<SubUpdateResult> updateSubscription({
  required String subId,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiSubsUpdateSubscription(
  subId: subId,
  viaProxy: viaProxy,
);

/// `start_sub_scheduler` — start the periodic update loop (idempotent).
SimpleResult startSubScheduler() =>
    RustLib.instance.api.crateApiSubsStartSubScheduler();

/// `stop_sub_scheduler` — graceful stop; never holds up process exit.
SimpleResult stopSubScheduler() =>
    RustLib.instance.api.crateApiSubsStopSubScheduler();

/// `sub_scheduler_running` — diagnostics.
bool subSchedulerRunning() =>
    RustLib.instance.api.crateApiSubsSubSchedulerRunning();

/// `job_view` — current state of any job (including subscription updates).
JobDto? jobView({required String jobId}) =>
    RustLib.instance.api.crateApiSubsJobView(jobId: jobId);

/// `import_from_text` — parse share URIs / base64 / inner URIs from text.
///
/// `subid` non-empty attaches the imported nodes to that subscription;
/// `deduplicate` applies the upstream `KeepOlderDedupl` collapse. Returns the
/// imported profiles plus located per-line errors (F-IMPORT-001/002/005).
Future<ImportResult> importFromText({
  required String text,
  String? subid,
  required bool deduplicate,
}) => RustLib.instance.api.crateApiSubsImportFromText(
  text: text,
  subid: subid,
  deduplicate: deduplicate,
);

/// `parse_share_uri` — resolve a single line without persisting it.
UriParseResult parseShareUri({required String line}) =>
    RustLib.instance.api.crateApiSubsParseShareUri(line: line);

/// Render the selected profiles as share URIs / base64 / inner URIs.
///
/// Returns the text to place on the clipboard or in a file. `kind` is one of
/// `share`, `base64`, `inner`.
Future<ShareExportResult> exportProfiles({
  required List<String> ids,
  required String kind,
}) => RustLib.instance.api.crateApiSubsExportProfiles(ids: ids, kind: kind);

/// `write_export_file` — write export text to a file (URI text only; kernel
/// config export is deferred to T10+).
SimpleResult writeExportFile({required String path, required String text}) =>
    RustLib.instance.api.crateApiSubsWriteExportFile(path: path, text: text);
