// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contract.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_install_root`, `app_update_spec_inner`, `backup_service`, `core_update_dto`, `cores_root`, `dto_to_webdav`, `last_update_flags`, `manifest_dto`, `now_epoch`, `open_path`, `proxy_unavailable`, `remember_update_flags`, `update_flags`, `update_service`, `update_target_dto`, `webdav_client`, `webdav_dto`, `work_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UpdateFlags`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// `backup_local` — write a versioned bundle under `dest_root`. Async: copies
/// files and hashes the database, so it must not run on the UI isolate.
Future<BackupResultDto> t16BackupLocal({required String destRoot}) =>
    RustLib.instance.api.crateApiT16T16BackupLocal(destRoot: destRoot);

/// `backup_list` — bundles directly under `parent`. Async: directory scan.
Future<BackupListDto> t16BackupList({required String parent}) =>
    RustLib.instance.api.crateApiT16T16BackupList(parent: parent);

/// `backup_verify` — verify a bundle without writing anything. Async: reads the
/// whole bundle and re-hashes it.
Future<VerificationDto> t16BackupVerify({required String bundleDir}) =>
    RustLib.instance.api.crateApiT16T16BackupVerify(bundleDir: bundleDir);

/// `backup_restore` — verify then restore a bundle. Async: DB lifecycle swap +
/// file I/O.
Future<RestoreResultDto> t16BackupRestore({required String bundleDir}) =>
    RustLib.instance.api.crateApiT16T16BackupRestore(bundleDir: bundleDir);

/// `backup_recognize` — recognise an upstream or project archive. Async: reads
/// the archive directory/central directory.
Future<RecognitionDto> t16BackupRecognize({required String path}) =>
    RustLib.instance.api.crateApiT16T16BackupRecognize(path: path);

/// `backup_import_upstream` — restore a directory/ZIP via the T04 candidate
/// flow with replace semantics (the upstream `guiNDB.db` becomes the database).
/// Async: DB lifecycle swap + file I/O.
Future<ImportSummaryDto> t16BackupImportUpstream({required String path}) =>
    RustLib.instance.api.crateApiT16T16BackupImportUpstream(path: path);

/// `backup_import_upstream_merge` — the explicitly named migration/merge
/// import that appends the source rows to the live database (R3-SET-02).
///
/// Registered as an independent entry; the checked-in `frb_generated` bindings
/// are not regenerated, so the UI restore path stays on
/// [`t16_backup_import_upstream`] (replace).
ImportSummaryDto t16BackupImportUpstreamMerge({required String path}) =>
    RustLib.instance.api.crateApiT16T16BackupImportUpstreamMerge(path: path);

/// `webdav_config_get` — the persisted `WebDavItem` (secret not logged).
WebDavConfigResultDto t16WebdavConfigGet() =>
    RustLib.instance.api.crateApiT16T16WebdavConfigGet();

/// `webdav_config_save` — persist the `WebDavItem` group.
WebDavConfigResultDto t16WebdavConfigSave({
  required WebDavConfigDto cfg,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiT16T16WebdavConfigSave(
  cfg: cfg,
  expectedRevision: expectedRevision,
);

/// `webdav_check` — connect, creating the default directory when missing.
Future<WebDavCheckDto> t16WebdavCheck({required WebDavConfigDto cfg}) =>
    RustLib.instance.api.crateApiT16T16WebdavCheck(cfg: cfg);

/// `webdav_list` — list the remote backup directory.
Future<WebDavListDto> t16WebdavList({required WebDavConfigDto cfg}) =>
    RustLib.instance.api.crateApiT16T16WebdavList(cfg: cfg);

/// `webdav_backup` — pack a local bundle and PUT it as `backup.zip`.
Future<WebDavOpDto> t16WebdavBackup({required WebDavConfigDto cfg}) =>
    RustLib.instance.api.crateApiT16T16WebdavBackup(cfg: cfg);

/// `webdav_restore` — GET `backup.zip`, extract and restore it.
Future<RestoreResultDto> t16WebdavRestore({required WebDavConfigDto cfg}) =>
    RustLib.instance.api.crateApiT16T16WebdavRestore(cfg: cfg);

/// `update_targets` — the built-in target list for the UI (disabled targets
/// carry a note and must be rendered disabled).
List<UpdateTargetDto> t16UpdateTargets() =>
    RustLib.instance.api.crateApiT16T16UpdateTargets();

/// `check_updates` — check the selected cores. Upstream contract: `null`
/// means every built-in target, an empty list means none (the user unchecked
/// every row) and is never expanded back to all.
Future<UpdateReportDto> t16CheckUpdates({
  List<String>? cores,
  required bool prerelease,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiT16T16CheckUpdates(
  cores: cores,
  prerelease: prerelease,
  viaProxy: viaProxy,
);

/// `apply_core_update` — download+verify+install every selected target that has
/// a newer version. Runs only inside the managed cores directory.
Future<ApplyCoreResultDto> t16ApplyCoreUpdate({
  required List<String> cores,
  required bool prerelease,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiT16T16ApplyCoreUpdate(
  cores: cores,
  prerelease: prerelease,
  viaProxy: viaProxy,
);

/// `cleanup_logs_tmp` — manual trigger of the 1h Test / 7d log+temp cleanup.
CleanupResultDto t16CleanupLogsTmp() =>
    RustLib.instance.api.crateApiT16T16CleanupLogsTmp();

/// `open_config_dir` — reveal the data directory in the file manager.
SimpleResult t16OpenConfigDir() =>
    RustLib.instance.api.crateApiT16T16OpenConfigDir();

/// `get_core_versions` — read-only probe of installed core directories.
CoreVersionsDto t16GetCoreVersions() =>
    RustLib.instance.api.crateApiT16T16GetCoreVersions();

/// `apply_app_update_spec_with_flags` — parameterized self-update staging
/// (R4-29): the `prerelease` / `via_proxy` selection is passed explicitly
/// instead of being read from a process-global "last check" slot.
Future<ExternalSpecDto> t16ApplyAppUpdateSpecWithFlags({
  required bool prerelease,
  required bool viaProxy,
}) => RustLib.instance.api.crateApiT16T16ApplyAppUpdateSpecWithFlags(
  prerelease: prerelease,
  viaProxy: viaProxy,
);

/// Backward-compatible no-arg entry point retained until the FRB bindings are
/// regenerated; it reuses the last recorded check selection (R4-29 gap).
Future<ExternalSpecDto> t16ApplyAppUpdateSpec() =>
    RustLib.instance.api.crateApiT16T16ApplyAppUpdateSpec();

/// `rollback_app_upgrade` — restore the `app.previous` payload kept by the last
/// external replacement (R4-29). No network; file effects stay inside the
/// install root.
AppRollbackResultDto t16RollbackAppUpgrade() =>
    RustLib.instance.api.crateApiT16T16RollbackAppUpgrade();

/// `app_restart_command` — the relaunch command the external upgrade runner
/// executes after a replacement (R4-29). Constructed only; never spawned here.
AppRestartCommandDto t16AppRestartCommand() =>
    RustLib.instance.api.crateApiT16T16AppRestartCommand();
