// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mirrors.dart';
import 'api/profiles.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiProfilesInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1538096185;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'bridge_api',
        ioDirectory: '../../crates/bridge_api/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  UiEventAck crateApiProfilesEchoUiEvent({
    required BigInt seq,
    required String kind,
  });

  List<ProfileSummary> crateApiProfilesFetchProfilesPage({
    required int offset,
    required int limit,
  });

  List<ProfileSummary> crateApiProfilesGenerateProfiles({required int count});

  Future<void> crateApiProfilesInitApp();

  int crateApiProfilesPingProfile({required String id});

  ProfileSummary? crateApiProfilesProfileAt({required int index});

  Stream<ProgressEvent> crateApiProfilesProgressStream({required int count});

  int crateApiProfilesRustProfileCount();

  Future<BigInt> crateApiProfilesSimulateBlocking({required BigInt ms});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  UiEventAck crateApiProfilesEchoUiEvent({
    required BigInt seq,
    required String kind,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seq, serializer);
          sse_encode_String(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ui_event_ack,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesEchoUiEventConstMeta,
        argValues: [seq, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesEchoUiEventConstMeta =>
      const TaskConstMeta(
        debugName: "echo_ui_event",
        argNames: ["seq", "kind"],
      );

  @override
  List<ProfileSummary> crateApiProfilesFetchProfilesPage({
    required int offset,
    required int limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesFetchProfilesPageConstMeta,
        argValues: [offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesFetchProfilesPageConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_profiles_page",
        argNames: ["offset", "limit"],
      );

  @override
  List<ProfileSummary> crateApiProfilesGenerateProfiles({required int count}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(count, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesGenerateProfilesConstMeta,
        argValues: [count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesGenerateProfilesConstMeta =>
      const TaskConstMeta(debugName: "generate_profiles", argNames: ["count"]);

  @override
  Future<void> crateApiProfilesInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  int crateApiProfilesPingProfile({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesPingProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesPingProfileConstMeta =>
      const TaskConstMeta(debugName: "ping_profile", argNames: ["id"]);

  @override
  ProfileSummary? crateApiProfilesProfileAt({required int index}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_profile_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesProfileAtConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesProfileAtConstMeta =>
      const TaskConstMeta(debugName: "profile_at", argNames: ["index"]);

  @override
  Stream<ProgressEvent> crateApiProfilesProgressStream({required int count}) {
    final sink = RustStreamSink<ProgressEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(count, serializer);
            sse_encode_StreamSink_progress_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiProfilesProgressStreamConstMeta,
          argValues: [count, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiProfilesProgressStreamConstMeta =>
      const TaskConstMeta(
        debugName: "progress_stream",
        argNames: ["count", "sink"],
      );

  @override
  int crateApiProfilesRustProfileCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesRustProfileCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesRustProfileCountConstMeta =>
      const TaskConstMeta(debugName: "rust_profile_count", argNames: []);

  @override
  Future<BigInt> crateApiProfilesSimulateBlocking({required BigInt ms}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(ms, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfilesSimulateBlockingConstMeta,
        argValues: [ms],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesSimulateBlockingConstMeta =>
      const TaskConstMeta(debugName: "simulate_blocking", argNames: ["ms"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ProfileSummary dco_decode_box_autoadd_profile_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile_summary(raw);
  }

  @protected
  ConfigType dco_decode_config_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConfigType.values[raw as int];
  }

  @protected
  CoreType dco_decode_core_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileSummary> dco_decode_list_profile_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_summary).toList();
  }

  @protected
  ProfileSummary? dco_decode_opt_box_autoadd_profile_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_profile_summary(raw);
  }

  @protected
  ProfileSummary dco_decode_profile_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return ProfileSummary(
      id: dco_decode_String(arr[0]),
      configType: dco_decode_config_type(arr[1]),
      remarks: dco_decode_String(arr[2]),
      address: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      network: dco_decode_String(arr[5]),
      streamSecurity: dco_decode_String(arr[6]),
      subRemarks: dco_decode_String(arr[7]),
      delay: dco_decode_i_32(arr[8]),
      speed: dco_decode_String(arr[9]),
      todayUp: dco_decode_u_64(arr[10]),
      ipInfo: dco_decode_String(arr[11]),
      todayDown: dco_decode_u_64(arr[12]),
      totalUp: dco_decode_u_64(arr[13]),
      totalDown: dco_decode_u_64(arr[14]),
      coreType: dco_decode_core_type(arr[15]),
    );
  }

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProgressEvent(
      seq: dco_decode_u_32(arr[0]),
      done: dco_decode_u_32(arr[1]),
      total: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiEventAck dco_decode_ui_event_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return UiEventAck(
      seq: dco_decode_u_64(arr[0]),
      kind: dco_decode_String(arr[1]),
      rustProfileCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ProfileSummary sse_decode_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile_summary(deserializer));
  }

  @protected
  ConfigType sse_decode_config_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConfigType.values[inner];
  }

  @protected
  CoreType sse_decode_core_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CoreType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileSummary> sse_decode_list_profile_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_summary(deserializer));
    }
    return ans_;
  }

  @protected
  ProfileSummary? sse_decode_opt_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_profile_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileSummary sse_decode_profile_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_configType = sse_decode_config_type(deserializer);
    var var_remarks = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_network = sse_decode_String(deserializer);
    var var_streamSecurity = sse_decode_String(deserializer);
    var var_subRemarks = sse_decode_String(deserializer);
    var var_delay = sse_decode_i_32(deserializer);
    var var_speed = sse_decode_String(deserializer);
    var var_todayUp = sse_decode_u_64(deserializer);
    var var_ipInfo = sse_decode_String(deserializer);
    var var_todayDown = sse_decode_u_64(deserializer);
    var var_totalUp = sse_decode_u_64(deserializer);
    var var_totalDown = sse_decode_u_64(deserializer);
    var var_coreType = sse_decode_core_type(deserializer);
    return ProfileSummary(
      id: var_id,
      configType: var_configType,
      remarks: var_remarks,
      address: var_address,
      port: var_port,
      network: var_network,
      streamSecurity: var_streamSecurity,
      subRemarks: var_subRemarks,
      delay: var_delay,
      speed: var_speed,
      todayUp: var_todayUp,
      ipInfo: var_ipInfo,
      todayDown: var_todayDown,
      totalUp: var_totalUp,
      totalDown: var_totalDown,
      coreType: var_coreType,
    );
  }

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seq = sse_decode_u_32(deserializer);
    var var_done = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    return ProgressEvent(seq: var_seq, done: var_done, total: var_total);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiEventAck sse_decode_ui_event_ack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seq = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_rustProfileCount = sse_decode_u_32(deserializer);
    return UiEventAck(
      seq: var_seq,
      kind: var_kind,
      rustProfileCount: var_rustProfileCount,
    );
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile_summary(self, serializer);
  }

  @protected
  void sse_encode_config_type(ConfigType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_core_type(CoreType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_summary(
    List<ProfileSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_profile_summary(
    ProfileSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_profile_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_config_type(self.configType, serializer);
    sse_encode_String(self.remarks, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.network, serializer);
    sse_encode_String(self.streamSecurity, serializer);
    sse_encode_String(self.subRemarks, serializer);
    sse_encode_i_32(self.delay, serializer);
    sse_encode_String(self.speed, serializer);
    sse_encode_u_64(self.todayUp, serializer);
    sse_encode_String(self.ipInfo, serializer);
    sse_encode_u_64(self.todayDown, serializer);
    sse_encode_u_64(self.totalUp, serializer);
    sse_encode_u_64(self.totalDown, serializer);
    sse_encode_core_type(self.coreType, serializer);
  }

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.seq, serializer);
    sse_encode_u_32(self.done, serializer);
    sse_encode_u_32(self.total, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_event_ack(UiEventAck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.seq, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_u_32(self.rustProfileCount, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
