// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/contract.dart';
import 'api/engine.dart';
import 'api/groups.dart';
import 'api/mirrors.dart';
import 'api/profiles.dart';
import 'api/settings.dart';
import 'api/subs.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EventEnvelopeDto> dco_decode_StreamSink_event_envelope_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApplyRuntimeResult dco_decode_apply_runtime_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CoreType dco_decode_box_autoadd_core_type(dynamic raw);

  @protected
  ErrorDto dco_decode_box_autoadd_error_dto(dynamic raw);

  @protected
  Fragment4RayItemDto dco_decode_box_autoadd_fragment_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  FullConfigTemplateDto dco_decode_box_autoadd_full_config_template_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  JobDto dco_decode_box_autoadd_job_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_box_autoadd_profile_dto(dynamic raw);

  @protected
  ProfileFilterDto dco_decode_box_autoadd_profile_filter_dto(dynamic raw);

  @protected
  ProfileSummary dco_decode_box_autoadd_profile_summary(dynamic raw);

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw);

  @protected
  SubItemDto dco_decode_box_autoadd_sub_item_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  CancelOutcome dco_decode_cancel_outcome(dynamic raw);

  @protected
  CancelResult dco_decode_cancel_result(dynamic raw);

  @protected
  CapabilityDto dco_decode_capability_dto(dynamic raw);

  @protected
  CheckUpdateItemDto dco_decode_check_update_item_dto(dynamic raw);

  @protected
  ClashUiItemDto dco_decode_clash_ui_item_dto(dynamic raw);

  @protected
  ColumnItemDto dco_decode_column_item_dto(dynamic raw);

  @protected
  ConfigType dco_decode_config_type(dynamic raw);

  @protected
  ConstItemDto dco_decode_const_item_dto(dynamic raw);

  @protected
  CopyProfilesResult dco_decode_copy_profiles_result(dynamic raw);

  @protected
  CoreBasicItemDto dco_decode_core_basic_item_dto(dynamic raw);

  @protected
  CoreType dco_decode_core_type(dynamic raw);

  @protected
  CoreTypeBindingDto dco_decode_core_type_binding_dto(dynamic raw);

  @protected
  DeleteProfilesResult dco_decode_delete_profiles_result(dynamic raw);

  @protected
  DeleteSubsResult dco_decode_delete_subs_result(dynamic raw);

  @protected
  ErrorDto dco_decode_error_dto(dynamic raw);

  @protected
  EventEnvelopeDto dco_decode_event_envelope_dto(dynamic raw);

  @protected
  Fragment4RayItemDto dco_decode_fragment_4_ray_item_dto(dynamic raw);

  @protected
  FullConfigTemplateDto dco_decode_full_config_template_dto(dynamic raw);

  @protected
  GlobalHotkeyDto dco_decode_global_hotkey_dto(dynamic raw);

  @protected
  GroupGenResult dco_decode_group_gen_result(dynamic raw);

  @protected
  GrpcItemDto dco_decode_grpc_item_dto(dynamic raw);

  @protected
  GuiItemDto dco_decode_gui_item_dto(dynamic raw);

  @protected
  HappyEyeballs4RayItemDto dco_decode_happy_eyeballs_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  HysteriaItemDto dco_decode_hysteria_item_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportResult dco_decode_import_result(dynamic raw);

  @protected
  InboundListenerDto dco_decode_inbound_listener_dto(dynamic raw);

  @protected
  JobDto dco_decode_job_dto(dynamic raw);

  @protected
  JobState dco_decode_job_state(dynamic raw);

  @protected
  KcpItemDto dco_decode_kcp_item_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CapabilityDto> dco_decode_list_capability_dto(dynamic raw);

  @protected
  List<ColumnItemDto> dco_decode_list_column_item_dto(dynamic raw);

  @protected
  List<ConfigType> dco_decode_list_config_type(dynamic raw);

  @protected
  List<CoreTypeBindingDto> dco_decode_list_core_type_binding_dto(dynamic raw);

  @protected
  List<FullConfigTemplateDto> dco_decode_list_full_config_template_dto(
    dynamic raw,
  );

  @protected
  List<GlobalHotkeyDto> dco_decode_list_global_hotkey_dto(dynamic raw);

  @protected
  List<InboundListenerDto> dco_decode_list_inbound_listener_dto(dynamic raw);

  @protected
  List<JobDto> dco_decode_list_job_dto(dynamic raw);

  @protected
  List<ParseIssueDto> dco_decode_list_parse_issue_dto(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileDto> dco_decode_list_profile_dto(dynamic raw);

  @protected
  List<ProfileSummary> dco_decode_list_profile_summary(dynamic raw);

  @protected
  List<SettingsChangeDto> dco_decode_list_settings_change_dto(dynamic raw);

  @protected
  List<SubItemDto> dco_decode_list_sub_item_dto(dynamic raw);

  @protected
  List<SubUpdateEntryDto> dco_decode_list_sub_update_entry_dto(dynamic raw);

  @protected
  List<WindowSizeItemDto> dco_decode_list_window_size_item_dto(dynamic raw);

  @protected
  MsgUiItemDto dco_decode_msg_ui_item_dto(dynamic raw);

  @protected
  Mux4RayItemDto dco_decode_mux_4_ray_item_dto(dynamic raw);

  @protected
  Mux4SboxItemDto dco_decode_mux_4_sbox_item_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CoreType? dco_decode_opt_box_autoadd_core_type(dynamic raw);

  @protected
  ErrorDto? dco_decode_opt_box_autoadd_error_dto(dynamic raw);

  @protected
  Fragment4RayItemDto? dco_decode_opt_box_autoadd_fragment_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  FullConfigTemplateDto? dco_decode_opt_box_autoadd_full_config_template_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  JobDto? dco_decode_opt_box_autoadd_job_dto(dynamic raw);

  @protected
  ProfileDto? dco_decode_opt_box_autoadd_profile_dto(dynamic raw);

  @protected
  ProfileSummary? dco_decode_opt_box_autoadd_profile_summary(dynamic raw);

  @protected
  SettingsDto? dco_decode_opt_box_autoadd_settings_dto(dynamic raw);

  @protected
  SubItemDto? dco_decode_opt_box_autoadd_sub_item_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<CoreTypeBindingDto>? dco_decode_opt_list_core_type_binding_dto(
    dynamic raw,
  );

  @protected
  ParseIssueDto dco_decode_parse_issue_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw);

  @protected
  ProfileFilterDto dco_decode_profile_filter_dto(dynamic raw);

  @protected
  ProfilePageDto dco_decode_profile_page_dto(dynamic raw);

  @protected
  ProfileSortDto dco_decode_profile_sort_dto(dynamic raw);

  @protected
  ProfileSummary dco_decode_profile_summary(dynamic raw);

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw);

  @protected
  ProtocolExtraDto dco_decode_protocol_extra_dto(dynamic raw);

  @protected
  RecoveryDto dco_decode_recovery_dto(dynamic raw);

  @protected
  RevisionState dco_decode_revision_state(dynamic raw);

  @protected
  RoutingBasicItemDto dco_decode_routing_basic_item_dto(dynamic raw);

  @protected
  RuntimeState dco_decode_runtime_state(dynamic raw);

  @protected
  SaveProfileResult dco_decode_save_profile_result(dynamic raw);

  @protected
  SaveSettingsResult dco_decode_save_settings_result(dynamic raw);

  @protected
  SecurityDto dco_decode_security_dto(dynamic raw);

  @protected
  SettingsChangeDto dco_decode_settings_change_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  SettingsLoadDto dco_decode_settings_load_dto(dynamic raw);

  @protected
  ShareExportResult dco_decode_share_export_result(dynamic raw);

  @protected
  SimpleDnsItemDto dco_decode_simple_dns_item_dto(dynamic raw);

  @protected
  SimpleResult dco_decode_simple_result(dynamic raw);

  @protected
  SnapshotDto dco_decode_snapshot_dto(dynamic raw);

  @protected
  SpeedTestItemDto dco_decode_speed_test_item_dto(dynamic raw);

  @protected
  StopRuntimeResult dco_decode_stop_runtime_result(dynamic raw);

  @protected
  SubItemDto dco_decode_sub_item_dto(dynamic raw);

  @protected
  SubItemDtoResult dco_decode_sub_item_dto_result(dynamic raw);

  @protected
  SubUpdateEntryDto dco_decode_sub_update_entry_dto(dynamic raw);

  @protected
  SubUpdateResult dco_decode_sub_update_result(dynamic raw);

  @protected
  SubsPageDto dco_decode_subs_page_dto(dynamic raw);

  @protected
  SystemProxyItemDto dco_decode_system_proxy_item_dto(dynamic raw);

  @protected
  TemplateDtoResult dco_decode_template_dto_result(dynamic raw);

  @protected
  TemplatesPageDto dco_decode_templates_page_dto(dynamic raw);

  @protected
  TransportExtraDto dco_decode_transport_extra_dto(dynamic raw);

  @protected
  TunModeItemDto dco_decode_tun_mode_item_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiEventAck dco_decode_ui_event_ack(dynamic raw);

  @protected
  UiItemDto dco_decode_ui_item_dto(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UriParseResult dco_decode_uri_parse_result(dynamic raw);

  @protected
  WebDavItemDto dco_decode_web_dav_item_dto(dynamic raw);

  @protected
  WindowSizeItemDto dco_decode_window_size_item_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EventEnvelopeDto> sse_decode_StreamSink_event_envelope_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApplyRuntimeResult sse_decode_apply_runtime_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CoreType sse_decode_box_autoadd_core_type(SseDeserializer deserializer);

  @protected
  ErrorDto sse_decode_box_autoadd_error_dto(SseDeserializer deserializer);

  @protected
  Fragment4RayItemDto sse_decode_box_autoadd_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto sse_decode_box_autoadd_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JobDto sse_decode_box_autoadd_job_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_box_autoadd_profile_dto(SseDeserializer deserializer);

  @protected
  ProfileFilterDto sse_decode_box_autoadd_profile_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProfileSummary sse_decode_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(SseDeserializer deserializer);

  @protected
  SubItemDto sse_decode_box_autoadd_sub_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  CancelOutcome sse_decode_cancel_outcome(SseDeserializer deserializer);

  @protected
  CancelResult sse_decode_cancel_result(SseDeserializer deserializer);

  @protected
  CapabilityDto sse_decode_capability_dto(SseDeserializer deserializer);

  @protected
  CheckUpdateItemDto sse_decode_check_update_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClashUiItemDto sse_decode_clash_ui_item_dto(SseDeserializer deserializer);

  @protected
  ColumnItemDto sse_decode_column_item_dto(SseDeserializer deserializer);

  @protected
  ConfigType sse_decode_config_type(SseDeserializer deserializer);

  @protected
  ConstItemDto sse_decode_const_item_dto(SseDeserializer deserializer);

  @protected
  CopyProfilesResult sse_decode_copy_profiles_result(
    SseDeserializer deserializer,
  );

  @protected
  CoreBasicItemDto sse_decode_core_basic_item_dto(SseDeserializer deserializer);

  @protected
  CoreType sse_decode_core_type(SseDeserializer deserializer);

  @protected
  CoreTypeBindingDto sse_decode_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeleteProfilesResult sse_decode_delete_profiles_result(
    SseDeserializer deserializer,
  );

  @protected
  DeleteSubsResult sse_decode_delete_subs_result(SseDeserializer deserializer);

  @protected
  ErrorDto sse_decode_error_dto(SseDeserializer deserializer);

  @protected
  EventEnvelopeDto sse_decode_event_envelope_dto(SseDeserializer deserializer);

  @protected
  Fragment4RayItemDto sse_decode_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto sse_decode_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  GlobalHotkeyDto sse_decode_global_hotkey_dto(SseDeserializer deserializer);

  @protected
  GroupGenResult sse_decode_group_gen_result(SseDeserializer deserializer);

  @protected
  GrpcItemDto sse_decode_grpc_item_dto(SseDeserializer deserializer);

  @protected
  GuiItemDto sse_decode_gui_item_dto(SseDeserializer deserializer);

  @protected
  HappyEyeballs4RayItemDto sse_decode_happy_eyeballs_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  HysteriaItemDto sse_decode_hysteria_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportResult sse_decode_import_result(SseDeserializer deserializer);

  @protected
  InboundListenerDto sse_decode_inbound_listener_dto(
    SseDeserializer deserializer,
  );

  @protected
  JobDto sse_decode_job_dto(SseDeserializer deserializer);

  @protected
  JobState sse_decode_job_state(SseDeserializer deserializer);

  @protected
  KcpItemDto sse_decode_kcp_item_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CapabilityDto> sse_decode_list_capability_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnItemDto> sse_decode_list_column_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ConfigType> sse_decode_list_config_type(SseDeserializer deserializer);

  @protected
  List<CoreTypeBindingDto> sse_decode_list_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FullConfigTemplateDto> sse_decode_list_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GlobalHotkeyDto> sse_decode_list_global_hotkey_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<InboundListenerDto> sse_decode_list_inbound_listener_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<JobDto> sse_decode_list_job_dto(SseDeserializer deserializer);

  @protected
  List<ParseIssueDto> sse_decode_list_parse_issue_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileDto> sse_decode_list_profile_dto(SseDeserializer deserializer);

  @protected
  List<ProfileSummary> sse_decode_list_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingsChangeDto> sse_decode_list_settings_change_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SubItemDto> sse_decode_list_sub_item_dto(SseDeserializer deserializer);

  @protected
  List<SubUpdateEntryDto> sse_decode_list_sub_update_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<WindowSizeItemDto> sse_decode_list_window_size_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  MsgUiItemDto sse_decode_msg_ui_item_dto(SseDeserializer deserializer);

  @protected
  Mux4RayItemDto sse_decode_mux_4_ray_item_dto(SseDeserializer deserializer);

  @protected
  Mux4SboxItemDto sse_decode_mux_4_sbox_item_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CoreType? sse_decode_opt_box_autoadd_core_type(SseDeserializer deserializer);

  @protected
  ErrorDto? sse_decode_opt_box_autoadd_error_dto(SseDeserializer deserializer);

  @protected
  Fragment4RayItemDto? sse_decode_opt_box_autoadd_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto? sse_decode_opt_box_autoadd_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JobDto? sse_decode_opt_box_autoadd_job_dto(SseDeserializer deserializer);

  @protected
  ProfileDto? sse_decode_opt_box_autoadd_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProfileSummary? sse_decode_opt_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto? sse_decode_opt_box_autoadd_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubItemDto? sse_decode_opt_box_autoadd_sub_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<CoreTypeBindingDto>? sse_decode_opt_list_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParseIssueDto sse_decode_parse_issue_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer);

  @protected
  ProfileFilterDto sse_decode_profile_filter_dto(SseDeserializer deserializer);

  @protected
  ProfilePageDto sse_decode_profile_page_dto(SseDeserializer deserializer);

  @protected
  ProfileSortDto sse_decode_profile_sort_dto(SseDeserializer deserializer);

  @protected
  ProfileSummary sse_decode_profile_summary(SseDeserializer deserializer);

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer);

  @protected
  ProtocolExtraDto sse_decode_protocol_extra_dto(SseDeserializer deserializer);

  @protected
  RecoveryDto sse_decode_recovery_dto(SseDeserializer deserializer);

  @protected
  RevisionState sse_decode_revision_state(SseDeserializer deserializer);

  @protected
  RoutingBasicItemDto sse_decode_routing_basic_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeState sse_decode_runtime_state(SseDeserializer deserializer);

  @protected
  SaveProfileResult sse_decode_save_profile_result(
    SseDeserializer deserializer,
  );

  @protected
  SaveSettingsResult sse_decode_save_settings_result(
    SseDeserializer deserializer,
  );

  @protected
  SecurityDto sse_decode_security_dto(SseDeserializer deserializer);

  @protected
  SettingsChangeDto sse_decode_settings_change_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  SettingsLoadDto sse_decode_settings_load_dto(SseDeserializer deserializer);

  @protected
  ShareExportResult sse_decode_share_export_result(
    SseDeserializer deserializer,
  );

  @protected
  SimpleDnsItemDto sse_decode_simple_dns_item_dto(SseDeserializer deserializer);

  @protected
  SimpleResult sse_decode_simple_result(SseDeserializer deserializer);

  @protected
  SnapshotDto sse_decode_snapshot_dto(SseDeserializer deserializer);

  @protected
  SpeedTestItemDto sse_decode_speed_test_item_dto(SseDeserializer deserializer);

  @protected
  StopRuntimeResult sse_decode_stop_runtime_result(
    SseDeserializer deserializer,
  );

  @protected
  SubItemDto sse_decode_sub_item_dto(SseDeserializer deserializer);

  @protected
  SubItemDtoResult sse_decode_sub_item_dto_result(SseDeserializer deserializer);

  @protected
  SubUpdateEntryDto sse_decode_sub_update_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubUpdateResult sse_decode_sub_update_result(SseDeserializer deserializer);

  @protected
  SubsPageDto sse_decode_subs_page_dto(SseDeserializer deserializer);

  @protected
  SystemProxyItemDto sse_decode_system_proxy_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  TemplateDtoResult sse_decode_template_dto_result(
    SseDeserializer deserializer,
  );

  @protected
  TemplatesPageDto sse_decode_templates_page_dto(SseDeserializer deserializer);

  @protected
  TransportExtraDto sse_decode_transport_extra_dto(
    SseDeserializer deserializer,
  );

  @protected
  TunModeItemDto sse_decode_tun_mode_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiEventAck sse_decode_ui_event_ack(SseDeserializer deserializer);

  @protected
  UiItemDto sse_decode_ui_item_dto(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UriParseResult sse_decode_uri_parse_result(SseDeserializer deserializer);

  @protected
  WebDavItemDto sse_decode_web_dav_item_dto(SseDeserializer deserializer);

  @protected
  WindowSizeItemDto sse_decode_window_size_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_event_envelope_dto_Sse(
    RustStreamSink<EventEnvelopeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_apply_runtime_result(
    ApplyRuntimeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_core_type(
    CoreType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_error_dto(
    ErrorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fragment_4_ray_item_dto(
    Fragment4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_full_config_template_dto(
    FullConfigTemplateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_job_dto(JobDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_profile_dto(
    ProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_profile_filter_dto(
    ProfileFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sub_item_dto(
    SubItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_cancel_outcome(CancelOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_cancel_result(CancelResult self, SseSerializer serializer);

  @protected
  void sse_encode_capability_dto(CapabilityDto self, SseSerializer serializer);

  @protected
  void sse_encode_check_update_item_dto(
    CheckUpdateItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clash_ui_item_dto(
    ClashUiItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_column_item_dto(ColumnItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_config_type(ConfigType self, SseSerializer serializer);

  @protected
  void sse_encode_const_item_dto(ConstItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_copy_profiles_result(
    CopyProfilesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_basic_item_dto(
    CoreBasicItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_type(CoreType self, SseSerializer serializer);

  @protected
  void sse_encode_core_type_binding_dto(
    CoreTypeBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_profiles_result(
    DeleteProfilesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_subs_result(
    DeleteSubsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_dto(ErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_event_envelope_dto(
    EventEnvelopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fragment_4_ray_item_dto(
    Fragment4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_full_config_template_dto(
    FullConfigTemplateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_global_hotkey_dto(
    GlobalHotkeyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_gen_result(
    GroupGenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grpc_item_dto(GrpcItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_gui_item_dto(GuiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_happy_eyeballs_4_ray_item_dto(
    HappyEyeballs4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hysteria_item_dto(
    HysteriaItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_result(ImportResult self, SseSerializer serializer);

  @protected
  void sse_encode_inbound_listener_dto(
    InboundListenerDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_job_dto(JobDto self, SseSerializer serializer);

  @protected
  void sse_encode_job_state(JobState self, SseSerializer serializer);

  @protected
  void sse_encode_kcp_item_dto(KcpItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_capability_dto(
    List<CapabilityDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_item_dto(
    List<ColumnItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_config_type(
    List<ConfigType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_core_type_binding_dto(
    List<CoreTypeBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_full_config_template_dto(
    List<FullConfigTemplateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_global_hotkey_dto(
    List<GlobalHotkeyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_inbound_listener_dto(
    List<InboundListenerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_job_dto(List<JobDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_parse_issue_dto(
    List<ParseIssueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_dto(
    List<ProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_summary(
    List<ProfileSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_settings_change_dto(
    List<SettingsChangeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_item_dto(
    List<SubItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_update_entry_dto(
    List<SubUpdateEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_window_size_item_dto(
    List<WindowSizeItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_msg_ui_item_dto(MsgUiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_mux_4_ray_item_dto(
    Mux4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mux_4_sbox_item_dto(
    Mux4SboxItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_core_type(
    CoreType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_error_dto(
    ErrorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_fragment_4_ray_item_dto(
    Fragment4RayItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_full_config_template_dto(
    FullConfigTemplateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_job_dto(
    JobDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_profile_dto(
    ProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_profile_summary(
    ProfileSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_settings_dto(
    SettingsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sub_item_dto(
    SubItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_core_type_binding_dto(
    List<CoreTypeBindingDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parse_issue_dto(ParseIssueDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_filter_dto(
    ProfileFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_page_dto(
    ProfilePageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_sort_dto(
    ProfileSortDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_extra_dto(
    ProtocolExtraDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_dto(RecoveryDto self, SseSerializer serializer);

  @protected
  void sse_encode_revision_state(RevisionState self, SseSerializer serializer);

  @protected
  void sse_encode_routing_basic_item_dto(
    RoutingBasicItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_state(RuntimeState self, SseSerializer serializer);

  @protected
  void sse_encode_save_profile_result(
    SaveProfileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_settings_result(
    SaveSettingsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_security_dto(SecurityDto self, SseSerializer serializer);

  @protected
  void sse_encode_settings_change_dto(
    SettingsChangeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_settings_load_dto(
    SettingsLoadDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_export_result(
    ShareExportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simple_dns_item_dto(
    SimpleDnsItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simple_result(SimpleResult self, SseSerializer serializer);

  @protected
  void sse_encode_snapshot_dto(SnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_speed_test_item_dto(
    SpeedTestItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stop_runtime_result(
    StopRuntimeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_item_dto(SubItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_sub_item_dto_result(
    SubItemDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_update_entry_dto(
    SubUpdateEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_update_result(
    SubUpdateResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subs_page_dto(SubsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_system_proxy_item_dto(
    SystemProxyItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_dto_result(
    TemplateDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_templates_page_dto(
    TemplatesPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_extra_dto(
    TransportExtraDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tun_mode_item_dto(
    TunModeItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event_ack(UiEventAck self, SseSerializer serializer);

  @protected
  void sse_encode_ui_item_dto(UiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_uri_parse_result(
    UriParseResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_item_dto(
    WebDavItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_window_size_item_dto(
    WindowSizeItemDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
