// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/contract.dart';
import 'api/dns.dart';
import 'api/engine.dart';
import 'api/groups.dart';
import 'api/mirrors.dart';
import 'api/monitor.dart';
import 'api/platform.dart';
import 'api/profiles.dart';
import 'api/routing.dart';
import 'api/settings.dart';
import 'api/speedtest.dart';
import 'api/stable.dart';
import 'api/subs.dart';
import 'api/t16.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EventEnvelopeDto> dco_decode_StreamSink_event_envelope_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogBatchDto> dco_decode_StreamSink_log_batch_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SpeedTestBatchDto>
  dco_decode_StreamSink_speed_test_batch_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<TrafficBatchDto> dco_decode_StreamSink_traffic_batch_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActualRuntimeDto dco_decode_actual_runtime_dto(dynamic raw);

  @protected
  AppRestartCommandDto dco_decode_app_restart_command_dto(dynamic raw);

  @protected
  AppRollbackResultDto dco_decode_app_rollback_result_dto(dynamic raw);

  @protected
  AppliedChangeDto dco_decode_applied_change_dto(dynamic raw);

  @protected
  AppliedCoreDto dco_decode_applied_core_dto(dynamic raw);

  @protected
  AppliedInboundDto dco_decode_applied_inbound_dto(dynamic raw);

  @protected
  ApplyCoreResultDto dco_decode_apply_core_result_dto(dynamic raw);

  @protected
  ApplyRuntimeResult dco_decode_apply_runtime_result(dynamic raw);

  @protected
  BackupListDto dco_decode_backup_list_dto(dynamic raw);

  @protected
  BackupManifestDto dco_decode_backup_manifest_dto(dynamic raw);

  @protected
  BackupResultDto dco_decode_backup_result_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActualRuntimeDto dco_decode_box_autoadd_actual_runtime_dto(dynamic raw);

  @protected
  BackupManifestDto dco_decode_box_autoadd_backup_manifest_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CancelOutcome dco_decode_box_autoadd_cancel_outcome(dynamic raw);

  @protected
  CoreType dco_decode_box_autoadd_core_type(dynamic raw);

  @protected
  DnsProfileDto dco_decode_box_autoadd_dns_profile_dto(dynamic raw);

  @protected
  ErrorDto dco_decode_box_autoadd_error_dto(dynamic raw);

  @protected
  ExitFactDto dco_decode_box_autoadd_exit_fact_dto(dynamic raw);

  @protected
  Fragment4RayItemDto dco_decode_box_autoadd_fragment_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  FullConfigTemplateDto dco_decode_box_autoadd_full_config_template_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  JobDto dco_decode_box_autoadd_job_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_box_autoadd_profile_dto(dynamic raw);

  @protected
  ProfileFilterDto dco_decode_box_autoadd_profile_filter_dto(dynamic raw);

  @protected
  ProfileSummary dco_decode_box_autoadd_profile_summary(dynamic raw);

  @protected
  ProxyStateDto dco_decode_box_autoadd_proxy_state_dto(dynamic raw);

  @protected
  RoutingProfileDto dco_decode_box_autoadd_routing_profile_dto(dynamic raw);

  @protected
  RuntimeTunDto dco_decode_box_autoadd_runtime_tun_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_box_autoadd_settings_dto(dynamic raw);

  @protected
  SimpleDnsDto dco_decode_box_autoadd_simple_dns_dto(dynamic raw);

  @protected
  SubItemDto dco_decode_box_autoadd_sub_item_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  WebDavConfigDto dco_decode_box_autoadd_web_dav_config_dto(dynamic raw);

  @protected
  CancelOutcome dco_decode_cancel_outcome(dynamic raw);

  @protected
  CancelResult dco_decode_cancel_result(dynamic raw);

  @protected
  CapabilityDto dco_decode_capability_dto(dynamic raw);

  @protected
  CertCommandDto dco_decode_cert_command_dto(dynamic raw);

  @protected
  CertProviderDto dco_decode_cert_provider_dto(dynamic raw);

  @protected
  CheckUpdateItemDto dco_decode_check_update_item_dto(dynamic raw);

  @protected
  ClashConnectionDto dco_decode_clash_connection_dto(dynamic raw);

  @protected
  ClashConnectionsDto dco_decode_clash_connections_dto(dynamic raw);

  @protected
  ClashModeDto dco_decode_clash_mode_dto(dynamic raw);

  @protected
  ClashProxiesDto dco_decode_clash_proxies_dto(dynamic raw);

  @protected
  ClashProxyDto dco_decode_clash_proxy_dto(dynamic raw);

  @protected
  ClashUiItemDto dco_decode_clash_ui_item_dto(dynamic raw);

  @protected
  CleanupResultDto dco_decode_cleanup_result_dto(dynamic raw);

  @protected
  ColumnItemDto dco_decode_column_item_dto(dynamic raw);

  @protected
  ConfigType dco_decode_config_type(dynamic raw);

  @protected
  ConstItemDto dco_decode_const_item_dto(dynamic raw);

  @protected
  CopyProfilesResult dco_decode_copy_profiles_result(dynamic raw);

  @protected
  CoreBasicItemDto dco_decode_core_basic_item_dto(dynamic raw);

  @protected
  CoreType dco_decode_core_type(dynamic raw);

  @protected
  CoreTypeBindingDto dco_decode_core_type_binding_dto(dynamic raw);

  @protected
  CoreUpdateDto dco_decode_core_update_dto(dynamic raw);

  @protected
  CoreVersionsDto dco_decode_core_versions_dto(dynamic raw);

  @protected
  CustomFileResult dco_decode_custom_file_result(dynamic raw);

  @protected
  DelayResultDto dco_decode_delay_result_dto(dynamic raw);

  @protected
  DeleteProfilesResult dco_decode_delete_profiles_result(dynamic raw);

  @protected
  DeleteSubsResult dco_decode_delete_subs_result(dynamic raw);

  @protected
  DnsDtoResult dco_decode_dns_dto_result(dynamic raw);

  @protected
  DnsPageDto dco_decode_dns_page_dto(dynamic raw);

  @protected
  DnsProfileDto dco_decode_dns_profile_dto(dynamic raw);

  @protected
  EntityCountDto dco_decode_entity_count_dto(dynamic raw);

  @protected
  ErrorDto dco_decode_error_dto(dynamic raw);

  @protected
  EventEnvelopeDto dco_decode_event_envelope_dto(dynamic raw);

  @protected
  ExitFactDto dco_decode_exit_fact_dto(dynamic raw);

  @protected
  ExportClientConfigDto dco_decode_export_client_config_dto(dynamic raw);

  @protected
  ExternalSpecDto dco_decode_external_spec_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Fragment4RayItemDto dco_decode_fragment_4_ray_item_dto(dynamic raw);

  @protected
  FullConfigTemplateDto dco_decode_full_config_template_dto(dynamic raw);

  @protected
  GlobalHotkeyDto dco_decode_global_hotkey_dto(dynamic raw);

  @protected
  GroupDelayDto dco_decode_group_delay_dto(dynamic raw);

  @protected
  GroupGenResult dco_decode_group_gen_result(dynamic raw);

  @protected
  GrpcItemDto dco_decode_grpc_item_dto(dynamic raw);

  @protected
  GuiItemDto dco_decode_gui_item_dto(dynamic raw);

  @protected
  HappyEyeballs4RayItemDto dco_decode_happy_eyeballs_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  HotkeyDto dco_decode_hotkey_dto(dynamic raw);

  @protected
  HysteriaItemDto dco_decode_hysteria_item_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportResult dco_decode_import_result(dynamic raw);

  @protected
  ImportSummaryDto dco_decode_import_summary_dto(dynamic raw);

  @protected
  InboundListenerDto dco_decode_inbound_listener_dto(dynamic raw);

  @protected
  InstalledCoreDto dco_decode_installed_core_dto(dynamic raw);

  @protected
  JobDto dco_decode_job_dto(dynamic raw);

  @protected
  JobState dco_decode_job_state(dynamic raw);

  @protected
  KcpItemDto dco_decode_kcp_item_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AppliedChangeDto> dco_decode_list_applied_change_dto(dynamic raw);

  @protected
  List<AppliedCoreDto> dco_decode_list_applied_core_dto(dynamic raw);

  @protected
  List<BackupManifestDto> dco_decode_list_backup_manifest_dto(dynamic raw);

  @protected
  List<CapabilityDto> dco_decode_list_capability_dto(dynamic raw);

  @protected
  List<ClashConnectionDto> dco_decode_list_clash_connection_dto(dynamic raw);

  @protected
  List<ClashProxyDto> dco_decode_list_clash_proxy_dto(dynamic raw);

  @protected
  List<ColumnItemDto> dco_decode_list_column_item_dto(dynamic raw);

  @protected
  List<ConfigType> dco_decode_list_config_type(dynamic raw);

  @protected
  List<CoreTypeBindingDto> dco_decode_list_core_type_binding_dto(dynamic raw);

  @protected
  List<CoreUpdateDto> dco_decode_list_core_update_dto(dynamic raw);

  @protected
  List<DelayResultDto> dco_decode_list_delay_result_dto(dynamic raw);

  @protected
  List<DnsProfileDto> dco_decode_list_dns_profile_dto(dynamic raw);

  @protected
  List<EntityCountDto> dco_decode_list_entity_count_dto(dynamic raw);

  @protected
  List<FullConfigTemplateDto> dco_decode_list_full_config_template_dto(
    dynamic raw,
  );

  @protected
  List<GlobalHotkeyDto> dco_decode_list_global_hotkey_dto(dynamic raw);

  @protected
  List<HotkeyDto> dco_decode_list_hotkey_dto(dynamic raw);

  @protected
  List<InboundListenerDto> dco_decode_list_inbound_listener_dto(dynamic raw);

  @protected
  List<InstalledCoreDto> dco_decode_list_installed_core_dto(dynamic raw);

  @protected
  List<JobDto> dco_decode_list_job_dto(dynamic raw);

  @protected
  List<LogLineDto> dco_decode_list_log_line_dto(dynamic raw);

  @protected
  List<NodeTrafficDto> dco_decode_list_node_traffic_dto(dynamic raw);

  @protected
  List<ParseIssueDto> dco_decode_list_parse_issue_dto(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileDto> dco_decode_list_profile_dto(dynamic raw);

  @protected
  List<ProfileSummary> dco_decode_list_profile_summary(dynamic raw);

  @protected
  List<ProxyOwnershipDto> dco_decode_list_proxy_ownership_dto(dynamic raw);

  @protected
  List<ResourceFailureDto> dco_decode_list_resource_failure_dto(dynamic raw);

  @protected
  List<RestoreActionDto> dco_decode_list_restore_action_dto(dynamic raw);

  @protected
  List<RestoreConflictDto> dco_decode_list_restore_conflict_dto(dynamic raw);

  @protected
  List<RoutingProfileDto> dco_decode_list_routing_profile_dto(dynamic raw);

  @protected
  List<RoutingRuleDto> dco_decode_list_routing_rule_dto(dynamic raw);

  @protected
  List<RoutingWarningDto> dco_decode_list_routing_warning_dto(dynamic raw);

  @protected
  List<SettingsChangeDto> dco_decode_list_settings_change_dto(dynamic raw);

  @protected
  List<SpeedTestResultDto> dco_decode_list_speed_test_result_dto(dynamic raw);

  @protected
  List<SubItemDto> dco_decode_list_sub_item_dto(dynamic raw);

  @protected
  List<SubUpdateEntryDto> dco_decode_list_sub_update_entry_dto(dynamic raw);

  @protected
  List<UpdateTargetDto> dco_decode_list_update_target_dto(dynamic raw);

  @protected
  List<WebDavEntryDto> dco_decode_list_web_dav_entry_dto(dynamic raw);

  @protected
  List<WindowSizeItemDto> dco_decode_list_window_size_item_dto(dynamic raw);

  @protected
  LogBatchDto dco_decode_log_batch_dto(dynamic raw);

  @protected
  LogLineDto dco_decode_log_line_dto(dynamic raw);

  @protected
  LogPageDto dco_decode_log_page_dto(dynamic raw);

  @protected
  MonitorActionResult dco_decode_monitor_action_result(dynamic raw);

  @protected
  MsgUiItemDto dco_decode_msg_ui_item_dto(dynamic raw);

  @protected
  Mux4RayItemDto dco_decode_mux_4_ray_item_dto(dynamic raw);

  @protected
  Mux4SboxItemDto dco_decode_mux_4_sbox_item_dto(dynamic raw);

  @protected
  NodeTrafficDto dco_decode_node_traffic_dto(dynamic raw);

  @protected
  OperationStatusDto dco_decode_operation_status_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ActualRuntimeDto? dco_decode_opt_box_autoadd_actual_runtime_dto(dynamic raw);

  @protected
  BackupManifestDto? dco_decode_opt_box_autoadd_backup_manifest_dto(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CancelOutcome? dco_decode_opt_box_autoadd_cancel_outcome(dynamic raw);

  @protected
  CoreType? dco_decode_opt_box_autoadd_core_type(dynamic raw);

  @protected
  DnsProfileDto? dco_decode_opt_box_autoadd_dns_profile_dto(dynamic raw);

  @protected
  ErrorDto? dco_decode_opt_box_autoadd_error_dto(dynamic raw);

  @protected
  ExitFactDto? dco_decode_opt_box_autoadd_exit_fact_dto(dynamic raw);

  @protected
  Fragment4RayItemDto? dco_decode_opt_box_autoadd_fragment_4_ray_item_dto(
    dynamic raw,
  );

  @protected
  FullConfigTemplateDto? dco_decode_opt_box_autoadd_full_config_template_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  JobDto? dco_decode_opt_box_autoadd_job_dto(dynamic raw);

  @protected
  ProfileDto? dco_decode_opt_box_autoadd_profile_dto(dynamic raw);

  @protected
  ProfileSummary? dco_decode_opt_box_autoadd_profile_summary(dynamic raw);

  @protected
  ProxyStateDto? dco_decode_opt_box_autoadd_proxy_state_dto(dynamic raw);

  @protected
  RoutingProfileDto? dco_decode_opt_box_autoadd_routing_profile_dto(
    dynamic raw,
  );

  @protected
  RuntimeTunDto? dco_decode_opt_box_autoadd_runtime_tun_dto(dynamic raw);

  @protected
  SettingsDto? dco_decode_opt_box_autoadd_settings_dto(dynamic raw);

  @protected
  SimpleDnsDto? dco_decode_opt_box_autoadd_simple_dns_dto(dynamic raw);

  @protected
  SubItemDto? dco_decode_opt_box_autoadd_sub_item_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  WebDavConfigDto? dco_decode_opt_box_autoadd_web_dav_config_dto(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<CoreTypeBindingDto>? dco_decode_opt_list_core_type_binding_dto(
    dynamic raw,
  );

  @protected
  PacHandleDto dco_decode_pac_handle_dto(dynamic raw);

  @protected
  PacScriptDto dco_decode_pac_script_dto(dynamic raw);

  @protected
  PageVisibilityDto dco_decode_page_visibility_dto(dynamic raw);

  @protected
  ParseIssueDto dco_decode_parse_issue_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw);

  @protected
  ProfileFilterDto dco_decode_profile_filter_dto(dynamic raw);

  @protected
  ProfilePageDto dco_decode_profile_page_dto(dynamic raw);

  @protected
  ProfileSortDto dco_decode_profile_sort_dto(dynamic raw);

  @protected
  ProfileSummary dco_decode_profile_summary(dynamic raw);

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw);

  @protected
  ProtocolExtraDto dco_decode_protocol_extra_dto(dynamic raw);

  @protected
  ProxyOwnershipDto dco_decode_proxy_ownership_dto(dynamic raw);

  @protected
  ProxyStateDto dco_decode_proxy_state_dto(dynamic raw);

  @protected
  RecognitionDto dco_decode_recognition_dto(dynamic raw);

  @protected
  RecoveryDto dco_decode_recovery_dto(dynamic raw);

  @protected
  RegionalPresetResult dco_decode_regional_preset_result(dynamic raw);

  @protected
  ResourceFailureDto dco_decode_resource_failure_dto(dynamic raw);

  @protected
  ResourceUpdateReportDto dco_decode_resource_update_report_dto(dynamic raw);

  @protected
  RestoreActionDto dco_decode_restore_action_dto(dynamic raw);

  @protected
  RestoreConflictDto dco_decode_restore_conflict_dto(dynamic raw);

  @protected
  RestoreResultDto dco_decode_restore_result_dto(dynamic raw);

  @protected
  RevisionState dco_decode_revision_state(dynamic raw);

  @protected
  RoutingBasicItemDto dco_decode_routing_basic_item_dto(dynamic raw);

  @protected
  RoutingDtoResult dco_decode_routing_dto_result(dynamic raw);

  @protected
  RoutingProfileDto dco_decode_routing_profile_dto(dynamic raw);

  @protected
  RoutingRuleDto dco_decode_routing_rule_dto(dynamic raw);

  @protected
  RoutingRulesPageDto dco_decode_routing_rules_page_dto(dynamic raw);

  @protected
  RoutingRulesTextResult dco_decode_routing_rules_text_result(dynamic raw);

  @protected
  RoutingWarningDto dco_decode_routing_warning_dto(dynamic raw);

  @protected
  RoutingsPageDto dco_decode_routings_page_dto(dynamic raw);

  @protected
  RuleModeResult dco_decode_rule_mode_result(dynamic raw);

  @protected
  RuntimeState dco_decode_runtime_state(dynamic raw);

  @protected
  RuntimeTunDto dco_decode_runtime_tun_dto(dynamic raw);

  @protected
  SaveProfileResult dco_decode_save_profile_result(dynamic raw);

  @protected
  SaveSettingsResult dco_decode_save_settings_result(dynamic raw);

  @protected
  SecurityDto dco_decode_security_dto(dynamic raw);

  @protected
  SettingsChangeDto dco_decode_settings_change_dto(dynamic raw);

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw);

  @protected
  SettingsLoadDto dco_decode_settings_load_dto(dynamic raw);

  @protected
  ShareExportResult dco_decode_share_export_result(dynamic raw);

  @protected
  SimpleDnsDto dco_decode_simple_dns_dto(dynamic raw);

  @protected
  SimpleDnsDtoResult dco_decode_simple_dns_dto_result(dynamic raw);

  @protected
  SimpleDnsItemDto dco_decode_simple_dns_item_dto(dynamic raw);

  @protected
  SimpleResult dco_decode_simple_result(dynamic raw);

  @protected
  SnapshotDto dco_decode_snapshot_dto(dynamic raw);

  @protected
  SpeedTestBatchDto dco_decode_speed_test_batch_dto(dynamic raw);

  @protected
  SpeedTestItemDto dco_decode_speed_test_item_dto(dynamic raw);

  @protected
  SpeedTestResultDto dco_decode_speed_test_result_dto(dynamic raw);

  @protected
  SpeedTestStartDto dco_decode_speed_test_start_dto(dynamic raw);

  @protected
  SpeedTestSupportDto dco_decode_speed_test_support_dto(dynamic raw);

  @protected
  StatsSnapshotDto dco_decode_stats_snapshot_dto(dynamic raw);

  @protected
  StopRuntimeResult dco_decode_stop_runtime_result(dynamic raw);

  @protected
  SubItemDto dco_decode_sub_item_dto(dynamic raw);

  @protected
  SubItemDtoResult dco_decode_sub_item_dto_result(dynamic raw);

  @protected
  SubUpdateEntryDto dco_decode_sub_update_entry_dto(dynamic raw);

  @protected
  SubUpdateResult dco_decode_sub_update_result(dynamic raw);

  @protected
  SubsPageDto dco_decode_subs_page_dto(dynamic raw);

  @protected
  SysProxyApplyResult dco_decode_sys_proxy_apply_result(dynamic raw);

  @protected
  SysProxyRestoreResult dco_decode_sys_proxy_restore_result(dynamic raw);

  @protected
  SystemProxyItemDto dco_decode_system_proxy_item_dto(dynamic raw);

  @protected
  TemplateDtoResult dco_decode_template_dto_result(dynamic raw);

  @protected
  TemplatesPageDto dco_decode_templates_page_dto(dynamic raw);

  @protected
  TrafficBatchDto dco_decode_traffic_batch_dto(dynamic raw);

  @protected
  TransportExtraDto dco_decode_transport_extra_dto(dynamic raw);

  @protected
  TunModeItemDto dco_decode_tun_mode_item_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiEventAck dco_decode_ui_event_ack(dynamic raw);

  @protected
  UiItemDto dco_decode_ui_item_dto(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateReportDto dco_decode_update_report_dto(dynamic raw);

  @protected
  UpdateTargetDto dco_decode_update_target_dto(dynamic raw);

  @protected
  UriParseResult dco_decode_uri_parse_result(dynamic raw);

  @protected
  VerificationDto dco_decode_verification_dto(dynamic raw);

  @protected
  WebDavCheckDto dco_decode_web_dav_check_dto(dynamic raw);

  @protected
  WebDavConfigDto dco_decode_web_dav_config_dto(dynamic raw);

  @protected
  WebDavConfigResultDto dco_decode_web_dav_config_result_dto(dynamic raw);

  @protected
  WebDavEntryDto dco_decode_web_dav_entry_dto(dynamic raw);

  @protected
  WebDavItemDto dco_decode_web_dav_item_dto(dynamic raw);

  @protected
  WebDavListDto dco_decode_web_dav_list_dto(dynamic raw);

  @protected
  WebDavOpDto dco_decode_web_dav_op_dto(dynamic raw);

  @protected
  WindowSizeItemDto dco_decode_window_size_item_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EventEnvelopeDto> sse_decode_StreamSink_event_envelope_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogBatchDto> sse_decode_StreamSink_log_batch_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SpeedTestBatchDto>
  sse_decode_StreamSink_speed_test_batch_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TrafficBatchDto> sse_decode_StreamSink_traffic_batch_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActualRuntimeDto sse_decode_actual_runtime_dto(SseDeserializer deserializer);

  @protected
  AppRestartCommandDto sse_decode_app_restart_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  AppRollbackResultDto sse_decode_app_rollback_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  AppliedChangeDto sse_decode_applied_change_dto(SseDeserializer deserializer);

  @protected
  AppliedCoreDto sse_decode_applied_core_dto(SseDeserializer deserializer);

  @protected
  AppliedInboundDto sse_decode_applied_inbound_dto(
    SseDeserializer deserializer,
  );

  @protected
  ApplyCoreResultDto sse_decode_apply_core_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  ApplyRuntimeResult sse_decode_apply_runtime_result(
    SseDeserializer deserializer,
  );

  @protected
  BackupListDto sse_decode_backup_list_dto(SseDeserializer deserializer);

  @protected
  BackupManifestDto sse_decode_backup_manifest_dto(
    SseDeserializer deserializer,
  );

  @protected
  BackupResultDto sse_decode_backup_result_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActualRuntimeDto sse_decode_box_autoadd_actual_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BackupManifestDto sse_decode_box_autoadd_backup_manifest_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CancelOutcome sse_decode_box_autoadd_cancel_outcome(
    SseDeserializer deserializer,
  );

  @protected
  CoreType sse_decode_box_autoadd_core_type(SseDeserializer deserializer);

  @protected
  DnsProfileDto sse_decode_box_autoadd_dns_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ErrorDto sse_decode_box_autoadd_error_dto(SseDeserializer deserializer);

  @protected
  ExitFactDto sse_decode_box_autoadd_exit_fact_dto(
    SseDeserializer deserializer,
  );

  @protected
  Fragment4RayItemDto sse_decode_box_autoadd_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto sse_decode_box_autoadd_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JobDto sse_decode_box_autoadd_job_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_box_autoadd_profile_dto(SseDeserializer deserializer);

  @protected
  ProfileFilterDto sse_decode_box_autoadd_profile_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProfileSummary sse_decode_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  ProxyStateDto sse_decode_box_autoadd_proxy_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingProfileDto sse_decode_box_autoadd_routing_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeTunDto sse_decode_box_autoadd_runtime_tun_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_box_autoadd_settings_dto(SseDeserializer deserializer);

  @protected
  SimpleDnsDto sse_decode_box_autoadd_simple_dns_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubItemDto sse_decode_box_autoadd_sub_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  WebDavConfigDto sse_decode_box_autoadd_web_dav_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  CancelOutcome sse_decode_cancel_outcome(SseDeserializer deserializer);

  @protected
  CancelResult sse_decode_cancel_result(SseDeserializer deserializer);

  @protected
  CapabilityDto sse_decode_capability_dto(SseDeserializer deserializer);

  @protected
  CertCommandDto sse_decode_cert_command_dto(SseDeserializer deserializer);

  @protected
  CertProviderDto sse_decode_cert_provider_dto(SseDeserializer deserializer);

  @protected
  CheckUpdateItemDto sse_decode_check_update_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClashConnectionDto sse_decode_clash_connection_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClashConnectionsDto sse_decode_clash_connections_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClashModeDto sse_decode_clash_mode_dto(SseDeserializer deserializer);

  @protected
  ClashProxiesDto sse_decode_clash_proxies_dto(SseDeserializer deserializer);

  @protected
  ClashProxyDto sse_decode_clash_proxy_dto(SseDeserializer deserializer);

  @protected
  ClashUiItemDto sse_decode_clash_ui_item_dto(SseDeserializer deserializer);

  @protected
  CleanupResultDto sse_decode_cleanup_result_dto(SseDeserializer deserializer);

  @protected
  ColumnItemDto sse_decode_column_item_dto(SseDeserializer deserializer);

  @protected
  ConfigType sse_decode_config_type(SseDeserializer deserializer);

  @protected
  ConstItemDto sse_decode_const_item_dto(SseDeserializer deserializer);

  @protected
  CopyProfilesResult sse_decode_copy_profiles_result(
    SseDeserializer deserializer,
  );

  @protected
  CoreBasicItemDto sse_decode_core_basic_item_dto(SseDeserializer deserializer);

  @protected
  CoreType sse_decode_core_type(SseDeserializer deserializer);

  @protected
  CoreTypeBindingDto sse_decode_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  CoreUpdateDto sse_decode_core_update_dto(SseDeserializer deserializer);

  @protected
  CoreVersionsDto sse_decode_core_versions_dto(SseDeserializer deserializer);

  @protected
  CustomFileResult sse_decode_custom_file_result(SseDeserializer deserializer);

  @protected
  DelayResultDto sse_decode_delay_result_dto(SseDeserializer deserializer);

  @protected
  DeleteProfilesResult sse_decode_delete_profiles_result(
    SseDeserializer deserializer,
  );

  @protected
  DeleteSubsResult sse_decode_delete_subs_result(SseDeserializer deserializer);

  @protected
  DnsDtoResult sse_decode_dns_dto_result(SseDeserializer deserializer);

  @protected
  DnsPageDto sse_decode_dns_page_dto(SseDeserializer deserializer);

  @protected
  DnsProfileDto sse_decode_dns_profile_dto(SseDeserializer deserializer);

  @protected
  EntityCountDto sse_decode_entity_count_dto(SseDeserializer deserializer);

  @protected
  ErrorDto sse_decode_error_dto(SseDeserializer deserializer);

  @protected
  EventEnvelopeDto sse_decode_event_envelope_dto(SseDeserializer deserializer);

  @protected
  ExitFactDto sse_decode_exit_fact_dto(SseDeserializer deserializer);

  @protected
  ExportClientConfigDto sse_decode_export_client_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExternalSpecDto sse_decode_external_spec_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Fragment4RayItemDto sse_decode_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto sse_decode_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  GlobalHotkeyDto sse_decode_global_hotkey_dto(SseDeserializer deserializer);

  @protected
  GroupDelayDto sse_decode_group_delay_dto(SseDeserializer deserializer);

  @protected
  GroupGenResult sse_decode_group_gen_result(SseDeserializer deserializer);

  @protected
  GrpcItemDto sse_decode_grpc_item_dto(SseDeserializer deserializer);

  @protected
  GuiItemDto sse_decode_gui_item_dto(SseDeserializer deserializer);

  @protected
  HappyEyeballs4RayItemDto sse_decode_happy_eyeballs_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  HotkeyDto sse_decode_hotkey_dto(SseDeserializer deserializer);

  @protected
  HysteriaItemDto sse_decode_hysteria_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportResult sse_decode_import_result(SseDeserializer deserializer);

  @protected
  ImportSummaryDto sse_decode_import_summary_dto(SseDeserializer deserializer);

  @protected
  InboundListenerDto sse_decode_inbound_listener_dto(
    SseDeserializer deserializer,
  );

  @protected
  InstalledCoreDto sse_decode_installed_core_dto(SseDeserializer deserializer);

  @protected
  JobDto sse_decode_job_dto(SseDeserializer deserializer);

  @protected
  JobState sse_decode_job_state(SseDeserializer deserializer);

  @protected
  KcpItemDto sse_decode_kcp_item_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AppliedChangeDto> sse_decode_list_applied_change_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AppliedCoreDto> sse_decode_list_applied_core_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BackupManifestDto> sse_decode_list_backup_manifest_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CapabilityDto> sse_decode_list_capability_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ClashConnectionDto> sse_decode_list_clash_connection_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ClashProxyDto> sse_decode_list_clash_proxy_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnItemDto> sse_decode_list_column_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ConfigType> sse_decode_list_config_type(SseDeserializer deserializer);

  @protected
  List<CoreTypeBindingDto> sse_decode_list_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CoreUpdateDto> sse_decode_list_core_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DelayResultDto> sse_decode_list_delay_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DnsProfileDto> sse_decode_list_dns_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EntityCountDto> sse_decode_list_entity_count_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FullConfigTemplateDto> sse_decode_list_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GlobalHotkeyDto> sse_decode_list_global_hotkey_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<HotkeyDto> sse_decode_list_hotkey_dto(SseDeserializer deserializer);

  @protected
  List<InboundListenerDto> sse_decode_list_inbound_listener_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<InstalledCoreDto> sse_decode_list_installed_core_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<JobDto> sse_decode_list_job_dto(SseDeserializer deserializer);

  @protected
  List<LogLineDto> sse_decode_list_log_line_dto(SseDeserializer deserializer);

  @protected
  List<NodeTrafficDto> sse_decode_list_node_traffic_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ParseIssueDto> sse_decode_list_parse_issue_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileDto> sse_decode_list_profile_dto(SseDeserializer deserializer);

  @protected
  List<ProfileSummary> sse_decode_list_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyOwnershipDto> sse_decode_list_proxy_ownership_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ResourceFailureDto> sse_decode_list_resource_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RestoreActionDto> sse_decode_list_restore_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RestoreConflictDto> sse_decode_list_restore_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RoutingProfileDto> sse_decode_list_routing_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RoutingRuleDto> sse_decode_list_routing_rule_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RoutingWarningDto> sse_decode_list_routing_warning_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingsChangeDto> sse_decode_list_settings_change_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SpeedTestResultDto> sse_decode_list_speed_test_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SubItemDto> sse_decode_list_sub_item_dto(SseDeserializer deserializer);

  @protected
  List<SubUpdateEntryDto> sse_decode_list_sub_update_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<UpdateTargetDto> sse_decode_list_update_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<WebDavEntryDto> sse_decode_list_web_dav_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<WindowSizeItemDto> sse_decode_list_window_size_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  LogBatchDto sse_decode_log_batch_dto(SseDeserializer deserializer);

  @protected
  LogLineDto sse_decode_log_line_dto(SseDeserializer deserializer);

  @protected
  LogPageDto sse_decode_log_page_dto(SseDeserializer deserializer);

  @protected
  MonitorActionResult sse_decode_monitor_action_result(
    SseDeserializer deserializer,
  );

  @protected
  MsgUiItemDto sse_decode_msg_ui_item_dto(SseDeserializer deserializer);

  @protected
  Mux4RayItemDto sse_decode_mux_4_ray_item_dto(SseDeserializer deserializer);

  @protected
  Mux4SboxItemDto sse_decode_mux_4_sbox_item_dto(SseDeserializer deserializer);

  @protected
  NodeTrafficDto sse_decode_node_traffic_dto(SseDeserializer deserializer);

  @protected
  OperationStatusDto sse_decode_operation_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ActualRuntimeDto? sse_decode_opt_box_autoadd_actual_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BackupManifestDto? sse_decode_opt_box_autoadd_backup_manifest_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CancelOutcome? sse_decode_opt_box_autoadd_cancel_outcome(
    SseDeserializer deserializer,
  );

  @protected
  CoreType? sse_decode_opt_box_autoadd_core_type(SseDeserializer deserializer);

  @protected
  DnsProfileDto? sse_decode_opt_box_autoadd_dns_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ErrorDto? sse_decode_opt_box_autoadd_error_dto(SseDeserializer deserializer);

  @protected
  ExitFactDto? sse_decode_opt_box_autoadd_exit_fact_dto(
    SseDeserializer deserializer,
  );

  @protected
  Fragment4RayItemDto? sse_decode_opt_box_autoadd_fragment_4_ray_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FullConfigTemplateDto? sse_decode_opt_box_autoadd_full_config_template_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JobDto? sse_decode_opt_box_autoadd_job_dto(SseDeserializer deserializer);

  @protected
  ProfileDto? sse_decode_opt_box_autoadd_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProfileSummary? sse_decode_opt_box_autoadd_profile_summary(
    SseDeserializer deserializer,
  );

  @protected
  ProxyStateDto? sse_decode_opt_box_autoadd_proxy_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingProfileDto? sse_decode_opt_box_autoadd_routing_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeTunDto? sse_decode_opt_box_autoadd_runtime_tun_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto? sse_decode_opt_box_autoadd_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  SimpleDnsDto? sse_decode_opt_box_autoadd_simple_dns_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubItemDto? sse_decode_opt_box_autoadd_sub_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  WebDavConfigDto? sse_decode_opt_box_autoadd_web_dav_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<CoreTypeBindingDto>? sse_decode_opt_list_core_type_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  PacHandleDto sse_decode_pac_handle_dto(SseDeserializer deserializer);

  @protected
  PacScriptDto sse_decode_pac_script_dto(SseDeserializer deserializer);

  @protected
  PageVisibilityDto sse_decode_page_visibility_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParseIssueDto sse_decode_parse_issue_dto(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer);

  @protected
  ProfileFilterDto sse_decode_profile_filter_dto(SseDeserializer deserializer);

  @protected
  ProfilePageDto sse_decode_profile_page_dto(SseDeserializer deserializer);

  @protected
  ProfileSortDto sse_decode_profile_sort_dto(SseDeserializer deserializer);

  @protected
  ProfileSummary sse_decode_profile_summary(SseDeserializer deserializer);

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer);

  @protected
  ProtocolExtraDto sse_decode_protocol_extra_dto(SseDeserializer deserializer);

  @protected
  ProxyOwnershipDto sse_decode_proxy_ownership_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProxyStateDto sse_decode_proxy_state_dto(SseDeserializer deserializer);

  @protected
  RecognitionDto sse_decode_recognition_dto(SseDeserializer deserializer);

  @protected
  RecoveryDto sse_decode_recovery_dto(SseDeserializer deserializer);

  @protected
  RegionalPresetResult sse_decode_regional_preset_result(
    SseDeserializer deserializer,
  );

  @protected
  ResourceFailureDto sse_decode_resource_failure_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResourceUpdateReportDto sse_decode_resource_update_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  RestoreActionDto sse_decode_restore_action_dto(SseDeserializer deserializer);

  @protected
  RestoreConflictDto sse_decode_restore_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  RestoreResultDto sse_decode_restore_result_dto(SseDeserializer deserializer);

  @protected
  RevisionState sse_decode_revision_state(SseDeserializer deserializer);

  @protected
  RoutingBasicItemDto sse_decode_routing_basic_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingDtoResult sse_decode_routing_dto_result(SseDeserializer deserializer);

  @protected
  RoutingProfileDto sse_decode_routing_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingRuleDto sse_decode_routing_rule_dto(SseDeserializer deserializer);

  @protected
  RoutingRulesPageDto sse_decode_routing_rules_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingRulesTextResult sse_decode_routing_rules_text_result(
    SseDeserializer deserializer,
  );

  @protected
  RoutingWarningDto sse_decode_routing_warning_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutingsPageDto sse_decode_routings_page_dto(SseDeserializer deserializer);

  @protected
  RuleModeResult sse_decode_rule_mode_result(SseDeserializer deserializer);

  @protected
  RuntimeState sse_decode_runtime_state(SseDeserializer deserializer);

  @protected
  RuntimeTunDto sse_decode_runtime_tun_dto(SseDeserializer deserializer);

  @protected
  SaveProfileResult sse_decode_save_profile_result(
    SseDeserializer deserializer,
  );

  @protected
  SaveSettingsResult sse_decode_save_settings_result(
    SseDeserializer deserializer,
  );

  @protected
  SecurityDto sse_decode_security_dto(SseDeserializer deserializer);

  @protected
  SettingsChangeDto sse_decode_settings_change_dto(
    SseDeserializer deserializer,
  );

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer);

  @protected
  SettingsLoadDto sse_decode_settings_load_dto(SseDeserializer deserializer);

  @protected
  ShareExportResult sse_decode_share_export_result(
    SseDeserializer deserializer,
  );

  @protected
  SimpleDnsDto sse_decode_simple_dns_dto(SseDeserializer deserializer);

  @protected
  SimpleDnsDtoResult sse_decode_simple_dns_dto_result(
    SseDeserializer deserializer,
  );

  @protected
  SimpleDnsItemDto sse_decode_simple_dns_item_dto(SseDeserializer deserializer);

  @protected
  SimpleResult sse_decode_simple_result(SseDeserializer deserializer);

  @protected
  SnapshotDto sse_decode_snapshot_dto(SseDeserializer deserializer);

  @protected
  SpeedTestBatchDto sse_decode_speed_test_batch_dto(
    SseDeserializer deserializer,
  );

  @protected
  SpeedTestItemDto sse_decode_speed_test_item_dto(SseDeserializer deserializer);

  @protected
  SpeedTestResultDto sse_decode_speed_test_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  SpeedTestStartDto sse_decode_speed_test_start_dto(
    SseDeserializer deserializer,
  );

  @protected
  SpeedTestSupportDto sse_decode_speed_test_support_dto(
    SseDeserializer deserializer,
  );

  @protected
  StatsSnapshotDto sse_decode_stats_snapshot_dto(SseDeserializer deserializer);

  @protected
  StopRuntimeResult sse_decode_stop_runtime_result(
    SseDeserializer deserializer,
  );

  @protected
  SubItemDto sse_decode_sub_item_dto(SseDeserializer deserializer);

  @protected
  SubItemDtoResult sse_decode_sub_item_dto_result(SseDeserializer deserializer);

  @protected
  SubUpdateEntryDto sse_decode_sub_update_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubUpdateResult sse_decode_sub_update_result(SseDeserializer deserializer);

  @protected
  SubsPageDto sse_decode_subs_page_dto(SseDeserializer deserializer);

  @protected
  SysProxyApplyResult sse_decode_sys_proxy_apply_result(
    SseDeserializer deserializer,
  );

  @protected
  SysProxyRestoreResult sse_decode_sys_proxy_restore_result(
    SseDeserializer deserializer,
  );

  @protected
  SystemProxyItemDto sse_decode_system_proxy_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  TemplateDtoResult sse_decode_template_dto_result(
    SseDeserializer deserializer,
  );

  @protected
  TemplatesPageDto sse_decode_templates_page_dto(SseDeserializer deserializer);

  @protected
  TrafficBatchDto sse_decode_traffic_batch_dto(SseDeserializer deserializer);

  @protected
  TransportExtraDto sse_decode_transport_extra_dto(
    SseDeserializer deserializer,
  );

  @protected
  TunModeItemDto sse_decode_tun_mode_item_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiEventAck sse_decode_ui_event_ack(SseDeserializer deserializer);

  @protected
  UiItemDto sse_decode_ui_item_dto(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateReportDto sse_decode_update_report_dto(SseDeserializer deserializer);

  @protected
  UpdateTargetDto sse_decode_update_target_dto(SseDeserializer deserializer);

  @protected
  UriParseResult sse_decode_uri_parse_result(SseDeserializer deserializer);

  @protected
  VerificationDto sse_decode_verification_dto(SseDeserializer deserializer);

  @protected
  WebDavCheckDto sse_decode_web_dav_check_dto(SseDeserializer deserializer);

  @protected
  WebDavConfigDto sse_decode_web_dav_config_dto(SseDeserializer deserializer);

  @protected
  WebDavConfigResultDto sse_decode_web_dav_config_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  WebDavEntryDto sse_decode_web_dav_entry_dto(SseDeserializer deserializer);

  @protected
  WebDavItemDto sse_decode_web_dav_item_dto(SseDeserializer deserializer);

  @protected
  WebDavListDto sse_decode_web_dav_list_dto(SseDeserializer deserializer);

  @protected
  WebDavOpDto sse_decode_web_dav_op_dto(SseDeserializer deserializer);

  @protected
  WindowSizeItemDto sse_decode_window_size_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_event_envelope_dto_Sse(
    RustStreamSink<EventEnvelopeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_batch_dto_Sse(
    RustStreamSink<LogBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_speed_test_batch_dto_Sse(
    RustStreamSink<SpeedTestBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_traffic_batch_dto_Sse(
    RustStreamSink<TrafficBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_actual_runtime_dto(
    ActualRuntimeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_restart_command_dto(
    AppRestartCommandDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_rollback_result_dto(
    AppRollbackResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_applied_change_dto(
    AppliedChangeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_applied_core_dto(
    AppliedCoreDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_applied_inbound_dto(
    AppliedInboundDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_apply_core_result_dto(
    ApplyCoreResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_apply_runtime_result(
    ApplyRuntimeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backup_list_dto(BackupListDto self, SseSerializer serializer);

  @protected
  void sse_encode_backup_manifest_dto(
    BackupManifestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backup_result_dto(
    BackupResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_actual_runtime_dto(
    ActualRuntimeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_backup_manifest_dto(
    BackupManifestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cancel_outcome(
    CancelOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_core_type(
    CoreType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_dns_profile_dto(
    DnsProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_error_dto(
    ErrorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_exit_fact_dto(
    ExitFactDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fragment_4_ray_item_dto(
    Fragment4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_full_config_template_dto(
    FullConfigTemplateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_job_dto(JobDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_profile_dto(
    ProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_profile_filter_dto(
    ProfileFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proxy_state_dto(
    ProxyStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_routing_profile_dto(
    RoutingProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_runtime_tun_dto(
    RuntimeTunDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings_dto(
    SettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_simple_dns_dto(
    SimpleDnsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sub_item_dto(
    SubItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_dav_config_dto(
    WebDavConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cancel_outcome(CancelOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_cancel_result(CancelResult self, SseSerializer serializer);

  @protected
  void sse_encode_capability_dto(CapabilityDto self, SseSerializer serializer);

  @protected
  void sse_encode_cert_command_dto(
    CertCommandDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cert_provider_dto(
    CertProviderDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_check_update_item_dto(
    CheckUpdateItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clash_connection_dto(
    ClashConnectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clash_connections_dto(
    ClashConnectionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clash_mode_dto(ClashModeDto self, SseSerializer serializer);

  @protected
  void sse_encode_clash_proxies_dto(
    ClashProxiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clash_proxy_dto(ClashProxyDto self, SseSerializer serializer);

  @protected
  void sse_encode_clash_ui_item_dto(
    ClashUiItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cleanup_result_dto(
    CleanupResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_column_item_dto(ColumnItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_config_type(ConfigType self, SseSerializer serializer);

  @protected
  void sse_encode_const_item_dto(ConstItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_copy_profiles_result(
    CopyProfilesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_basic_item_dto(
    CoreBasicItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_type(CoreType self, SseSerializer serializer);

  @protected
  void sse_encode_core_type_binding_dto(
    CoreTypeBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_update_dto(CoreUpdateDto self, SseSerializer serializer);

  @protected
  void sse_encode_core_versions_dto(
    CoreVersionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_file_result(
    CustomFileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delay_result_dto(
    DelayResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_profiles_result(
    DeleteProfilesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_subs_result(
    DeleteSubsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_dto_result(DnsDtoResult self, SseSerializer serializer);

  @protected
  void sse_encode_dns_page_dto(DnsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_dns_profile_dto(DnsProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_count_dto(
    EntityCountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_dto(ErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_event_envelope_dto(
    EventEnvelopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exit_fact_dto(ExitFactDto self, SseSerializer serializer);

  @protected
  void sse_encode_export_client_config_dto(
    ExportClientConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_external_spec_dto(
    ExternalSpecDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fragment_4_ray_item_dto(
    Fragment4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_full_config_template_dto(
    FullConfigTemplateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_global_hotkey_dto(
    GlobalHotkeyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_delay_dto(GroupDelayDto self, SseSerializer serializer);

  @protected
  void sse_encode_group_gen_result(
    GroupGenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grpc_item_dto(GrpcItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_gui_item_dto(GuiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_happy_eyeballs_4_ray_item_dto(
    HappyEyeballs4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hotkey_dto(HotkeyDto self, SseSerializer serializer);

  @protected
  void sse_encode_hysteria_item_dto(
    HysteriaItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_result(ImportResult self, SseSerializer serializer);

  @protected
  void sse_encode_import_summary_dto(
    ImportSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_inbound_listener_dto(
    InboundListenerDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_installed_core_dto(
    InstalledCoreDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_job_dto(JobDto self, SseSerializer serializer);

  @protected
  void sse_encode_job_state(JobState self, SseSerializer serializer);

  @protected
  void sse_encode_kcp_item_dto(KcpItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_applied_change_dto(
    List<AppliedChangeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_applied_core_dto(
    List<AppliedCoreDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_backup_manifest_dto(
    List<BackupManifestDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_capability_dto(
    List<CapabilityDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_clash_connection_dto(
    List<ClashConnectionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_clash_proxy_dto(
    List<ClashProxyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_item_dto(
    List<ColumnItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_config_type(
    List<ConfigType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_core_type_binding_dto(
    List<CoreTypeBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_core_update_dto(
    List<CoreUpdateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_delay_result_dto(
    List<DelayResultDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dns_profile_dto(
    List<DnsProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entity_count_dto(
    List<EntityCountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_full_config_template_dto(
    List<FullConfigTemplateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_global_hotkey_dto(
    List<GlobalHotkeyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hotkey_dto(
    List<HotkeyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_inbound_listener_dto(
    List<InboundListenerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_installed_core_dto(
    List<InstalledCoreDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_job_dto(List<JobDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_log_line_dto(
    List<LogLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_node_traffic_dto(
    List<NodeTrafficDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parse_issue_dto(
    List<ParseIssueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_dto(
    List<ProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile_summary(
    List<ProfileSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_ownership_dto(
    List<ProxyOwnershipDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resource_failure_dto(
    List<ResourceFailureDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_restore_action_dto(
    List<RestoreActionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_restore_conflict_dto(
    List<RestoreConflictDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_routing_profile_dto(
    List<RoutingProfileDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_routing_rule_dto(
    List<RoutingRuleDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_routing_warning_dto(
    List<RoutingWarningDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_settings_change_dto(
    List<SettingsChangeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_speed_test_result_dto(
    List<SpeedTestResultDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_item_dto(
    List<SubItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_update_entry_dto(
    List<SubUpdateEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_update_target_dto(
    List<UpdateTargetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_web_dav_entry_dto(
    List<WebDavEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_window_size_item_dto(
    List<WindowSizeItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_batch_dto(LogBatchDto self, SseSerializer serializer);

  @protected
  void sse_encode_log_line_dto(LogLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_log_page_dto(LogPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_monitor_action_result(
    MonitorActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_msg_ui_item_dto(MsgUiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_mux_4_ray_item_dto(
    Mux4RayItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mux_4_sbox_item_dto(
    Mux4SboxItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_traffic_dto(
    NodeTrafficDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation_status_dto(
    OperationStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_actual_runtime_dto(
    ActualRuntimeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_backup_manifest_dto(
    BackupManifestDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cancel_outcome(
    CancelOutcome? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_core_type(
    CoreType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_dns_profile_dto(
    DnsProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_error_dto(
    ErrorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_exit_fact_dto(
    ExitFactDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_fragment_4_ray_item_dto(
    Fragment4RayItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_full_config_template_dto(
    FullConfigTemplateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_job_dto(
    JobDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_profile_dto(
    ProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_profile_summary(
    ProfileSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_proxy_state_dto(
    ProxyStateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_routing_profile_dto(
    RoutingProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_runtime_tun_dto(
    RuntimeTunDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_settings_dto(
    SettingsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_simple_dns_dto(
    SimpleDnsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sub_item_dto(
    SubItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_web_dav_config_dto(
    WebDavConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_core_type_binding_dto(
    List<CoreTypeBindingDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pac_handle_dto(PacHandleDto self, SseSerializer serializer);

  @protected
  void sse_encode_pac_script_dto(PacScriptDto self, SseSerializer serializer);

  @protected
  void sse_encode_page_visibility_dto(
    PageVisibilityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parse_issue_dto(ParseIssueDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_filter_dto(
    ProfileFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_page_dto(
    ProfilePageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_sort_dto(
    ProfileSortDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_summary(
    ProfileSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_extra_dto(
    ProtocolExtraDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_ownership_dto(
    ProxyOwnershipDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_state_dto(ProxyStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_recognition_dto(
    RecognitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_dto(RecoveryDto self, SseSerializer serializer);

  @protected
  void sse_encode_regional_preset_result(
    RegionalPresetResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_failure_dto(
    ResourceFailureDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_update_report_dto(
    ResourceUpdateReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restore_action_dto(
    RestoreActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restore_conflict_dto(
    RestoreConflictDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restore_result_dto(
    RestoreResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_revision_state(RevisionState self, SseSerializer serializer);

  @protected
  void sse_encode_routing_basic_item_dto(
    RoutingBasicItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_dto_result(
    RoutingDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_profile_dto(
    RoutingProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_rule_dto(
    RoutingRuleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_rules_page_dto(
    RoutingRulesPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_rules_text_result(
    RoutingRulesTextResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routing_warning_dto(
    RoutingWarningDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routings_page_dto(
    RoutingsPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_mode_result(
    RuleModeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_state(RuntimeState self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_tun_dto(RuntimeTunDto self, SseSerializer serializer);

  @protected
  void sse_encode_save_profile_result(
    SaveProfileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_settings_result(
    SaveSettingsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_security_dto(SecurityDto self, SseSerializer serializer);

  @protected
  void sse_encode_settings_change_dto(
    SettingsChangeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_settings_load_dto(
    SettingsLoadDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_export_result(
    ShareExportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simple_dns_dto(SimpleDnsDto self, SseSerializer serializer);

  @protected
  void sse_encode_simple_dns_dto_result(
    SimpleDnsDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simple_dns_item_dto(
    SimpleDnsItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_simple_result(SimpleResult self, SseSerializer serializer);

  @protected
  void sse_encode_snapshot_dto(SnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_speed_test_batch_dto(
    SpeedTestBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speed_test_item_dto(
    SpeedTestItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speed_test_result_dto(
    SpeedTestResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speed_test_start_dto(
    SpeedTestStartDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speed_test_support_dto(
    SpeedTestSupportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_snapshot_dto(
    StatsSnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stop_runtime_result(
    StopRuntimeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_item_dto(SubItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_sub_item_dto_result(
    SubItemDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_update_entry_dto(
    SubUpdateEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_update_result(
    SubUpdateResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subs_page_dto(SubsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_sys_proxy_apply_result(
    SysProxyApplyResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sys_proxy_restore_result(
    SysProxyRestoreResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_system_proxy_item_dto(
    SystemProxyItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_dto_result(
    TemplateDtoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_templates_page_dto(
    TemplatesPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_traffic_batch_dto(
    TrafficBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_extra_dto(
    TransportExtraDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tun_mode_item_dto(
    TunModeItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event_ack(UiEventAck self, SseSerializer serializer);

  @protected
  void sse_encode_ui_item_dto(UiItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_report_dto(
    UpdateReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_update_target_dto(
    UpdateTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uri_parse_result(
    UriParseResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_verification_dto(
    VerificationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_check_dto(
    WebDavCheckDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_config_dto(
    WebDavConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_config_result_dto(
    WebDavConfigResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_entry_dto(
    WebDavEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_item_dto(
    WebDavItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_list_dto(
    WebDavListDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_web_dav_op_dto(WebDavOpDto self, SseSerializer serializer);

  @protected
  void sse_encode_window_size_item_dto(
    WindowSizeItemDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
