/// Top-level settings groups that can be saved independently
/// (`domain::SETTINGS_GROUPS`).
const List<String> defaultSettingsGroups = <String>[
  'IndexId',
  'SubIndexId',
  'CoreBasicItem',
  'TunModeItem',
  'KcpItem',
  'GrpcItem',
  'RoutingBasicItem',
  'GuiItem',
  'MsgUIItem',
  'UiItem',
  'ConstItem',
  'SpeedTestItem',
  'Mux4RayItem',
  'Mux4SboxItem',
  'HysteriaItem',
  'ClashUIItem',
  'SystemProxyItem',
  'WebDavItem',
  'CheckUpdateItem',
  'Fragment4RayItem',
  'Inbound',
  'GlobalHotkeys',
  'CoreTypeItem',
  'SimpleDNSItem',
  'HappyEyeballs4RayItem',
];

/// Canonical default `guiNConfig.json` `Config` tree.
///
/// Mirrors `AppSettings::default()` in `crates/domain/src/settings.rs`
/// (upstream `ConfigHandler.LoadConfig`). Used by the synthetic bridge in
/// widget tests and as a fallback when the native bridge is unavailable. Keys
/// are PascalCase and enums are integers, exactly like the persisted document.
Map<String, dynamic> defaultSettingsJson() => <String, dynamic>{
  'IndexId': null,
  'SubIndexId': null,
  'CoreBasicItem': <String, dynamic>{
    'LogEnabled': false,
    'Loglevel': 'warning',
    'DefFingerprint': null,
    'DefUserAgent': null,
    'SendThrough': null,
    'BindInterface': null,
    'EnableFragment': false,
    'EnableFinalFragment': false,
    'EnableCacheFile4Sbox': true,
  },
  'TunModeItem': <String, dynamic>{
    'EnableTun': false,
    'AutoRoute': true,
    'StrictRoute': true,
    'Stack': null,
    'Mtu': 9000,
    'EnableIPv6Address': false,
    'IcmpRouting': 'rule',
    'EnableLegacyProtect': true,
    'RouteExcludeAddress': null,
    'IPv4Address': null,
    'IPv6Address': null,
  },
  'KcpItem': <String, dynamic>{
    'Mtu': 1350,
    'Tti': 50,
    'UplinkCapacity': 12,
    'DownlinkCapacity': 100,
    'CwndMultiplier': 1,
    'MaxSendingWindow': 2097152,
  },
  'GrpcItem': <String, dynamic>{
    'IdleTimeout': 60,
    'HealthCheckTimeout': 20,
    'PermitWithoutStream': false,
    'InitialWindowsSize': 0,
  },
  'RoutingBasicItem': <String, dynamic>{
    'DomainStrategy': 'AsIs',
    'DomainStrategy4Singbox': null,
    'RoutingIndexId': null,
  },
  'GuiItem': <String, dynamic>{
    'AutoRun': false,
    'EnableStatistics': false,
    'DisplayRealTimeSpeed': false,
    'KeepOlderDedupl': false,
    'AutoUpdateInterval': 0,
    'TrayMenuServersLimit': 20,
    'EnableHWA': false,
    'EnableLog': true,
    'RootCertProvider': 'system',
  },
  'MsgUIItem': <String, dynamic>{'MainMsgFilter': null, 'AutoRefresh': null},
  'UiItem': <String, dynamic>{
    'EnableAutoAdjustMainLvColWidth': false,
    'MainGirdHeight1': 0,
    'MainGirdHeight2': 0,
    'MainGirdOrientation': 1,
    'ColorPrimaryName': null,
    'CurrentTheme': null,
    'CurrentLanguage': 'zh-Hans',
    'CurrentFontFamily': null,
    'CurrentFontSize': 0,
    'EnableDragDropSort': false,
    'DoubleClick2Activate': false,
    'AutoHideStartup': false,
    'Hide2TrayWhenClose': false,
    'MacOSShowInDock': false,
    'MainColumnItem': <dynamic>[],
    'WindowSizeItem': <dynamic>[],
    'HideColumnIpInfo': false,
  },
  'ConstItem': <String, dynamic>{
    'SubConvertUrl': null,
    'GeoSourceUrl': null,
    'SrsSourceUrl': null,
    'RouteRulesTemplateSourceUrl': null,
  },
  'SpeedTestItem': <String, dynamic>{
    'SpeedTestTimeout': 10,
    'SpeedTestUrl': 'https://cachefly.cachefly.net/50mb.test',
    'SpeedPingTestUrl': 'https://www.google.com/generate_204',
    'MixedConcurrencyCount': 10,
    'IPAPIUrl': null,
    'UdpTestTarget': 'ntp:pool.ntp.org',
    'SpeedTestPageSize': null,
    'SpeedTestDelayInterval': null,
  },
  'Mux4RayItem': <String, dynamic>{
    'Concurrency': 8,
    'XudpConcurrency': 16,
    'XudpProxyUDP443': 'reject',
  },
  'Mux4SboxItem': <String, dynamic>{
    'Protocol': 'h2mux',
    'MaxConnections': 8,
    'Padding': null,
  },
  'HysteriaItem': <String, dynamic>{
    'UpMbps': 100,
    'DownMbps': 100,
    'HopInterval': 30,
  },
  'ClashUIItem': <String, dynamic>{
    'EnableIPv6': false,
    'EnableMixinContent': false,
    'ProxiesSorting': 0,
    'ProxiesAutoRefresh': false,
    'ProxiesRefreshInterval': 2,
    'ConnectionsAutoRefresh': false,
    'ConnectionsRefreshInterval': 2,
    'ConnectionsColumnItem': <dynamic>[],
  },
  'SystemProxyItem': <String, dynamic>{
    'SysProxyType': 0,
    'SystemProxyExceptions':
        'localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;'
        '172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;'
        '172.28.*;172.29.*;172.30.*;172.31.*;192.168.*',
    'NotProxyLocalAddress': true,
    'SystemProxyAdvancedProtocol': null,
    'CustomSystemProxyPacPath': null,
    'CustomSystemProxyScriptPath': null,
  },
  'WebDavItem': <String, dynamic>{
    'Url': null,
    'UserName': null,
    'Password': null,
    'DirName': null,
  },
  'CheckUpdateItem': <String, dynamic>{
    'CheckPreReleaseUpdate': false,
    'UpdateViaProxy': true,
    'SelectedCoreTypes': null,
  },
  'Fragment4RayItem': <String, dynamic>{
    'Packets': 'tlshello',
    'Lengths': <dynamic>['50-100'],
    'Delays': <dynamic>['10-20'],
    'MaxSplit': '0',
    'Length': null,
    'Interval': null,
  },
  'Inbound': <dynamic>[
    <String, dynamic>{
      'LocalPort': 10808,
      'Protocol': 0,
      'UdpEnabled': true,
      'SniffingEnabled': true,
      'DestOverride': <dynamic>['http', 'tls'],
      'RouteOnly': false,
      'AllowLANConn': false,
      'NewPort4LAN': false,
      'User': '',
      'Pass': '',
      'SecondLocalPortEnabled': false,
    },
  ],
  'GlobalHotkeys': <dynamic>[],
  'CoreTypeItem': null,
  'SimpleDNSItem': <String, dynamic>{
    'UseSystemHosts': false,
    'AddCommonHosts': true,
    'FakeIP': false,
    'GlobalFakeIp': true,
    'FakeIPRange': '198.18.0.0/15',
    'BlockBindingQuery': true,
    'BlockAAAAQuery': false,
    'DirectDNS': '119.29.29.29',
    'RemoteDNS': 'https://cloudflare-dns.com/dns-query',
    'BootstrapDNS': '119.29.29.29',
    'Strategy4Freedom': null,
    'Strategy4Proxy': null,
    'Strategy4ProxyDial': null,
    'ServeStale': false,
    'ParallelQuery': false,
    'Hosts': null,
    'DirectExpectedIPs': null,
    'EnableHappyEyeballs': false,
  },
  'HappyEyeballs4RayItem': <String, dynamic>{
    'TryDelayMs': 250,
    'PrioritizeIPv6': false,
    'Interleave': 1,
    'MaxConcurrentTry': 4,
  },
};
